### ISSUE TITLE
[BUG] dungeon finder interaction window is not visible

### ISSUE THREAD

**Issue by Undertoe** [JamminL/cata-classic-bugs#1000]
#### 1.1. Description
Right clicking on the dungeon finder window does not provide a window that allows you to teleport to the dungeon or leave the dungeon group.  This pretty much locks you into the instance.

Only work around is `/run LFGTeleport(IsInLFGDungeon())`  to leave or to log out.

**Comment by Yotsutester** [comment]
the script > /script LeaveParty () will also work
