### ISSUE TITLE
[BUG] Void Storage NPC is missing from Stormwind and Orgrimmar

### ISSUE THREAD

**Issue by LordOfOtakus** [JamminL/cata-classic-bugs#1006]
#### 1.1. Description
The NPCs that are supposed to perform Void Storage for the player are not present with the other ethereal NPCs.
  #### 1.2. How to Reproduce
          
           1. Go to The Three Winds shop in Stormwind
           2. Observe the NPCs in the building
           3. Notice that there is no NPC in the middle, between the Reforger and Transmoggrifier
  #### 1.3  Source Material
![Screenshot 2024-04-23 at 4 58 34 PM](https://github.com/JamminL/cata-classic-bugs/assets/75953994/37721211-b41c-4576-9c64-ed200c9d5a7e)

#### 2.1. Description
There should be a Void Storage NPC present, waiting and willing to take junk off player's hands and store it away forever.
  #### 2.2 Source Material
https://wowpedia.fandom.com/wiki/Vaultkeeper_Razhid

**Comment by JamminL** [comment]
Void storage is obsolete on the account of having collections

**Comment by LordOfOtakus** [comment]
I still have things I'd like to store there, and Retail has still kept around Void Storage even after the addition of collections, because it is still relevant to have, by its own original premise:

"In addition to the bank, players will now have access to a new “deep storage” system, allowing characters to free bag space by setting aside coveted gear."

 Coveted gear is not exclusive to things like transmog or toys. People have many reasons they would want to keep something, and there's no indication that its removal is intentional. This is a bug.

**Comment by DFortun81** [comment]
Void Storage is NOT obsolete. Its purpose in Retail is to place items that drop for the wrong character into it as a form of punishment formally dubbed "Transmog Hell". Items such as Tusks of Mannoroth" on my mage have suffered this fate. A fate that is worse than death, much like they deserve.

Just because you think it's obsolete doesn't mean it doesn't have a special purpose for other people.

**Comment by JamminL** [comment]
Maybe obsolete was the wrong word but this change was intentional and the issue will remain closed until blizzard says otherwise, sorry guys

**Comment by DFortun81** [comment]
Curious if there was a public statement regarding Void Storage or if this was only discussed internally. The strangely absent communication we typically get on Beta is troubling to me.

**Comment by ForgeGit** [comment]
A [recent bluepost](https://www.wowhead.com/cata/news/notable-differences-between-cataclsym-classic-4-4-0-and-original-cataclysm-4-0-339080) from the community manager states that:

> It is our intention to **not** add the Void Storage feature to Cataclysm Classic.

There is however a bug with Oggrimar city NPCs were the "Void Storage" remains an option

![image](https://github.com/JamminL/cata-classic-bugs/assets/75605537/9587fb32-1796-4c12-8ac2-522d9b49ffb1)

Unsure if this is the case for other cities.
