### ISSUE TITLE
[BUG] Keyring visible

### ISSUE THREAD

**Issue by JamminL** [JamminL/cata-classic-bugs#1008]
#### 1.1. Description
Keyring is visible on beta
  #### 1.3  Source Material
![image](https://github.com/JamminL/cata-classic-bugs/assets/107503518/ad0cc0c0-7f75-41b1-bc74-261aa711962a)
#### 2.1. Description
There should be no keyring

**Comment by LordOfOtakus** [comment]
Fixed as of today.
