### ISSUE TITLE
[BUG] Searing Flames Cannot Critically Strike

### ISSUE THREAD

**Issue by raethkcj** [JamminL/cata-classic-bugs#1009]
#### 1.1. Description
  Searing Flames' ticks are incapable of being a critical strike.
  #### 1.2. How to Reproduce
           1. Talent into Searing Flames
           2. Wear a fair amount of Crit Rating
           3. Attack enemies with Searing Totem, allowing Searing Flames to tick
  #### 1.3  Source Material
https://classic.warcraftlogs.com/reports/RJwktr4aQ1zCGBVc#boss=-3&difficulty=0&type=damage-done&source=4
Searing Flames shows zero critical strikes, while other spells that use spell crit, but don't benefit from Stormstrike's large crit bonus (Fire Nova, Flametongue Weapon, Flame Shock) show roughly 20% crit chance.
#### 2.1. Description
  Searing Flames should be capable of critically striking, at a rate similar to the crit chance of other spells used by the shaman.
  #### 2.2 Source Material
  A Recount damage meter window showing 14.5% crit chance on Searing Flames
  https://youtu.be/KSHhu_eujMk?si=Rm-QBnI1RbAZqieu&t=611  
![image](https://github.com/JamminL/cata-classic-bugs/assets/7716908/0415875f-7406-42d7-94e8-5a259f7a5cc1)

A scrolling combat text addon showing what appear to be critical Searing Flame ticks. This is less clear, but the assumption based on common Scrolling Combat Text addons is that critical strikes are shown in the center, scrolling straight up, while non-critical hits appear to the left and right, curving away and fading out.
https://youtu.be/ODVd4PGgSPI?si=Cup49PFZkwnuqArF&t=58
Red indicates what we assume are critical strikes, while green indicates non-critical strikes.
![image](https://github.com/JamminL/cata-classic-bugs/assets/7716908/01fb6c75-0bc9-47df-a839-b3d8b746d0d9)

**Comment by freddaxyz** [comment]
appears fixed on live just like #1001

https://i.imgur.com/Tt60GQl.png
