### ISSUE TITLE
[BUG] Glyph of Insect Swarm not providing 30% bonus damage

### ISSUE THREAD

**Issue by ssabbyccatt** [JamminL/cata-classic-bugs#1014]
#### 1.1. Description
Appears to currently be providing about 27% instead of 30%. 
  #### 1.2. How to Reproduce
           1. Cast IS without Glyph on, note values
           2. Cast IS with Glyph on, note values
  #### 1.3  Source Material
IS without glyph - https://cdn.discordapp.com/attachments/1171267821112676363/1233380681816739900/image.png?ex=662ce2c5&is=662b9145&hm=d53a6aef9fa358bc6df2f85e8403c17a5aae49cf13f45d919d3a7a7a08937ce5&
IS with glyph - https://cdn.discordapp.com/attachments/1171267821112676363/1233380748153716786/image.png?ex=662ce2d5&is=662b9155&hm=d18d3001d668cf851200612614d9540a81797e79a8ba368b19c3409fb9a8ffce&
#### 2.1. Description
Glyph of Insect Swarm should provide a 30% damage boost to Insect Swarm.
  #### 2.2 Source Material
https://www.wowhead.com/cata/spell=54830/glyph-of-insect-swarm

**Comment by ssabbyccatt** [comment]
![Screenshot 2024-04-26 095526](https://github.com/JamminL/cata-classic-bugs/assets/99249505/e1907aab-4888-40eb-b5e9-4e2a108b4aaa)
Appears to be some broken interaction between the Glyph+Moonfury

**Comment by raethkcj** [comment]
Closing per comment in #1013
