### ISSUE TITLE
[BUG] If your client is set to french, german, or russian, you cannot see character stats on PaperDoll

### ISSUE THREAD

**Issue by JamminL** [JamminL/cata-classic-bugs#1015]
#### 1.1. Description
Paperdoll will not allow you to see your character stats if your client is french
  #### 1.3  Source Material
![image](https://github.com/JamminL/cata-classic-bugs/assets/107503518/6515a8ee-bd2a-4fe6-a581-d69704d9a6c2)

**Comment by CharWS** [comment]
as of #1133 can see that the stat line background stripes of alternating brightness to delineate rows are also not present

**Comment by artscout** [comment]
Probable cause is that BreakUpLargeNumbers doesn't take in account DECIMAL_SEPERATOR thus enabling this error as german, French or Russian locale uses comma as separator. And yes, for some reason this is original macro name for decimal separator since long ago.
