### ISSUE TITLE
[BUG] Inspecting another player's talents is weird

### ISSUE THREAD

**Issue by JamminL** [JamminL/cata-classic-bugs#1017]
#### 1.1. Description
The first time you inspect someone's talents, this is what it looks like:
  #### 1.3  Source Material
![image](https://github.com/JamminL/cata-classic-bugs/assets/107503518/e56f90bb-c447-46fb-89f3-35d58c404b3f)

**Comment by Avizurax7** [comment]
bumping this, still not fixed.

![image](https://github.com/JamminL/cata-classic-bugs/assets/167564762/ca63c3ec-fd1c-4432-86a8-53ca9c697c80)

**Comment by JamminL** [comment]
The specific issue with the random box is fixed, there's another issue open for the scroll/spacing issue
