### ISSUE TITLE
[BUG] Enemy Nameplates showing marks

### ISSUE THREAD

**Issue by JamminL** [JamminL/cata-classic-bugs#1021]
#### 1.1. Description
Enemy nameplates are showing marks ontop and on the left of it
  #### 1.3  Source Material
![image](https://github.com/JamminL/cata-classic-bugs/assets/107503518/aabee2ba-22a8-4c20-8965-720bea6cff32)

**Comment by CharWS** [comment]
looks to be fixed in build 54427
