### ISSUE TITLE
[BUG] Can't apply cataclysm enchantments to lvl 85 character preset gear

### ISSUE THREAD

**Issue by CharWS** [JamminL/cata-classic-bugs#1022]
#### 1.1. Description
Despite the 85 character presets having ilvl 346 gear equipped the cataclysm vendor enchantments cannot be applied to them (minimum requirement of 300 ilvl)

**Comment by XsExcess** [comment]
Still true on most recent build 54481 04/29

**Comment by Yotsutester** [comment]
I was able to enchant [Enchant Chest - Greater Stamina] and [Enchant Boots - Earthen Vitality] to Flynn's Favorite Chestplate and Ramkahen Front Boots, respectively. See imgur link.

https://imgur.com/a/Y3Evx4x
