### ISSUE TITLE
[BUG] Glyph of Renew provides a 25% bonus rather than a 10% bonus

### ISSUE THREAD

**Issue by raethkcj** [JamminL/cata-classic-bugs#1023]
#### 1.1. Description
  [Glyph of Renew](https://www.wowhead.com/cata/spell=55674/glyph-of-renew) provides 25% increased healing to Renew.
  #### 1.2. How to Reproduce
           1. Cast Renew without Glyph of Renew
           2. Equip Glyph of Renew
           3. Cast Renew, observe 25% increased healing done
#### 2.1. Description
  It should have changed from 25% to 10% going from Wrath to Cata. The SpellEffect seems to have been changed in Wrath Classic to fix a bug, from a standard Modifier in [Build 3.4.0.45189](https://wago.tools/db2/SpellEffect?build=3.4.0.45189&filter[SpellID]=55674&page=1) to a server-side Dummy effect in [Build 3.4.0.45264](https://wago.tools/db2/SpellEffect?build=3.4.0.45264&filter[SpellID]=55674&page=1). It seems that this Classic-only change prevented the effect from being updated during the migration to Cataclysm.
   #### 2.2. Source Material
   https://old.wow.tools/dbc/?dbc=spelleffect&build=4.3.4.15595#page=1&colFilter[24]=exact%3A55674

**Comment by EzzaB** [comment]
This is resolved in 54525
