### ISSUE TITLE
[BUG] Health Regeneration is based on Spirit

### ISSUE THREAD

**Issue by raethkcj** [JamminL/cata-classic-bugs#1026]
#### 1.1. Description
  Currently, Health Regeneration functions identically to how it did in Wrath of the Lich King. It is based on two GameTables, shipped with the game client: `OCTRegenHP.txt` and `RegenHPPerSpt.txt`. The tables contain columns for each class, and rows for each level. For the purposes of this issue I'll use Shaman's level 85 values of `OCTRegenHP = 0.172414` and `RegenHPPerSpt = 0.071429`. The values are identical for an 80 Shaman in Wrath and and 85 Shaman in Cataclysm.
  
  OctRegenHP applies to the first 50 points of Spirit, while RegenHpPerSpt applies to any Spirit over 50. This means the current HP regen per second of a level 85 Shaman is
  `50 * 0.172414 + (Spirit - 50) * 0.071429`
  
  In the Source Material below, you can see highlighted in green that the HP regeneration rate in the Cataclysm Beta matches this formula, aside from some small rounding errors, likely due to actual regen being interpolated based on actual elapsed time from frame rate versus a true 2 second ticker.
  #### 1.2. How to Reproduce
           1. On a Shaman, talent into Mana Tide Totem, which increases your Spirit by a percentage
           2. Take a large chunk of damage out of combat, e.g. from falling damage
           3. Observe the timing and amount of your health regen ticks
           4. Cast Mana Tide Totem
           5. Observe the timing and amount of your health regen ticks
  #### 1.3  Source Material
![image](https://github.com/JamminL/cata-classic-bugs/assets/7716908/8266a610-e668-4597-8cf5-5ef189475788)
#### 2.1. Description
  While historical sources aren't very thorough, they seem to agree that Cataclysm Patch 4.0.1 changed Health Regeneration to be based on a percentage of Maximum Health, that is the same for every Class, rather than on Spirit. They suggest it starts at 20% HP per second at level 1 and reduces to either 1% or 0.75% HP per second by level 85. 
  #### 2.2 Source Material
  > [Health regeneration uses a new formula. Outside of combat, all classes seem to regenerate 0.75% of their maximum health per second before the effects of abilities.](https://warcraft.wiki.gg/wiki/Patch_4.0.1_(undocumented_changes))
  ---
  https://warcraft.wiki.gg/wiki/Health_regeneration  
  > Every two seconds, there is one tick of health regeneration. The value is a percentage of the maximum health, though this percentage decreases with level.
    Health Regeneration is increased by 33% while sitting.
    Trolls regenerate 110% of this amount while out of combat, and 11% of this amount while in combat, due to their racial ability Regeneration.
    At level 1, health regeneration is 20% of maximum health per 2 seconds. Because it is so high, it is impossible to drown a level 1 character.
    
---
   > [I observed 1% of max health regen per tick at level 85, and 20% at level 1.](https://warcraft.wiki.gg/wiki/Talk:Health_regeneration)

**Comment by JamminL** [comment]
Looks fixed as of 54525

**Comment by raethkcj** [comment]
Confirmed, and for posterity:
It does appear to be 25% HP2 at level 1, matching reference material:
![image](https://github.com/JamminL/cata-classic-bugs/assets/7716908/f3835e4b-efb3-4084-99be-14077d95fdb3)
![image](https://github.com/JamminL/cata-classic-bugs/assets/7716908/5517c31e-6344-4057-b9d3-f271f6947d20)

13.78% HP2 on a level 11 Troll (so likely 12.5% HP2 on a level 11 non-Troll)
![image](https://github.com/JamminL/cata-classic-bugs/assets/7716908/3d9f5e2a-78d1-40f7-828c-aab2cb96189d)

6.127% HP2 at level 16:
![image](https://github.com/JamminL/cata-classic-bugs/assets/7716908/de5b95cf-c090-47b2-a0f7-a6a2ce8c6c06)

1% HP2 from level 31 to level 80:
![image](https://github.com/JamminL/cata-classic-bugs/assets/7716908/6c4d0c88-0efe-47fe-a245-73691b2fb2e0)
![image](https://github.com/JamminL/cata-classic-bugs/assets/7716908/8cec64a7-648d-4110-8fb9-57f4553bf95a)

It looks likely that it just halves every few levels (25%, 12.5%, 6.25%, ...) at certain breakpoints between levels 1 and 31, then remains at a flat 1% until at least level 80. 

Quick and dirty WeakAura used for testing: https://wago.io/1j23r53eV
