### ISSUE TITLE
[BUG] Scatter Shot behavior with damage not working currently

### ISSUE THREAD

**Issue by Feorblade** [JamminL/cata-classic-bugs#1028]
#### 1.1. Description
Scatter Shot is not breaking to all damage, pet attacks won't break scatter neither will Shadow Word: Death However it does break to ranged attack damage from the hunter

  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Do this: Cast Scatter Shot on a target
           2. Do that: Send your pet to attack them 
           3. Do this again and voilá}: Watch Scatter Shot stick to the target
  #### 1.3  Source Material
{Video, Posts, etc..}
#### 2.1. Description 
Scatter Shot should be breaking to pet damage and things like Shadow Word; Death
  #### 2.2 Source Material
{Video, Posts, etc..}

**Comment by gekkuxz** [comment]
Adding here that Repentance from retribution paladins has the same issue as Scatter Shot at the moment, aka it won't break from damage
