### ISSUE TITLE
[BUG] Mage Ignite refresh duration/tick count 

### ISSUE THREAD

**Issue by Remidemmi** [JamminL/cata-classic-bugs#1033]
#### 1.1. Description

When you crit with a fire spell, 40% of the damage * mastery bonus will be stored as damage for the ignite, which will then be evenly dealt over its duration. Ignite ticks every 2 seconds and has a 4-second duration, meaning a normal ignite will tick twice, each for half of the total amount stored. If you crit again while ignite is still active, it is refreshed and the damage of the new crit will be added to the remaining total of the ignite, which will then again be dealt evenly spread over each tick.

Currently, a refreshed ignite also has a 2 ticks, but it should be 3 ticks.

#### 1.2. How to Reproduce

Crit to trigger ignite, then crit again while ignite is still active on the target.

#### 1.3. Source Material

{Video, Posts, etc..}

#### 2.1. Description

Refreshing an ignite doesn't always seem to reset its duration; it will often tick less than 2 seconds after it has been refreshed, but for the amount of a combined ignite spread over 3 ticks. I can only accurately describe the behavior of the tick count and amount, but establishing the duration without timestamped combat logs is difficult. My best theory currently is that on refresh the progress towards the next tick is preserved, so rather than refreshing to the full 6 seconds and having to wait 2 seconds for the next tick, it refreshes to 4 seconds + how much time was left until the next tick before the refresh occured.

#### 2.2. Source Material

The best video I've been able to find so far is this. [Link to video](https://youtu.be/TGYUVoYujpI?si=5UlxAQsLe2cZS-rv&t=112)

This video has a readable and well-setup combat log, so we can track the amount of each crit and ignite tick. He also displays his stats on the bottom right above his minimap, listing his mastery as 33.93%, which matches the math I'm doing. Adding this mastery to the baseline 40% ignite damage gives us 53.572% of crit damage converted to ignite, which I will be using for the math in the rest of this.

Looking at his crits and ignites in detail from 1:53 onwards:

He starts his ignite with a fireball crit of 53,917 at 1:53, which gives us a total stored ignite damage of 53,917 * 0.53572 = 28,884.4152.

Before ignite gets to tick, he crits again at 1:55 for 53,641, which should add another 53,641 * 0.53572 = 28,736.5565 damage, giving us a total of 28,736.5565 + 28,884.4152 = 57,620.9717.

Less than a second after, we get our first ignite tick of 19,207. This suggests that the duration has not been refreshed, as we would expect the first tick at 1:57 in that case. But looking at the tick amount, it has the value of a combined ignite of both crits split over 3 ticks: 57,620.9717 / 3 = 19,206.9906. It's the only way to arrive at this amount; taking only the first crit split over 2 would be too little, and taking both crits spread over 2 (the way it currently would work in beta) would be too much.

A bit later in the video starting at 2:02, we see 3 consecutive ignite ticks for 18,728 without any refreshing of the duration as well, confirming that a refreshed ignite should last 3 ticks.

I'll include the math for the entire crit line below, but I think this first part should prove my point.

1:53 - 53,917 crit, 53,917 * 0.53572 = 28,884.4152. 

Ignite total: 28,884.4152, ticks remaining: 2, expected tick amount: 14,442.2076.

1:55 - 53,641 crit, 53,641 * 0.53572 = 28,736.5565, 28,736.5565 + 28,736.5565 = 57,620.9717. 

Ignite total: 57,620.9717, ticks remaining: 3, expected tick amount: 19,206.9906.

_1:55 ignite tick, 19,207, 57,620.9717 - 19,207 = 38,413.9717._

Ignite total: 38,413.9717, ticks remaining: 2, expected tick amount: 19,206.9859.

1:57 - 73,937 crit, 73,937 * 0.53572 = 39,609.5296, 39,609.5296 + 38,413.9717 = 78,023.5013. 

Ignite total: 78,023.5013, ticks remaining: 3, expected tick amount: 26,007.8338.

_1:58 ignite tick, 26,008, 78,023.5013 - 26,008 = 52,015.5013._

Ignite total: 52,015.5013, ticks remaining: 2, expected tick amount: 26,007.7507.

_2:00 ignite tick, 26,008, 52,015.5013 - 26,008 = 26,007.5013._

Ignite total: 26,007.5013, ticks remaining: 1, expected tick amount: 26,007.5013.

2:00 - 56,333 crit, 56,333 * 0.53572 = 30,178.7148, 26,007.5013 + 30,178.7148 = 56,186.2161. 

Ignite total: 56,186.2161, ticks remaining: 3, expected tick amount: 18,728.7387.

_2:01 ignite tick, 18,728, 56,186.2161 - 18,728 = 37,458.2161._

Ignite total: 37,458.2161, ticks remaining: 2, expected tick amount: 18,729.108.

_2:03 ignite tick, 18,728, 37,458.2161 - 18,728 = 18,730.2161._

Ignite total: 18,730.2161, ticks remaining: 1, expected tick amount: 18,730.2161.

_2:05 ignite tick, 18,729, Ignite expires._

**Comment by kenthklui** [comment]
Appears to be fixed now.
