### ISSUE TITLE
[BUG] Repentance can be used on a druid with Tree Form Up (potentially other druid forms as well)

### ISSUE THREAD

**Issue by Azmoddan** [JamminL/cata-classic-bugs#1035]
#### 1.1. Description
Currently it is possible to use retribution paladin spell 'Repentance' to crowd control druid in Tree of Life form.
  #### 1.2. How to Reproduce
           1. Enter tree form
           2. Ask a ret paladin to use repentance on you
  #### 1.3  Source Material
  

https://github.com/JamminL/cata-classic-bugs/assets/42694757/455c8b06-1888-450e-81a0-4294bbe0af1c

#### 2.1. Description
From Repentance's tooltip:
https://www.wowhead.com/cata/spell=20066/repentance

> Puts the enemy target in a state of meditation, incapacitating them for up to 1 min.  Any damage from sources other than Censure will awaken the target.  Usable against **Demons, Dragonkin, Giants, Humanoids and Undead**.

The way Tree of Life is supposed to work is that it transforms you into **Elemental** that is immune to polymorph effects.
https://www.wowhead.com/cata/npc=51246/tree-of-life-test-dnd

There is a possibility that the Bear/Cat Form also have this issue (they transform you into **Beast** instead, which should also not be targetable by Repentance).
  #### 2.2 Source Material
Taking into consideration the fact that original Cataclysm's changes aren't well documented I will use a mention from WoWWiki instead:

https://wowwiki-archive.fandom.com/wiki/Tree_of_Life_Form

> Tree of Life Form (or often nicknamed Tree Form, Healing Form or Treant Form) is a druid spell in the [Restoration](https://wowwiki-archive.fandom.com/wiki/Restoration) tree. It requires 30 points (was 41 points) and is a primary talent for resto specs. While shapeshifted, the druid gains immunity to polymorph effects but is considered an **elemental.**

+ add the fact that it is how the Tree Form worked in Wrath of the Lich King as well, even though the elemental part was not included in the tooltip.

**Comment by JamminL** [comment]
Multiple people have said this was not the case and that this is NAB, we'll need some more evidence

**Comment by SimonBpvp** [comment]
I dont think tree form is meant to transform you into an elemental in cata, reason: you couldn't banish a druid in tree form.
