### ISSUE TITLE
Intervene Absorbing Bad Manner Spell

### ISSUE THREAD

**Issue by Kenniflopper** [JamminL/cata-classic-bugs#1036]
#### 1.1. Description
Currently Bad manner spell is being absorbed by intervene which is supposed to only absorb Physical abilities.
  #### 1.2. How to Reproduce
      Have 2 enemys be infront of you 1 warrior and 1 random class, have the warrior use intervene spell on his party member and then you will use bad manner on the affected intervene target.
  #### 1.3  Source Material
https://youtu.be/AYEBdrP2V1I
#### 2.1. Description
Bad manner is a spell and it should not be affected by intervene, it works through hand of protection and does NOT work into cloak of shadows and anti-magic shell

**Comment by Snipin** [comment]
https://youtube.com/clip/UgkxvD4e4sahgEWPAgG7UbmoOWvECN6Ye4Ib?si=QvliN5xpQn59Qr1W

Warrior intervenes Paladin, does not absorb the Bad Manner

**Comment by Azmoddan** [comment]
https://www.wowhead.com/cata/spell=90337/bad-manner
**School: Nature**

Most likely should ignore Intervene/Blessing of Protection and be immuned by Cloak and AMS like mentioned above.

**Comment by skinnay-dev** [comment]
School of magic is not the same as spell vs. attack categorization. You can intervene a Chimera shot for example that does nature damage because it's a ranged attack. Same with arcane shot and various other "magic" shots, Hammer of Wrath, etc. and they go through BoP because they are not physical. School is irrelevant to whether something should be able to be intervened. However, the Cloak of Shadows and Anti-Magic Shell interactions are relevant.

**Comment by skinnay-dev** [comment]
> https://youtube.com/clip/UgkxvD4e4sahgEWPAgG7UbmoOWvECN6Ye4Ib?si=QvliN5xpQn59Qr1W
> 
> Warrior intervenes Paladin, does not absorb the Bad Manner

This isn't good proof because of the range requirement on Intervene. It looks like the Warrior wasn't quite in range yet.

**Comment by Kenniflopper** [comment]
> > https://youtube.com/clip/UgkxvD4e4sahgEWPAgG7UbmoOWvECN6Ye4Ib?si=QvliN5xpQn59Qr1W
> > Warrior intervenes Paladin, does not absorb the Bad Manner
> 
> This isn't good proof because of the range requirement on Intervene. It looks like the Warrior wasn't quite in range yet.

Intervene gives the buff instantly to the target when you press it, it doesnt only apply once the warrior reaches the target. So the clip clearly proves that you should be able to bad manner through intervene. :-)

**Comment by Kenniflopper** [comment]
https://youtube.com/clip/UgkxT5lUxADaEvzE-Tp4YXQPWDPbUbGbTtd4?si=-hQILu7JW0jxezE6 - Intervene buff being applied before Warrior is even at the target location.

**Comment by skinnay-dev** [comment]
There is still a 10 yard range requirement when you have the buff.

**Comment by Kenniflopper** [comment]
> https://youtu.be/AYEBdrP2V1I

https://youtu.be/AYEBdrP2V1I

**Comment by Kenniflopper** [comment]
> There is still a 10 yard range requirement when you have the buff.

https://youtu.be/AYEBdrP2V1I

**Comment by skinnay-dev** [comment]
See the warrior is in range in that clip

**Comment by skinnay-dev** [comment]
Did some testing on pre-patch and Bad Manner is behaving with a strange mixed categorization that is most similar to shooting a wand:

Bad Manner and Wand can be Intervened as if they are ranged attacks
Bad Manner and Wand are not affected by 25% miss on Evasion for ranged attacks
Bad Manner and Wand do not get Spell Reflected
Bad Manner and Wand will Miss on Cloak of Shadows (or Immune if Cloak is used during the cast time)
Bad Manner and Wand both have a 0.5 second cast
Bad Manner can be kicked/blanket silenced and displays a castbar, unlike wand.

Still unsure if this is consistent with original Cata but maybe this will help with finding any discrepancies in old videos.

**Comment by Snipin** [comment]
> Did some testing on pre-patch and Bad Manner is behaving with a strange mixed categorization that is most similar to shooting a wand:
> 
> Bad Manner and Wand can be Intervened as if they are ranged attacks Bad Manner and Wand are not affected by 25% miss on Evasion for ranged attacks Bad Manner and Wand do not get Spell Reflected Bad Manner and Wand will Miss on Cloak of Shadows (or Immune if Cloak is used during the cast time) Bad Manner and Wand both have a 0.5 second cast Bad Manner can be kicked/blanket silenced and displays a castbar, unlike wand.
> 
> Still unsure if this is consistent with original Cata but maybe this will help with finding any discrepancies in old videos.

Bad Manner, to my knowledge, is accurate with all of those things except that it can be intervened.

As you can see in the original clip, it is not even removing the intervene buff.

**Comment by AidanZMoon** [comment]
This behavior is accurate to 4.3.4 Cataclysm

Intervene will redirect Bad Manner to the Warrior and it will NOT consume Intervene.

**Comment by JamminL** [comment]
> This behavior is accurate to 4.3.4 Cataclysm
> 
> Intervene will redirect Bad Manner to the Warrior and it will NOT consume Intervene.

Works like SAP I guess. Spaguetti code >;
