### ISSUE TITLE
[BUG] Blood Parasite spawning multiple worms

### ISSUE THREAD

**Issue by CharWS** [JamminL/cata-classic-bugs#1045]
#### 1.1. Description
The talent Blood Parasite is spawning 2-4 Bloodworms on proc

#### 2.1. Description
Blood Parasite should only spawn a single worm when it procs
  #### 2.2 Source Material
[{Video, Posts, etc..}](https://youtu.be/zi4j8fXAwCA?t=62)

**Comment by lordblackadder** [comment]
Fixed with build 54481
