### ISSUE TITLE
[BUG] Repentance not breaking from Hand of Sacrifice

### ISSUE THREAD

**Issue by gekkuxz** [JamminL/cata-classic-bugs#1048]
#### 1.1. Description
Repentance does not break from damage transferred through Hand of Sacrifice.
  #### 1.2. How to Reproduce
          1. Cast Hand of Sacrifice on an allied player
          2. Have an enemy paladin cast Repentance on you
          3. Have that enemy paladin attack your ally
          4. Notice Repentance is not breaking from the damage taken
  #### 1.3  Source Material
https://streamable.com/hjulqs
#### 2.1. Description
Repentance should break from Hand of Sacrifice damage as mentioned in the tooltip :   Any damage from sources other than Censure will awaken the target. 
  #### 2.2 Source Material
{Video, Posts, etc..}

**Comment by JamminL** [comment]
Comment test

**Comment by JamminL** [comment]
Centralized it here: https://github.com/JamminL/cata-classic-bugs/issues/1271
