### ISSUE TITLE
[BUG] hunter pet appears to be level 80

### ISSUE THREAD

**Issue by SimonBpvp** [JamminL/cata-classic-bugs#1050]
#### 1.1. Description 
hunter pets appear to be level 80 when targetted

  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. get an hunter to summon a pet
  #### 1.3  Source Material
{Video, Posts, etc..} 
![image](https://github.com/JamminL/cata-classic-bugs/assets/94299191/3845c932-f7dc-4b50-b3ff-6dfc191db88f)

#### 2.1. Description 
the pet should be level 85, levelling pets wasn't a thing in cata
  #### 2.2 Source Material
{Video, Posts, etc..}

**Comment by CharWS** [comment]
You mention it "appears to be level 80" is it just a visual bug then, or is it impacting interactions with the pet as well?

**Comment by SimonBpvp** [comment]
I think all hunter pets are really level 80 not just a visual bug

**Comment by JamminL** [comment]
Steps:

- Go to STV Monkey island (Jaguero Isle) as level 85
- Tame one of the gorillas
- Notice the gorilla levels up to 80, not 85
- Check stats and notice it only has 80 resist to make sure it's not visual
