### ISSUE TITLE
[BUG]Spells go through Deterrence if Hunter is casting a spell

### ISSUE THREAD

**Issue by Snipin** [JamminL/cata-classic-bugs#1055]
### 1. Current Behavior
If a Hunter uses Deterrence and begins to cast a spell (Dismiss pet, Scare beast) magical spells will begin through through deterrence.
 
 #### 1.2. How to Reproduce
           1. Hunter casts Deterrence
           2. Hunter casts Dismiss pet
           3. Cast any spell into Deterrence and it will land
           
In the source material from Cataclysm classic beta, Gargoyle Strikes are landing through Deterrence while casting Dismiss Pet. Once finished casting Dismiss Pet, the spells are deflected.
 
 #### 1.3  Source Material
(https://www.youtube.com/watch?v=4p30ZTNpZfA)   

### 2. Expected Behavior
While Hunter's Deterrence is active, no spells should pass through it, regardless whether they are casting a spell or not. 

In the source material from Retail Cataclysm, Tosan uses Deterrence and begins casting Dismiss pet. Gargoyle strikes are deflected the entire duration of his Deterrence- Nothing passes through the Deterrence for it's entire duration.

  #### 2.2 Source Material
(https://youtube.com/clip/UgkxAeHyh4qOo_97L7GnSha1ms_YFV0hmFv9?si=Snhjy26AXHQhZYSa)

**Comment by JamminL** [comment]
https://www.youtube.com/watch?v=3AYdGGMBrcc&t=60s NAB

Turned into suggestion -> https://github.com/JamminL/cata-classic-bugs/issues/1057

**Comment by JamminL** [comment]
> > https://www.youtube.com/watch?v=3AYdGGMBrcc&t=60s NAB
> > Turned into suggestion -> #1057
> 
> Can you explain this clip? What spells are we looking at here, Is it mirror image frostbolts?

https://youtu.be/3AYdGGMBrcc?t=60 - Cannot Deflect during CC (similar to other avoidances parry/dodge/kidney)
https://youtu.be/dZTtb9_rOww?t=61 - Waterbolt Through Deter
https://youtu.be/q0YckSFSZhI?t=16615- Corruption Through Deter
https://youtu.be/Ttqk4Qy96GA?t=202 - Piercing Howl Through Deter
https://youtu.be/q0YckSFSZhI?t=17067 - Deathcoil Through deter (check pushback and unholy blight)
https://youtu.be/q0YckSFSZhI?t=17108 - Chains of Ice Through deter
