### ISSUE TITLE
[BUG] Mage spread ignite does not clear correctly

### ISSUE THREAD

**Issue by Remidemmi** [JamminL/cata-classic-bugs#1058]
#### 1.1. Description
When spreading a full duration ignite with an impact procc, the spread ignite only ticks once instead of twice. If you apply a fresh ignite on the target after the spread ignite has expired, the missing tick will be added to the total of the new ignite.
  #### 1.2. How to Reproduce
           1. Have targets A and B that you can spread ignite between
           2. Get Ignite on A and instantly spread it to B before the first tick
           3. Let Ignite expire
           4. Trigger new Ignite on B
  #### 1.3  Source Material
https://www.youtube.com/watch?v=MW-NG-4Qvyw

![image](https://github.com/JamminL/cata-classic-bugs/assets/609473/352531b3-7cf1-4453-b385-5d0abce2e0b2)
In the combat log, we see the last fireball crit before the fireblast spread happens at 14:40:46.
The first spread ignite tick happen 2 seconds later at :48 for 11350.
The second should happen at :50, but doesnt

![image](https://github.com/JamminL/cata-classic-bugs/assets/609473/4cd0642f-2d56-4227-92fe-c738e453a550)
After Ignite expired, we see a scorch crit for 9109, which gives us a ignite total of 3643.6 and tick of 1821.8, but we get 7496, which means a toal of 14992, which is the missing 11350 from earlier + the 3643 from the scorch crit

#### 2.1. Description
Tick the correct amount of times and clear stored ignite damage when the aura is removed
  #### 2.2 Source Material
{Video, Posts, etc..}

**Comment by JamminL** [comment]
This is related with the wotlk ignite hotfix, most likely
