### ISSUE TITLE
[BUG] Disengage Reaction / Wrong Direction

### ISSUE THREAD

**Issue by Kenniflopper** [JamminL/cata-classic-bugs#1065]
#### 1.1. Description
Currently if u disengage you sometimes disengage sideways or not the right way.
  #### 1.2. How to Reproduce
   duel an enemy, get combat, move ur camera around in a rapid succesion then press disengage and watch now u dont actually go in the proper direction
  #### 1.3  Source Material
https://www.youtube.com/watch?v=MQpVl_PGK6o
#### 2.1. Description
You should always disengage backwards.

**Comment by Lillyton** [comment]
Nothing buggy there. Look at the exact moment you used it, it correctly launched you backwards.

**Comment by ManneN1** [comment]
I don't see the issue either. Looking at this video it looks like you're being disengaged exactly to where I would expect you to be disengaged.
