### ISSUE TITLE
[BUG] Pyromaniac does not proc from Flamestrike

### ISSUE THREAD

**Issue by TheHate123** [JamminL/cata-classic-bugs#1069]
#### 1.1. Description
You do not get the Pyromaniac (talent) buff when 3 or more mobs are standing in your Flamestrike
  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Find 3 or more adds
           2. Flamestrike
           3. Be sad when they are all standing in it and you have no Pyromaniac
  #### 1.3  Source Material
https://www.youtube.com/watch?v=2A8rSXV9mU4
#### 2.1. Description
The talent Pyromaniac should proc from Flamestrike
  #### 2.2 Source Material
https://youtu.be/JvPMa0KERT0?si=g6X2Um6Z5oS8vJMM&t=98
https://youtu.be/qzDo3rPp4MI?si=erCTfcwC8FczHf4q&t=234

**Comment by TamerLee** [comment]
Would like others to add to this discussion, but I believe the video is having flamestrike trigger ignites, which in turn triggers pyromaniac. Flamestrike does not benefit from mastery (flashburn), and is unlikely to be considered a DoT for pyromaniac purposes as well. I am not positive, though.

**Comment by SimonBpvp** [comment]
I would be surprised if flamestrike counts as a dot like that because I don't think of floor effects working that way. Not 100% sure though.
