### ISSUE TITLE
[BUG] Hunter serpent spread and black arrow dots not critting.

### ISSUE THREAD

**Issue by bluemike61** [JamminL/cata-classic-bugs#1074]
#### 1.1. Description
          When casting multishot with the serpent spread talent the serpent spread DOT is not able to crit. The same applies to casting black arrow which is not critting.
  #### 1.2. How to Reproduce
           1. Use multi shot with serpent spread
           2. Use black arrow
           3. Neither of the dots will ever crit
#### 2.1. Description
          The serpent spread DOT should be able to crit the same way as casting serpent sting by itself can. Black Arrow should be able to crit as well which is supported by the talent Toxicology which increases Black Arrow crit damage.

**Comment by skinnay-dev** [comment]
These DoTs are critting now in pre-patch.

![2024-04-30-23:41:33-ss](https://github.com/JamminL/cata-classic-bugs/assets/54093054/b64e448c-5329-4326-b544-5339c96953dd)
![2024-04-30-23:41:16-ss](https://github.com/JamminL/cata-classic-bugs/assets/54093054/e744d28e-c103-445c-b8b8-f0ce0da7fbb4)
