### ISSUE TITLE
[BUG] Resilience is barely working

### ISSUE THREAD

**Issue by JamminL** [JamminL/cata-classic-bugs#1075]
#### 1.1. Description
Resilience currently is doing roughly 18-20% of its intended pre-diminished amount.

  #### 1.3  Source Material
![image](https://github.com/JamminL/cata-classic-bugs/assets/107503518/26135a30-31cb-404f-a167-cc8939195074)

Thanks to @raethkcj for the help with this!

**Comment by raethkcj** [comment]
As of build 54558 Resilience is both using the correct conversion rate, and respecting Diminishing Returns, both in the character sheet and in combat:
![image](https://github.com/JamminL/cata-classic-bugs/assets/7716908/96974281-0982-4a70-b053-f4792dd95f86)
![image](https://github.com/JamminL/cata-classic-bugs/assets/7716908/b8a3d8d9-251f-4a6a-b960-63c3dd9e7d98)
