### ISSUE TITLE
[BUG] Fear/Hex/Roots using WOTLK threshold

### ISSUE THREAD

**Issue by JamminL** [JamminL/cata-classic-bugs#1078]
#### 1.1. Description
Right now CC that is supposed to break on damage e.g fear is breaking around 4k damage, which is a dot tick in cata. Basically any cc with a threshold is breaking almost instantly.
  #### 1.2. How to Reproduce
           1. Cast fear on a lvl 85 enemy player/mob
           2. Notice the fear disappears as soon as he takes ~5k damage
  #### 1.3  Source Material

https://github.com/JamminL/cata-classic-bugs/assets/107503518/27746286-db54-413e-ae21-01af6698e8d7

**Comment by Scrynax** [comment]
Please fix it, its unplayble in the current state. Fear breaks on 1 corruption / agony / shadowflame dot...

**Comment by Kenniflopper** [comment]
So fear has been "fixed" but now the dmg threshold is too high, sometimes taking up to 30-40k damage from dots before breaking.
