### ISSUE TITLE
[BUG] Tree stumps and all environmental objects in WSG are NOT providing LOS.

### ISSUE THREAD

**Issue by oldspices** [JamminL/cata-classic-bugs#1082]
#### 1.1. Description
giant tree stumps and small pillars around GY are not providing LOS , you cannot run through them but all spells go through them
  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. stand behind giant stump and either get casted on or cast against someone.
         
  #### 1.3  Source Material
{Video, Posts, etc..} 
#### 2.1. it should provide line of sight.
{Describe how that mechanic/spell/npc should be working, in detail}
  #### 2.its quite simple, should be providing LOS.
{Video, Posts, etc..}

**Comment by oldspices** [comment]
how is this not a bug

**Comment by CharWS** [comment]
do you have any examples from cataclysm where this wasn't the case?
