### ISSUE TITLE
[BUG]Spells disappearing, not showing up in spellbook

### ISSUE THREAD

**Issue by Snipin** [JamminL/cata-classic-bugs#1084]
### 1. Current Behavior
Incorrect spells showing up in spellbook.
Spells disappearing completely from spellbook
  #### 1.2. How to Reproduce
Relog or switch specs and certain spells might disappear.
Notice how call pet 3 and 4 are in the Marksman spellbook. 
I am also missing Steady Shot and Aimed Shot at the moment of this picture
  #### 1.3  Source Material
Prepatch
https://imgur.com/8eNuRWy 
https://imgur.com/eogcpo8

Beta
https://imgur.com/2dGaEyK
https://imgur.com/o5rgnig

**Comment by JamminL** [comment]
Is fixed for the cases I checked, if you still have some cases where this is still happening let me know and I'll reopen
