### ISSUE TITLE
[BUG] Enhancement Shaman Feral Spirit Wolves not gaining Unleashed Rage buff 

### ISSUE THREAD

**Issue by Somatics23** [JamminL/cata-classic-bugs#1085]
Currently, when you summon Feral Spirit wolves, they do not gain the Unleashed Rage Enhancement Shaman passive talent. They do, however, benefit and gain Windfury Totem. 
  #### 1.2. How to Reproduce
          1. As an Enhancement Shaman, talent into both Unleashed Rage and Feral Spirit
          2. Cast Feral Spirit
          3. Notice that the Unleashed Rage buff is not active on either Spirit Wolf 
  
  
The expected behavior of the interaction between these two talents is for the Spirit Wolves to benefit from Unleashed Rage’s 20% melee attack power buff, just as they did in wotlk classic and do on every cataclysm private server. Thank you.

**Comment by raethkcj** [comment]
Please fill out the entire template including source material.
