### ISSUE TITLE
[BUG] Shadow Priest talent Shadowy Apparition randomly stops working

### ISSUE THREAD

**Issue by TheHate123** [JamminL/cata-classic-bugs#1090]
#### 1.1. Description
The Shadow Priest talent Shadowy Apparition seems to bug out often and stops working completely.
The fix seems to be a simple relog, but the cause is unknown. A theory is that if the Apparitions don't make it to the target (because it died), maybe the game still keeps count of it existing (you can only have 4 apparitions at once), and after this happens 4 times, you get locked. This is however, not proven and just an idea of what the cause could be.
  #### 1.2. How to Reproduce
           1. Teleport to Uldum
           2. HS back to Stormwind
           3. Dot all the dummies
           4. Notice apparitions never proc
  #### 1.3  Source Material
https://www.youtube.com/watch?v=WsuWAdilRzs
https://classic.warcraftlogs.com/reports/JxymfdgcrvV9MGtQ#boss=-2&difficulty=0&type=damage-done
On the log, for example you can see Magmaw Heroic wipes #2 and #3, they work perfectly fine.
But then wipes #4 and #5 they stopped working. I relogged after wipe #5, and it fixed it. Wipe #6 they work fine again.
#### 2.1. Description
Every Shadow Word: Pain tick is supposed to have a 12% chance to spawn an Apparition, up to 60% if you were moving during the tick.
  #### 2.2 Source Material
https://www.wowhead.com/cata/spell=78204/shadowy-apparition

**Comment by TheHate123** [comment]
This seems fixed again on the last update, can be closed.

**Comment by JamminL** [comment]
Reopened, need to find a consistent way to reproduce this but it's still happening at times

**Comment by JamminL** [comment]
If you teleport, your apparitions will no longer proc. Updated your post with repro steps
