### ISSUE TITLE
[BUG] Some characters still have digsites in inaccessible Cataclysm zones and are stuck because of it

### ISSUE THREAD

**Issue by TheHate123** [JamminL/cata-classic-bugs#1091]
#### 1.1. Description
Characters who had Twilight Highlands or Uldum digsites (example) as their only solves on a continent are effectively stuck on that character. This seems to have been changed and new characters cannot get stuck like this but the old ones still are.
  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. ?
  #### 1.3  Source Material
![image](https://github.com/JamminL/cata-classic-bugs/assets/118665346/04b47a63-91b1-479e-a58f-faccdd0acb2e)
![image1](https://github.com/JamminL/cata-classic-bugs/assets/118665346/668cb94e-7752-4686-bd0b-35efd1f3d8aa)
#### 2.1. Description
If possible, maybe something could be done to unstuck them so they don't have to relevel the profession on another character.
  #### 2.2 Source Material
{Video, Posts, etc..}

**Comment by CharWS** [comment]
should be fixed as of: https://us.forums.blizzard.com/en/wow/t/cataclysm-classic-hotfixes-may-1/1843458

**Comment by CharWS** [comment]
Looks as though this is functioning going forward for new digsite spawns but has not retroactively fixed those who already had them stuck in inaccessible areas so reopening for now.

**Comment by CharWS** [comment]
looks to be fully fixed now as of today
