### ISSUE TITLE
[BUG] Some Retribution Paladins still have their Crusader Strike misalign it's cooldown with Divine Storm

### ISSUE THREAD

**Issue by TheHate123** [JamminL/cata-classic-bugs#1092]
#### 1.1. Description
Some Retribution specced Paladins seem to have the hidden passive of the Protection spec where Crusader Strike has a reduced cooldown, despite not being specced into Protection.
  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Be one of the few paladins who still have this bug
  #### 1.3  Source Material
https://www.youtube.com/watch?v=FTVBmOxeDMY
#### 2.1. Description
It's supposed to have a base cooldown of 4.5 seconds, not 3.0 seconds. Obviously lower when you spec into the Sanctity of Battle Retribution talent.
  #### 2.2 Source Material
{Video, Posts, etc..}

**Comment by XsExcess** [comment]
To add to this, tried to track it down on beta/PTR with the help of the Paladin beta community too, but no real luck.

Doesn't seem to be related to a Prot OS, but seems to be linked to specific (accounts?) characters that just have it. 
It was active on the PTR for my character copy (as consistently as I could check), and persists into live, but wasn't a thing on the beta copy. But wasn't able to replicate it on any template characters no matter race/spec/template(body type) attempts. While others would get it on their templates.

**Comment by TheHate123** [comment]
Should be fixed now with the last update
