### ISSUE TITLE
[BUG] Frost Presence and Improved Frost Presence not increasing the runic power generation of abilities

### ISSUE THREAD

**Issue by CharWS** [JamminL/cata-classic-bugs#1093]
#### 1.1. Description
Currently Frost Presence and the talent Improved Frost Presence are only increasing the runic power generated through sources such as Chill of the Grave, but are not increasing the runic power generated through the expenditure of runes
  #### 1.2. How to Reproduce
           1. Cast an ability which costs 1 rune noting that it only generates 10 rp
           2. Enter frost presence and repeat step 1 noting that 10 rp is still generated when it should be 11
           3. talent into improved frost presence and change into a non-frost presence
           4. repeat step 1 noting that still only 10 rp is generated even through repeated use when 10.4 should be

#### 2.1. Description
Frost presence should cause all sources of runic power generated to be increased by 10%, and when talented and using a different presence should increase all sources of runic power generation by 4%

**Comment by CharWS** [comment]
https://www.wowhead.com/cata/spell=48266/frost-presence can see under Effect #3 that frost presence is only set to modify the spell effectiveness of butchery, scent of blood, chill of the grave, and might of the frozen wastes, but does not include any rune costing abilities
https://www.wowhead.com/cata/spell=50385/improved-frost-presence can see that improved frost presence is similarly acting on the same effect of frost presence at a reduced value and thus has the same issue

**Comment by lordblackadder** [comment]
Fixed with build 54558
Frost presence (+10%):
![image](https://github.com/JamminL/cata-classic-bugs/assets/12127284/ddeeb997-8436-4a5a-a265-2348928b70f7)
Improved frost presence but in unholy presence (+4%):
![image](https://github.com/JamminL/cata-classic-bugs/assets/12127284/3f4a61ab-dd6e-4e90-a766-401a67f0ad39)

It also correctly multiplied other modifiers like Chill of the Grave
