### ISSUE TITLE
[BUG] Nourish is consuming clearcasting

### ISSUE THREAD

**Issue by CharWS** [JamminL/cata-classic-bugs#1100]
#### 1.1. Description
Casting Nourish can consume a Clearcasting proc for druids

  #### 1.3  Source Material
https://classic.warcraftlogs.com/reports/TVNj3A9dDFy6XPaL#boss=-3&difficulty=0&pins=2%24Off%24%23244F4B%24auras%7Ccasts%24-1%240.0.0.Any%240.0.0.Any%24true%240.0.0.Any%24true%2416246%7C16870%7C50464&source=1&view=events
![nourish](https://github.com/JamminL/cata-classic-bugs/assets/104176019/2bea941e-2923-478c-aab3-22b93faf2f3f)

#### 2.1. Description
Nourish should not consume Clearcasting procs
  #### 2.2 Source Material
https://warcraft.wiki.gg/wiki/Patch_4.0.3a
"Nourish no longer consumes  Omen of Clarity"

**Comment by Loregon** [comment]
I would also add a video. An extremely important problem for the restor druids...
https://youtu.be/R2m9AKUCzIw?si=B8yR9oOOpJj1LYxg&t=91
