### ISSUE TITLE
[BUG] Armor Jewelry and Weapons are contributing 700% the tooltip indicated armor value

### ISSUE THREAD

**Issue by kenthklui** [JamminL/cata-classic-bugs#1104]
#### 1.1. Description
Jewelry items and weapons that have armor or bonus armor on them, are currently providing 7x the armor that is specified within their tooltip. This armor contribution is unrelated from the currently buggy character sheet displayed armor value, and instead affects actual melee damage reduction as recorded from combat. For example, the 245 itemlevel version of The Arbiter's Muse (https://www.wowhead.com/cata/item=47116/the-arbiters-muse) has a tooltip value of 156 bonus armor, but wearing it has the effect of adding 7 * 156 = 1092 armor instead.

This bug has been verified as applying to the following item slots:
- Neck
- Rings (both slots)
- Trinkets (both slots)
- Weapon

This bug applies only to items which have static armor amounts. It does not seem to affect armor procs (ie. ICC rings) or extra armor on non-jewelry armor slots (ie. plate armor slot and cloak).

  #### 1.2. How to Reproduce
Technically, reproducing this bug is very simple. All you need to is to wear an item and get attacked by a mob, and then repeat the process with the item unequipped, to compare the amount of damage taken. However, in practice it is a bit more difficult to verify the bug is present.

**Please note that as of the time of writing, the character sheet is currently very buggy. Therefore, armor values displayed on the character sheet are being completely disregarded within this testing.** Here are the steps I took to verify the bug on a druid and a warrior.

1. Use a bear druid/protection warrior/any tank class that prevents critical strikes, as they will complicate mitigation numbers later.
2. Equip set of gear with no armor procs, no extra armor on any pieces, except the slot you are trying to test (neck/ring/trinket).
3. Enable advanced combat logging and start a combat log.
4. Enter a normal level 80 dungeon with melee mobs at the start. This guarantees the same attacker level at all times. For this purpose, I chose normal Forge of Souls.
5. Pull the mobs and turn your back at them. This will let them hit you more often, and also prevents blocking on paladins/warriors which would complicate calculations later.
6. Zone out at low health.
7. Now, equip the neckpiece/ring/trinket with extra armor, and repeat steps 4 through 6. Here are some item options for each slot that are easy to acquire:
   - Neck: [Arbiter's Muse](https://www.wowhead.com/cata/item=47116/the-arbiters-muse)
   - Ring: [Clutch of Fortification](https://www.wowhead.com/cata/item=47731/clutch-of-fortification)
   - Trinket: [Glyph of Indomitability](https://www.wowhead.com/cata/item=47735/glyph-of-indomitability)
8. You should now have logs of the taken melee damage, which should include both the unmitigated value and post-migitation value. For convenience, upload the acquired combat logs to WarcraftLogs for easier analysis.

### 2. Expected Behavior
The player should see the increase in damage reduction percentage, corresponding to the tooltip armor value displayed on the item.
  #### 2.1. Calculating expected damage reduction
The expected melee damage reduction consists of 2 components: the reduction due to armor, and effects due to class/talents. The reduction due to armor is calculated as follow:
`armor_DR = armor_value / (armor_value - 22167.5 + 467.5 * attacker_level)`

For a given level 80 attacker, this simplifies to the following:
`armor_DR = armor_value / (armor_value + 15232.5)`

In terms of class/talent effects, warriors have 10% damage reduction due to defensive stance, while bears have 18% damage reduction due to the Natural Reaction talent. The final damage reduction can then be calculated as follow:
`expected_DR = 1 - (1 - armor_DR) * (1 - class_DR)`

### 3. Observed Behavior
The player sees jewelry contributing 700% the indicated armor value. Here are some logs demonstrating the "before/after" effects of equipping armor jewelry.

#### 3.1 Warrior trinket
Warrior before equipping trinket has 26959 armor, expected DR = 67.51%. Testing confirms as 67.50%: https://classic.warcraftlogs.com/reports/QydWLqBrkwXnYHGp#fight=5&type=damage-taken&ability=1

Warrior after equipping [Petrified Twilight Scale](https://www.wowhead.com/cata/item=54591/petrified-twilight-scale) **should have 26959 + 736 = 27695 armor, expected DR = 68.06%. Testing returns 71.04% instead**: https://classic.warcraftlogs.com/reports/QydWLqBrkwXnYHGp#fight=4&type=damage-taken&ability=1

The observed DR corresponds to 32111 armor, which has an expected DR = 71.04%. This means the trinket is providing 5152 armor, which is 700% the correct value.

#### 3.2 Druid neck
Druid before equipping neck has 40604 armor, expected DR = 77.63%. Testing confirms as 77.62%: https://classic.warcraftlogs.com/reports/3WyThFDBtCJ4mGz9#fight=3&type=damage-taken&ability=1

Druid after equipping [Arbiter's Muse](https://www.wowhead.com/cata/item=47116/the-arbiters-muse) **should have 40604 + 156 = 40760 armor, expected DR = 77.69%. Testing returns 78.06% instead**: https://classic.warcraftlogs.com/reports/3WyThFDBtCJ4mGz9#fight=4&type=damage-taken&ability=1

The observed DR corresponds to 41696 armor, which has an expected DR = 78.06%. This means the neck is providing 1092 armor, which is 700% the correct value.

#### 3.3 Druid ring
Druid before equipping ring has 40802 armor, expected DR = 77.71%. Testing confirms as 77.70%: https://classic.warcraftlogs.com/reports/zFjAynGk48NMLt6r#fight=1&type=damage-taken&ability=1

Druid after equipping [Clutch of Fortification](https://www.wowhead.com/cata/item=47731/clutch-of-fortification) **should have 40802 + 160 = 40962 armor, expected DR = 77.77%. Testing returns 78.14% instead**: https://classic.warcraftlogs.com/reports/zFjAynGk48NMLt6r#fight=2&type=damage-taken&ability=1

The observed DR corresponds to 41922 armor, which has an expected DR = 78.15%. This means the trinket is providing 1120 armor, which is 700% the correct value.

#### 3.4 Druid trinket
Druid before equipping trinket has 37931 armor, expected DR = 76.51%. Testing confirms as 76.50%: https://classic.warcraftlogs.com/reports/TnzKPXYf8kqLbyGg#fight=2&type=damage-taken&ability=1

Druid after equipping [Unidentifiable Organ](https://www.wowhead.com/cata/item=50344/unidentifiable-organ) **should have 37931 + 611 = 38542 armor, expected DR = 76.77%. Testing returns 78.25% instead**: https://classic.warcraftlogs.com/reports/TnzKPXYf8kqLbyGg#fight=3&type=damage-taken&ability=1

The observed DR corresponds well to 42208 armor, which has an expected DR = 78.25%. This means the trinket is providing 4277 armor, which is 700% the correct value.

#### 3.5 Warrior with weapon
See https://github.com/JamminL/cata-classic-bugs/issues/1104#issuecomment-2105259919

**Comment by Undertoe** [comment]
Unsure if this is related but I'm going to piggy back on this:  Armor trinkets are currently providing negative armor values on character sheets: 

Exact gearset used: 
https://sixtyupgrades.com/cata/set/xAvgV1RHJiJUtF5XjuZei2 

![image](https://github.com/JamminL/cata-classic-bugs/assets/3249986/10c10de5-e4ef-480b-8246-d4047bc86986)
Swapping to [Petrified Twilight Scale](https://www.wowhead.com/wotlk/item=54571/petrified-twilight-scale) yields this: 
![image](https://github.com/JamminL/cata-classic-bugs/assets/3249986/a412842f-d9a1-46b6-8d26-56f162b5233f)


I haven't tested anything about the actual DR of this but the raw gear sheet is wrong at any rate.

**Comment by Undertoe** [comment]
Swapping in [Defender's Code](https://www.wowhead.com/wotlk/item=40257/defenders-code) gives a new armor value: 

![image](https://github.com/JamminL/cata-classic-bugs/assets/3249986/0b8cc150-dde3-4384-8c13-e3b83ccbb5e2)


Defender's + Sindra gives even more armor? 
![image](https://github.com/JamminL/cata-classic-bugs/assets/3249986/769303e7-6f0b-4cb6-aa7f-277dd0971c08)

**Comment by kenthklui** [comment]
> Unsure if this is related but I'm going to piggy back on this: Armor trinkets are currently providing negative armor values on character sheets:
The issue is not as simple as "armor trinket is providing negative armor values". You can test it as follow:
1. Unequip an armor trinket, leaving the slot blank.
2. Log out and back in. You will notice that your character sheet armor now reflects the "correct" armor value, taking into account the current 7x multiplier on armor contributions.
3. Now equip the armor trinket. You should see your character sheet armor increase by the value indicated on the trinket's armor tooltip.
4. Log out and back in again. You will notice your character has gained armor compared to the value in step 3. The difference appears to be 6x the trinket's tooltip armor.

This indicates the character sheet issue is possibly related, as it seems like swapping items is resulting in addition and/or subtraction of tooltip armor values, instead of the current 7x actual value. Generally, these issues seemed to fix themselves after logging out and back in, or shifting out of and back into bear form.

That said, I found the character sheet issue to be entirely cosmetic. It doesn't affect the melee damage mitigation in combat. Therefore, I would suggest making a separate issue to track it as a character sheet/UI issue, even if the speculated root cause is related or maybe even identical.

**Comment by kenthklui** [comment]
Unfortunately it appears that the bug is not limited to jewelry, but also affects weapons. I found an old [Crusader's Glory](https://www.wowhead.com/cata/item=47967/crusaders-glory) in the bank and decided to give it a run.

No weapon, 44527 armor, expected DR ~= 77.06%. Confirmed by log as 77.06%: https://classic.warcraftlogs.com/reports/3vq1FHQAYcZTnfk9#fight=4&type=damage-taken&ability=1
With weapon, expected 44527 + 149 = 44676 armor, expected DR ~= 77.12%. Actual DR from log is 77.45%: https://classic.warcraftlogs.com/reports/3vq1FHQAYcZTnfk9#fight=3&type=damage-taken&ability=1
77.45% matched 44527 + 149 * 7 = 45570 armor, expected DR ~= 77.45%.

I will updated the title/description of this issue accordingly.

**Comment by kenthklui** [comment]
Bug appears to be fixed.

Tested with a warrior with Charred Twilight Scale.
