### ISSUE TITLE
[BUG] Demonic Pact only gives 2% spell damage

### ISSUE THREAD

**Issue by Tharre** [JamminL/cata-classic-bugs#1105]
#### 1.1. Description

Demonic pact has 2 separate effects:
1. > Increases your spell damage by 10%,

2. > your summoned demon grants the `Demonic Pact effect` to all nearby friendly party and raid members. The `Demonic Pact effect` increases spell power by 10%.

Currently, the first effect only gives 2% spell damage to the warlock (like Rank 1 did in Wrath), instead of 10%.

  #### 1.2. How to Reproduce
To make things simpler, we dismiss our pet so only the first effect can ever be active.

1. Without demonic pact talented, note the damage of a static effect, i.e. the nonperiodic damage part of immolate
2. Talent Demonic Pact
3. Look at the damage from Step 1 again, the difference to now should be 10% (minus rounding) and not 2%.

  #### 1.3  Source Material
#### 2.1. Description
Demonic Pact should be giving 10% spell damage, not 2%.
  #### 2.2 Source Material

**Comment by TheHate123** [comment]
Supposedly just a tooltip error. 2% seems intended.
