### ISSUE TITLE
[BUG] "Thirty Tabards" achievement tracking was reset

### ISSUE THREAD

**Issue by ForgeGit** [JamminL/cata-classic-bugs#1112]
#### 1.1. Description
If you already had the 25 Tabards achievement, and wear 5 new tabards, you won't get the 30 Tabards achievement.

Running the script 
`/run print("== Tabards you haven't worn:") for i=1,99999 do local s,_,d,_,_,_,_,l=GetAchievementCriteriaInfoByID(621,i) if s then if l then _,l=GetItemInfo(l) end if not d then print(l and "- "..l or "- "..s) end end end print("== end")
`
Suggests all tracking has been resetted

  #### 1.2. How to Reproduce
           1. Have the 25 Tabards Achievement in Wrath
           2. Wear 5 new tabards in Cataclysm
  #### 1.3  Source Material

Tabard achievement for 25 tabards from pre-TOC (Sept 2022)
![image](https://github.com/JamminL/cata-classic-bugs/assets/75605537/939dc2a8-1775-4b90-bdd0-771366b8ed7d)

Achievement currently in Cataclysm, after wearing 5 new tabards (TOC tabards)
![2024_05_03_WowClassic_dyhnKTh98m42_19_27_53](https://github.com/JamminL/cata-classic-bugs/assets/75605537/4dce01b9-6de9-4c94-bc93-792c61a5d7f9)

The 5 new tabards used
![image](https://github.com/JamminL/cata-classic-bugs/assets/75605537/27cdb1ff-3d09-49a9-b070-046e73674949)

Script above listing tabards that have been used before (In wrath) no longer listed as having been used
![image](https://github.com/JamminL/cata-classic-bugs/assets/75605537/c8783593-40c1-4ff4-89de-8d005f6bed3d)

**Comment by LordOfOtakus** [comment]
Likely related to the same issue as Got My Mind On My Money (100k) and 2500 Daily Quests completed, where they're all marked as account-wide but only counting newly acquired stats.

**Comment by lavjamanxd** [comment]
![image](https://github.com/JamminL/cata-classic-bugs/assets/10040415/9ef9fe0f-9262-486b-b048-b79716cb7d49)
I have more than 30 unique tabards in my bank, even if i equip them one by one again, the achievement still remains incomplete.
So even the tracking part might be bugged atm.

**Comment by raethkcj** [comment]
I just got this achievement out of the blue without acquiring or equipping any new tabards, so possibly hotfixed?

**Comment by LordOfOtakus** [comment]
Appears to be fixed, but the other 2 achievements I mentioned being broken aren't. Guess I'll make a seperate post for them soon.

**Comment by LordOfOtakus** [comment]
I forgot I made that post tbh.
