### ISSUE TITLE
[BUG][RAID] Theralion and Valiona (Heroic): Unstable Twilight

### ISSUE THREAD

**Issue by Northlol** [JamminL/cata-classic-bugs#1116]
#### 1.1. Description
Unstable Twilight, the orbs in the Twilight Realm on Theralion and Valiona (Heroic), are not doing damage to players
  #### 1.2. How to Reproduce
           1. Engage Theralion and Valiona
           2. Get sent to the twilight realm (it seems any mechanism of going down works)
           3. Run over a Twilight Orb
  #### 1.3  Source Material
![msedge_KxHhRJ8Uj3](https://github.com/JamminL/cata-classic-bugs/assets/43507247/3eb9d6e4-81e5-4f61-b2c3-7eb0c6359f9f) Full Damage Taken log for a kill, 0 damage taken from Unstable Twilight: this [video](https://youtu.be/uMeWGrp7Wkg) shows the orbs not exploding while underneath.
#### 2.1. Description
Running over an orb should cause the player to take damage.
  #### 2.2 Source Material
![Unstable Twilight](https://github.com/JamminL/cata-classic-bugs/assets/43507247/a4d8f18f-c7d4-4624-8c0d-0c7414978575)

**Comment by JamminL** [comment]
Comment Test

**Comment by Northlol** [comment]
This [video](https://youtu.be/uMeWGrp7Wkg) shows the behavior in question
