### ISSUE TITLE
[BUG][RAID] Magmaw sometimes drops away from the raid when pinned

### ISSUE THREAD

**Issue by l0uki** [JamminL/cata-classic-bugs#1119]
#### 1.1. Description
After being pinned to the ground, Magmaw can drop away from the raid, placing the exposed head out of reach.
  #### 1.2. How to Reproduce
           1. Engage Magmaw
           2. Wait for Magmaw to do his slam attack
           3. Have players jump on Magmaw
           4. Pin Magmaw
           5. Have Magmaw randomly drop to the wrong direction, away from the raid.
  #### 1.3  Source Material
None, sorry. Not sure what exactly causes the behavior, it happened in one of ten attempts. Will add if we can clip it.
#### 2.1. Description
Magmaw should drop to the front when properly pinned, exposing its head.
  #### 2.2 Source Material
{Video, Posts, etc..}

**Comment by kenthklui** [comment]
Appears to be still happening on live.

https://www.twitch.tv/videos/2159473081?t=05h37m55s
