### ISSUE TITLE
[BUG] Mind Flay loses final tick when clipped by another cast of Mind Flay

### ISSUE THREAD

**Issue by adhdk** [JamminL/cata-classic-bugs#1121]
#### 1.1. Description
Mind Flay loses the last tick of damage when it is clipped by another Mind Flay cast after the 2nd tick. 
  #### 1.2. How to Reproduce
           1. Cast Mind Flay
           2. After 2nd tick of Mind Flay, start casting Mind Flay again and let the cast complete. 
           3. Notice only 5 ticks of Mind Flay damage. 
  #### 1.3  Source Material
![image](https://github.com/JamminL/cata-classic-bugs/assets/134566385/ffcf5341-812e-4fb2-95a6-a0f8d3ebadb5)

#### 2.1. Description
Clipping Mind Flay after the 2nd tick with another cast of Mind Flay should not lose the final tick. 
  #### 2.2 Source Material
https://warcraft.wiki.gg/wiki/Patch_4.1.0
![image](https://github.com/JamminL/cata-classic-bugs/assets/134566385/33fc7f56-4588-4947-b149-15902506a196)

**Comment by TheHate123** [comment]
Mind Sear is exactly the same.
https://www.youtube.com/watch?v=GxcLONhyUNM - Reference video for both of them
