### ISSUE TITLE
[BUG] Glyph of Death's Embrace not working

### ISSUE THREAD

**Issue by Heroclassx** [JamminL/cata-classic-bugs#1130]
### 1. Current Behavior 
Glyph of Death's Embrace is not refunding runic power when used to heal your Dk Ghoul pet, for some unknown reason it does work when healing your gargoyle tho.
 
 #### 1.1. Description
"Glyph of Death's Embrace: Your Death Coil refunds 20 Runic Power when use to heal an allied minion." 

  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Apply Glyph of Death's Embrace to your Glyph slot
           2. Use Death Coil @pet (your ghoul) 
           3. Observe how you not receive any runic power after healing your pet
           
### 2. Expected Behavior
As the glyph mentions when healing an allied minion (your pet) it should reward the 20 runic power as mentioned in the tooltip

**Comment by AidanZMoon** [comment]
This is not bugged.
Death's Embrace does not provide runic power to you if you do full overhealing.
Have your pet take damage and then heal it with Death's Embrace glyph again to see
![image](https://github.com/JamminL/cata-classic-bugs/assets/137581830/8a566c37-0271-469f-b9be-26e958aa022d)
