### ISSUE TITLE
[BUG] [Paladin] Guardian of the ancient kings double dipping healing reduction

### ISSUE THREAD

**Issue by Heroclassx** [JamminL/cata-classic-bugs#1137]
### 1. Current Behavior
  Guardian of the ancient kings is supposed to duplicate healing for the holy paladin. Right now it seems to double dip with healing reduction effects. The initial heal from paladin gets reduced by the healing reduction then guardian copies the heal from paladin and it gets reduced once again.

{Describe how that mechanic/spell/npc is currently working, in detail}
See 1. Current Behavior

  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Use guardian of the ancient kings 
           2. heal once with healing reduction on a target and once without
           3. guardian should do more or less the same healing as the paladin but with healing reduction it does exact healing reduction value less
           
  #### 1.3  Source Material
https://clips.twitch.tv/PoisedHelpfulEndiveNerfRedBlaster-g_wlJcbb3fS_4PfQ

### 2. Expected Behavior
It shouldn't double dip.

**Comment by JamminL** [comment]
You will need to find some evidence for this, this behavior seems accurate
