### ISSUE TITLE
[BUG] Combat sometimes not being applied by aoe spells?

### ISSUE THREAD

**Issue by Heroclassx** [JamminL/cata-classic-bugs#1142]
Damaging a player should put you in combat but it seems like sometimes this does not happen. 

https://clips.twitch.tv/BrainyTsundereDiscYouDontSay-IFcHpmeZx4aAqIe5 

Shaman in dnd continues drinking

**Comment by JamminL** [comment]
Death and decay has LOS

**Comment by SimonBpvp** [comment]
I agree this shouldnt put combat, but he doesn't even take damage by the looks of it. Do you have to be in LoS of the centre of dnd to take dmg?

**Comment by AidanZMoon** [comment]
Yes. Otherwise you could Death and Decay things through walls by placing the center on your side of the wall, and the edge goes through the wall to whatever you wanna hit

**Comment by SimonBpvp** [comment]
interesting, thanks, do you know if it's the same with Flamestrike, Concecration and what about other effects like Flare?

**Comment by AidanZMoon** [comment]
If they do not have the ignores line of sight flag, they will be the same
