### ISSUE TITLE
[BUG] Pets are ignoring feign death

### ISSUE THREAD

**Issue by MannySJH** [JamminL/cata-classic-bugs#1143]
#### 1.2. How to Reproduce
           1. Send pet to attack a hunter
           2. Feign death as hunter
           3. No change in combat state regardless of pet behavior (Passive,aggressive)
#### 2.2 Source Material
https://www.youtube.com/watch?v=J9kNEWD6egg&t=315s&ab_channel=TosanTribe

The water ele in this clip stops attacking and adjusts its position to the mages side exactly how pet follow functions.

**Comment by MannySJH** [comment]
https://youtu.be/uySiPvXlXpY?si=RqOQlcfVMCv3EYFS&t=373
Stumbled upon this video also, hunter feigning the pet scorpions attack. 
https://youtu.be/uySiPvXlXpY?si=ojKhDGq907_jr798&t=369

**Comment by AidanZMoon** [comment]
Do you have more detailed steps for this?
I am unable to reproduce this on 4.4.0, the pet goes back to the owner.
Does this have something to do with having aggressive on?

**Comment by MannySJH** [comment]
I did two tests, fiend on aggressive completely ignored my feign. Second was a hunter pet on passive which also ignored my feign. Mirror images behaved the same way. This was on live prepatch not beta if that makes a difference.

**Comment by AidanZMoon** [comment]
Hmm if you could include a video of the bug occurring that will help it get approved as a bug. Just see 2 videos of expected behavior.

Idk if it's a live issue vs. Other realms but I'll look into it. Just haven't been able to reproduce it but I believe it is happening. Just don't know what condition is causing the difference on my end.

**Comment by MannySJH** [comment]
Did some testing on beta vs live. Seems like aggressive pets will not under any circumstances stop attacking based on feign death on both beta and live. A passive pet however on beta will work respond to feign as expected.
https://streamable.com/n2yl3u
https://streamable.com/wd0tql

However on live prepatch even a passive pet won't respond to feign death
https://streamable.com/d4g82x

**Comment by AidanZMoon** [comment]
Thank you so much for looking into this MannySJH. I really appreciate it.
So it looks like there's a fix coming for it that will make Passive work correctly.
Aggressive is an out dated stance for pets that is eventually going to be replaced by Assist Me (which is what happened in original cataclysm).
So it makes sense that Aggressive is not supported correctly. Appreciate this @JamminL can approve
