### ISSUE TITLE
[BUG] [RAID] Atramedes telegraphs for Sonar Bomb missing during flight phase

### ISSUE THREAD

**Issue by l0uki** [JamminL/cata-classic-bugs#1146]
#### 1.1. Description
The animation of Atramedes' Sonar Bomb (ID 92553) is currently not displaying the telegraph on the ground. 
  #### 1.2. How to Reproduce
          1. Engage Atramedes in BWD
          2. Wait until he starts Flight Phase
          3. Observe the missing ground effects
  #### 1.3  Source Material
![image](https://github.com/JamminL/cata-classic-bugs/assets/109001923/9ba66d24-449b-4ed4-95bf-e76fb0b6e956)

Bugged Animation:
![image](https://github.com/JamminL/cata-classic-bugs/assets/109001923/44a6db06-00d9-4442-b79a-9f314deae452)

![image](https://github.com/JamminL/cata-classic-bugs/assets/109001923/44dfeef8-350d-400d-a4bf-bb5e7e652357)

#### 2.1. Description
Player's are supposed to use the ground animation to preemptively dodge the projectiles/aoe.
  #### 2.2 Source Material
![image](https://github.com/JamminL/cata-classic-bugs/assets/109001923/2a0cecec-0307-437c-b14a-1af50ff7be01)
https://youtu.be/Yuwo2oHgIp8?t=241

**Comment by Northlol** [comment]
Same issue across every telegraph in the raids afaik- Cho'gall Crash, this, Halfus fireballs etc.

**Comment by CharWS** [comment]
the atramedes telegraphs specifically appear to be working properly now
