### ISSUE TITLE
[BUG] Hand of Gul'Dan currently being displayed and working as a totem

### ISSUE THREAD

**Issue by l0uki** [JamminL/cata-classic-bugs#1148]
#### 1.1. Description
Hand of Gul'dan is supposed to create an aura around the positon of the target it was cast on, applying a debuff in a 4y area. Currently, this seems to implement a totem, using the totem bar UI with a Consecration symbol. The UI element also works functionally as a totem, allowing a player to dismiss the effect via right-clicking. For no apparent reason, the Curse of Gul'dan debuff can then apply to the player who cast Hand of Gul'dan as well.
  #### 1.2. How to Reproduce
           1. Be Warlock
           2. Spec into Demonology, Select Hand of Gul'dan as a Skill
           3. Cast Hand of Gul'dan on a enemy (some Dummies don't work, use a real NPC)
           4. Observe the icon in the totem UI
           5. Right Click to despawn the Hand of Gul'dan Area Effect
           6. Sometimes gain the Hand of Gul'dan debuff  
  #### 1.3  Source Material
  
![image](https://github.com/JamminL/cata-classic-bugs/assets/109001923/bc7fe9fb-ab6b-479d-b8ff-e71c7ccc0fd7)

[Video of Testing](https://youtube.com/live/PF1Q-Pyhxpk)

#### 2.1. Description
Hand of Gul'dan should not allow interaction as a totem.
  #### 2.2 Source Material
N/A

**Comment by SimonBpvp** [comment]
![image](https://github.com/JamminL/cata-classic-bugs/assets/94299191/663bf34b-76a5-4fd8-b031-d4dc86596127)
the totem part looks blizzlike (literally spent 1 minute on youtube)
https://youtu.be/mVS8BX83G44?feature=shared&t=42

I don't know if you can right click it like a totem, I assume yes or else why would they put it there, but theres no source.

But the debuff affecting the player who casted it is probably the bugged part but again no source on that.
