### ISSUE TITLE
[BUG] Hand of freedom and hand of protection not being useable while being CC't

### ISSUE THREAD

**Issue by Heroclassx** [JamminL/cata-classic-bugs#1151]
### 1. Current Behavior
Right now you are not able to use HoF and HoP while being in any form of CC 

{Describe how that mechanic/spell/npc is currently working, in detail}
You should be able to use those spells while being CC't

          {Describe the steps to reproduce the particular bug, in detail:
           1. Start a duel 
           2. get cycloned/any form of CC
           3. try using hand of freedom or hand of protection
           
  #### 1.3  Source Material
https://youtu.be/gEsD2_0SR3M?t=89
https://youtu.be/LoGjJ366eZ4?t=209 
https://youtube.com/clip/Ugkxo9QDTOR3wGZTRLanL7kLSEZQuz1oTDqy?si=JXN_F5YzNHVpWDLg
https://youtu.be/lj9fN07W7wg?t=38
https://youtu.be/fDnGK7SKyDc?t=146

### 2. Expected Behavior
As you can see in the video from retail cataclysm you should be able to use hand of freedom (and hand of protection due to same mechanic) while being in CC

**Comment by AidanZMoon** [comment]
This is not bugged.
Hand of Freedom CAN currently be cast while under the effect of Crowd Control like Cyclone.
Hand of Protection CANNOT be cast while under the effect of anything that would not be removed by the cast. E.g. Hammer of Justice, Cyclone, Fear. 
Hand of Protection CAN be cast while under the effect of anything that would be purged on cast. E.g. Blind, Sap, Kidney Shot.

**Comment by Heroclassx** [comment]
I mean currently you can use freedom in some CC's on your teammates and in others you can't. 

https://streamable.com/9vhv8c 

Here is a clip on current beta not being able to use freedom on a friendly target while being in scatter/monkey blind.

**Comment by AidanZMoon** [comment]
That is accurate to 4.4.0
You cannot cast Freedom while Disoriented. Blind, Scatter, Monkey Blind will lock you out of Freedom.
