### ISSUE TITLE
Warlock: Pet combat trading issues

### ISSUE THREAD

**Issue by Scrynax** [JamminL/cata-classic-bugs#1152]
#### 1.1. Description
When pets get in combat the owner can't get in combat via: **Soul link, Unending breath** - only way how to trade combat from pet is Dark Intent.
  #### 1.2. How to Reproduce
           1. Summon pet
           2. Auto attack -> pet get in combat
           3. Buff Soul Link, Unending breath
           4. owner is not in combat
  #### 1.3  Source Material
**imp**: (https://streamable.com/cafxop)
**succubus**: https://streamable.com/ufuuu9
**felhunter**: https://streamable.com/xugkzu
**voidwalker**: https://streamable.com/njrn8s
#### 2.1. Description
Any buff I cast on a pet should get me in combat: That includes Soul Link, Unending Breathing, Dark Intent (this works).

  #### 2.2 Source Material
combat trading with soul link (TBC classic, worked same way in WotLK): https://youtu.be/iX9IFuCGLiQ?t=1230

Permanent combat trading (without pet actually hitting anything and being AFK) was obviously a bug in TBC / WotLK, but as long the pet is in combat the owner should be able to get it from the pet.

**Comment by Scrynax** [comment]
@JamminL Why did you close this without any comment?

**Comment by Scrynax** [comment]
I understand why the Seduction ticket is closed, because Simon came up with facts. But I dont see any world why it wouldnt work with other buffs aside from Dark Intent, Also Hunters can do exactly the same thing, perma feed the pet and directly stay in combat through their pet attacking. :)

**Comment by JamminL** [comment]
Both Unending and Soul Link do not trigger combat at all in cata. If you find evidence of otherwise I'll reopen it @Scrynax.
