### ISSUE TITLE
Warlock: Succubus casting Seduction does not put pet in combat

### ISSUE THREAD

**Issue by Scrynax** [JamminL/cata-classic-bugs#1153]
#### 1.1. Description
When Succubus casts Seduction, the pet does not get into combat state - any other ability works that way (was the same in WotLK / TBC Classic)
  #### 1.2. How to Reproduce
           1. Summon Succubus
           2. Cast seduction on target
           3. Target is Seducted, but pet is not in combat (so isnt owner obv)
  #### 1.3  Source Material
Succubus: https://streamable.com/ufuuu9
### 2. Expected Behavior
Pet should get in combat.

  #### 2.2 Source Material
WotLK Classic: https://clips.twitch.tv/SuspiciousOpenCrocodileMcaT-4ToE_-TjGrfRVx8D

If Seduction channel was dropping combat, pet would be out of combat by the time Seduction ends (it lasted full duration) - its clearly Cataclysm Beta / Prepatch bug.

**Comment by SimonBpvp** [comment]
not a bug, this was changed in patch 4.2 along with blind and a bunch of others. It was designed specifically for dungeons but it affects PvP too. Basically none of these cc abilities listed should put you in combat.

![image](https://github.com/JamminL/cata-classic-bugs/assets/94299191/d9589aaa-3236-4eca-8519-a67bdd38c463)

https://wowpedia.fandom.com/wiki/Patch_4.2.0

**Comment by Scrynax** [comment]
Fair enough @SimonBpvp, but this is a bug https://github.com/JamminL/cata-classic-bugs/issues/1152, not sure why you guys close it without any comment.
