### ISSUE TITLE
[#SomeChanges Suggestion] Buff the conquest cap to make PvP gear more achievable given the shorter seasons

### ISSUE THREAD

**Issue by jimusah** [JamminL/cata-classic-bugs#1154]
### Description
{Describe your suggestion}
![conquest](https://github.com/JamminL/cata-classic-bugs/assets/93409374/3a21b171-8485-4552-8451-7534ff9cd44f)

Currently it costs 30950 conquest to purchase every PvP item including elite weapons. In the sheet above I've outlined the estimated time to achieve this with various levels of conquest cap. Unfortunately I did not find a verified & working conquest cap calculator for Cataclysm online, so I opted to just show different conquest cap values rather than rating.

So here we can see that if you are an elite PvPer, you may expect to achieve full gear in around 11-12 weeks time NOT including any drops you may get from Baradin Hold (too RNG to include).

My suggestion is simple and also outlined in the spreadsheet. Buff the conquest cap by something like 50-75%. If that happens, we can now see that this drastically cuts down the time required even for more average PvPers, as with just a 2400 normal cap, this would now become 3600 or 4200, which means that even the average player can now expect full gear in <8 weeks realistically.

75% may be a little optimistic to hope for, but I feel even a 50% buff would help out greatly as that puts the estimate at around 7-8 weeks minus whatever you get from Baradin Hold. This will greatly improve seasons as you can now enjoy playing with full gear before the season is over, and any alts you make even 1 month into the season may end up getting full gear before it's over. Right now with the 11-12 week timeframe it will feel pretty terrible to play any alts unless you made them week 1 of the season, given that seasons in Cataclysm are expected to last around 3-4 months each.

**Comment by Kenniflopper** [comment]
I would suggest you also increase the conquest points per arena win, the default points you get per win is 180, should maybe considering increasing that accordingly to the cap so you dont have to do 25-30 games to cap per character.

**Comment by dedestus** [comment]
> I would suggest you also increase the conquest points per arena win, the default points you get per win is 180, should maybe consider increasing that accordingly to the cap so you dont have to do 25-30 games to cap per character.

more games required = more activity :)

**Comment by SimonBpvp** [comment]
Jimusa makes very good points but I agree with the boy ^ I think we will get more activity if it's normal 1x.

**Comment by Kenniflopper** [comment]
> > I would suggest you also increase the conquest points per arena win, the default points you get per win is 180, should maybe consider increasing that accordingly to the cap so you dont have to do 25-30 games to cap per character.
> 
> more games required = more activity :)

Yeah but not everyone can play 30 arenas per char every week, and imagine they got 3-5 chars in total. There is no conquest catchup system so they will end up being so behind on gear eventually.

**Comment by dedestus** [comment]
> > > I would suggest you also increase the conquest points per arena win, the default points you get per win is 180, should maybe consider increasing that accordingly to the cap so you dont have to do 25-30 games to cap per character.
> > 
> > 
> > more games required = more activity :)
> 
> Yeah but not everyone can play 30 arenas per char every week, and imagine they got 3-5 chars in total. There is no conquest catchup system so they will end up being so behind on gear eventually.

well not everyone can raid on 5 characters either because it is really time consuming, at some point you have to pick your priorities

**Comment by ManneN1** [comment]
They need to also add a catchup, so if you miss a week or are coming in a couple of months late you're not completely screwed.

Basically just add the catch-up that was originally added in MoP, but make it more powerful (instead of 1000 CP catch-up per week - make it whatever your cap was that week, either the default 0 rating 2200 CP cap or higher if you actually had a raised cap).

**Comment by SimonBpvp** [comment]
1k/1250 Conq per week catchup would be fair and not OP imo
