### ISSUE TITLE
[BUG][RAID] Rocket Boots can lauch you in the air in raids

### ISSUE THREAD

**Issue by Northlol** [JamminL/cata-classic-bugs#1166]
#### 1.1. Description
Rocket boots can launch you into the air in raid- according to old wowhead comments, that malfunction was designed as "an alternative failure for dungeons, raids, and battlegrounds."
  #### 1.2. How to Reproduce
           1. Enter a raid
           2. Use rocketboots until failure
  #### 1.3  Source Material
Was happening frequently- will try to clip tomorrow, hard to find clear POV as the person I was spectating was not engi.
#### 2.1. Description
Only rocket fuel leak should be available as a malfunction
  #### 2.2 Source Material
![msedge_kMYEVTtISM](https://github.com/JamminL/cata-classic-bugs/assets/43507247/260adf93-b227-42ee-837c-909eaf06cfd6)
![msedge_2UZk4dUkX0](https://github.com/JamminL/cata-classic-bugs/assets/43507247/7e16b4a9-4406-45da-90a4-781b104aeb90)
![msedge_RKEOobcDqU](https://github.com/JamminL/cata-classic-bugs/assets/43507247/28d8ab16-06ba-4b65-941a-bbdbb98911ce)
All found on [wowhead's entry](https://www.wowhead.com/cata/spell=55016/nitro-boosts#comments) for rocket fuel leak

Blue post submitted by lordblackadder describing the intention to not be able to be blasted into the air in raids / dungeons
https://www.wowhead.com/blue-tracker/topic/why-do-nitro-boosts-kill-you-now-2416120230#24519251114

**Comment by lordblackadder** [comment]
https://www.wowhead.com/blue-tracker/topic/why-do-nitro-boosts-kill-you-now-2416120230#24519251114
blue post from back then regarding that change
