### ISSUE TITLE
[BUG] Ring of Frost AoE Indicator

### ISSUE THREAD

**Issue by JamminL** [JamminL/cata-classic-bugs#1175]
#### 1.1. Description
Since last build on beta 54558 the ring of frost indicator is much smaller than it should be
  #### 1.2. How to Reproduce
           1. Cast Ring of Frost
           2. Notice the AoE Green Indicator is considerably smaller than the 10 yard radius of the ring
           
![image](https://github.com/JamminL/cata-classic-bugs/assets/107503518/d7ddfff3-2750-4875-9299-8d041fe74a4d)

**Comment by Rivahlol** [comment]
Also, the ring breaks too easily, the treshold is bugued. As we can see on this video, https://www.youtube.com/watch?v=bK8Qw4ZXFJA&t=271s it should not break after 1 or 2 ticks of living bomb, only when it explodes or after 2-3 ticks.

**Comment by JamminL** [comment]
> Also, the ring breaks too easily, the treshold is bugued. As we can see on this video, https://www.youtube.com/watch?v=bK8Qw4ZXFJA&t=271s it should not break after 1 or 2 ticks of living bomb, only when it explodes or after 2-3 ticks.

This is related with issue #1078

**Comment by Rivahlol** [comment]
> > Also, the ring breaks too easily, the treshold is bugued. As we can see on this video, https://www.youtube.com/watch?v=bK8Qw4ZXFJA&t=271s it should not break after 1 or 2 ticks of living bomb, only when it explodes or after 2-3 ticks.
> 
> This is related with issue #1078

Can we precise it on the issue #1078 then please? I see only fear being mentioned there.
