### ISSUE TITLE
[BUG] Honor Among Thieves buff is stacking (Visually)

### ISSUE THREAD

**Issue by MannySJH** [JamminL/cata-classic-bugs#1177]
### 1. Current Behavior
  Honor Among Thieves buff is stacking (Visually)
{Describe how that mechanic/spell/npc is currently working, in detail}
  #### 1.2. How to Reproduce
Join a raid/group with multiple subtlety rogues
  #### 1.3  Source Material
![Capture](https://github.com/JamminL/cata-classic-bugs/assets/168474168/ea2be3ef-2d3a-4778-811f-6df7efe533dc)

**Comment by SimonBpvp** [comment]
as it should I think

**Comment by SimonBpvp** [comment]
It visually stacked here:

![image](https://github.com/JamminL/cata-classic-bugs/assets/94299191/27f36415-ded3-4208-9b66-158062f65488)

https://youtu.be/IgNNCXWzzVQ?feature=shared&t=427
