### ISSUE TITLE
[BUG] API_UnitGetIncomingHeals is returning extremely incorrect values

### ISSUE THREAD

**Issue by Kangamooster** [JamminL/cata-classic-bugs#1179]
#### 1.1. Description
The UnitGetIncomingHeals API is returning very incorrect values, either way too high or way too low.

  #### 1.2. How to Reproduce
           1. Use a direct heal on someone, with an addon tracking the UnitGetIncomingHeals API.
           2. The healing amount predicted is very off.
  #### 1.3  Source Material
![image](https://github.com/JamminL/cata-classic-bugs/assets/166673485/79e77afa-a375-4f1f-89ce-9c47ca3fa1b4)

#### 2.1. Description
The predicted healing should be identical to the amount of healing that will be done.

  #### 2.2 Source Material
n/a

**Comment by AidanZMoon** [comment]
Steps for this without an addon
1. Be healer or have healer that can heal you.
2. Target yourself.
3. Have an incoming heal from yourself or another player.
4. Type `/dump UnitGetIncomingHeals("player")`
5. Observe the number produced and the healing value when it lands.
6. Notice they aren't equal.

This needs to be fixed before incoming healing on frames is added to the game, or those frames will be wildly off.
