### ISSUE TITLE
[BUG][RAID] Heroic Nefarion (And maybe other tier bosses) are not dropping normal tokens

### ISSUE THREAD

**Issue by Northlol** [JamminL/cata-classic-bugs#1180]
#### 1.1. Description
Heroic Nef (and other bosses, did not check the others) are only dropping heroic tokens
  #### 1.2. How to Reproduce
           1. Kill Nef on heroic
           2. Loot him
  #### 1.3  Source Material
Screenshot after our kill 
![ApplicationFrameHost_32XIKZA0t3](https://github.com/JamminL/cata-classic-bugs/assets/43507247/0281cc3a-fa8e-4173-abea-8f2601cb622f)

#### 2.1. Description
Bosses should drop normal and heroic versions of their tier: just like ICC.
  #### 2.2 Source Material
[Vodka Video](https://youtu.be/fWkk2h83w3M?t=657) with this screenshot, Helm (normal) vs. Crown (Heroic)
![image](https://github.com/JamminL/cata-classic-bugs/assets/43507247/28f84f43-8786-479c-b08d-2ac19955c8df)

**Comment by Lillyton** [comment]
Not a bug. 

https://www.youtube.com/watch?v=OzFWjtZiZ-M - They killed Nef on heroic and only got heroic token. 

https://wowpedia.fandom.com/wiki/Patch_4.0.6
![image](https://github.com/JamminL/cata-classic-bugs/assets/137237050/f33e2903-ca8e-4297-bd49-c2cf26a12229)

**Comment by CharWS** [comment]
https://youtu.be/En8lkMTeQC0?t=627 can see only crowns in this kill video from March 26, 2011 as well (patch 4.0.6 released February 8, 2011)
