### ISSUE TITLE
[BUG] 2500 Daily Quests and 100k GMMOMM are not retroactively counting.

### ISSUE THREAD

**Issue by LordOfOtakus** [JamminL/cata-classic-bugs#1191]
#### 1.1. Description
The achievements 2500 Daily Quests Completed and Got My Mind On My Money (100k version) are not counting progress retroactively.
  #### 1.2. How to Reproduce
          Check your achievement progess on these achievements, and compare to your statistics page on characters.
  #### 1.3  Source Material
![Screenshot 2024-05-09 at 11 23 43 AM](https://github.com/JamminL/cata-classic-bugs/assets/75953994/0c93748d-e430-4625-85cf-f7ea2d2dff7d)
![Screenshot 2024-05-09 at 11 23 52 AM](https://github.com/JamminL/cata-classic-bugs/assets/75953994/6ae5f2c8-cbd2-4684-b192-935de9005204)
![Screenshot 2024-05-09 at 11 24 03 AM](https://github.com/JamminL/cata-classic-bugs/assets/75953994/0b64393d-1b6f-4c85-bcb0-891dd725a692)
![Screenshot 2024-05-09 at 11 24 14 AM](https://github.com/JamminL/cata-classic-bugs/assets/75953994/568b4717-186b-4d64-ad8b-593721be9ad2)

#### 2.1. Description
Retroactive progress should be counted, because 2500 Daily Quests and 100k gold looted is a LOT.
  #### 2.2 Source Material
N/A, Cata didn't have account-wide achievements originally (both of them are marked as tracking progress account-wide). Likely where the issue lies.

**Comment by lavjamanxd** [comment]
![image](https://github.com/JamminL/cata-classic-bugs/assets/10040415/7d12948f-51e1-444f-bc0b-a5b89497ad76)
![image](https://github.com/JamminL/cata-classic-bugs/assets/10040415/2409440e-419b-499f-898e-f787e8dadf75)
![image](https://github.com/JamminL/cata-classic-bugs/assets/10040415/c1ab3ba4-3661-444b-928c-7bc7ad30b618)
![image](https://github.com/JamminL/cata-classic-bugs/assets/10040415/7d941b8d-5f32-4032-b2a9-3bcbb6576ce3)

looks like it just got fixed

**Comment by LordOfOtakus** [comment]
Hasn't gone through for me yet, did you do anything in particular?

**Comment by lavjamanxd** [comment]
We had a server restart on Golemagg not long ago, after i logged back in the 2500 daily quests achi popped up

**Comment by LordOfOtakus** [comment]
They must've fixed it after US realm restarts but before EU ones. Guess it might be a bit before it hits US.
