### ISSUE TITLE
[BUG] Heroic Tier Helmet and Shoulders require normal tier when they shouldn't

### ISSUE THREAD

**Issue by Northlol** [JamminL/cata-classic-bugs#1198]
#### 1.1. Description
Heroic Tier Helmet and Shoulders on the Valor vendors requires the normal tier piece. In patch 4.0.6 Cho'gall and Nefarion stopped dropping their normal tier, but Heroic Helmet and Shoulders had their normal tier piece requirement removed. Cho and Nef are correctly not dropping normal tier pieces, but the vendors have the incorrect purchasing prerequisites. 
  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Try to purchase tier helmet or shoulders from the valor quartermaster
  #### 1.3  Source Material
![WowClassicB_FNbsNfstth](https://github.com/JamminL/cata-classic-bugs/assets/43507247/e3928058-3162-4f59-a6c7-7af505ecc8d4)
![WowClassicB_p5ZKg6bmu2](https://github.com/JamminL/cata-classic-bugs/assets/43507247/7e02108f-8b98-4e25-8b61-baf7a9ac4d4f)
![WowClassicB_hfefkAtZKF](https://github.com/JamminL/cata-classic-bugs/assets/43507247/776e128e-4723-4ce0-bc3b-799f383a5f77)
Current beta build
#### 2.1. Description
Tier Helmet and Shoulders should be purchasable with ONLY the Heroic tokens
  #### 2.2 Source Material
![msedge_6HnotVy1pT](https://github.com/JamminL/cata-classic-bugs/assets/43507247/196c4596-727d-4913-8af0-c9a1a91e87dd)
Patch 4.0.6

**Comment by AidanZMoon** [comment]
This is only applicable to the Helm and Shoulders for Tier 11.
Chest/Legs/Gloves will still require you to have the Normal versions of them before upgrading them to Heroic.

**Comment by Northlol** [comment]
true, editing it to reflect that, thanks
