### ISSUE TITLE
[BUG] Mage water elemental freeze cooldown wont reset on new pet

### ISSUE THREAD

**Issue by oldspices** [JamminL/cata-classic-bugs#1199]
#### 1.2. How to Reproduce
          
           1. summon water elemental.  
           2. use freeze
           3. summon new elemental

#### 2.2 Source Material  
 this is how its worked all of wotlk etc etc, for warlock pets too. 
https://www.wowhead.com/cata/spell=33395/freeze

**Comment by JamminL** [comment]
NAB was hotfixed during s11 for both mages and warlocks
