### ISSUE TITLE
[BUG] Living bomb explosion should not proc ignite

### ISSUE THREAD

**Issue by JamminL** [JamminL/cata-classic-bugs#1206]
#### 1.1. Description
Living bomb explosion should not proc ignite if it crits, it currently is.
  #### 1.2. How to Reproduce
           1. Cast living bomb on a target
           2. Wait for living bomb to expire
           3. Notice if that explosion crits, ignite is procced

#### 2.1. Description
You shouldn't get ignite if your Living bomb explosion crits
  #### 2.2 Source Material
https://youtu.be/BL4qBoxDcEg?t=916

**Comment by Moistxx** [comment]
Ignite should proc off non-periodic damage. The explosion is a non-periodic damage, the ticks of living bomb, correctly, shouldn't proc living bomb

Not sure why you think living bomb explosion _shouldn't_ proc ignite.


Cataclysm [Patch 4.3.0](https://wowpedia.fandom.com/wiki/Patch_4.3.0) (2011-11-29): Damage over time has been increased by approximately 10%, and explosion damage has been increased by approximately 120%.
Cataclysm [Patch 4.2.0](https://wowpedia.fandom.com/wiki/Patch_4.2.0) (2011-06-28): When Spell fire meteorstorm [[Impact]](https://wowpedia.fandom.com/wiki/Impact_(mage_talent)) spreads Living Bomb, it will only be spread to two additional targets. The net effect is that if the mage's most recent Living Bomb target is the same as their Impact target, that target will no longer lose the Living Bomb effect. If Living Bomb is active on multiple targets when the Impact effect is cast, Living Bomb will remain active on the most recent Living Bomb target, and will be added to two other nearby targets.
Cataclysm [Patch 4.0.6](https://wowpedia.fandom.com/wiki/Patch_4.0.6) (2011-02-08): Mana cost has been reduced by 22%.
Cataclysm [Patch 4.0.1](https://wowpedia.fandom.com/wiki/Patch_4.0.1) (2010-10-12): Now limited to 3 targets, hits a maximum of 3 targets with its explosion, and no longer explodes when dispelled. Moved to tier 7 (was tier 11).
Wrath-Logo-Small [Hotfix](https://web.archive.org/web/20090809194619/http://forums.worldofwarcraft.com/thread.html?topicId=19110153306&sid=1) (2009-08-05): Periodic damage no longer interacts with Ability mage hotstreak [[Hot Streak]](https://wowpedia.fandom.com/wiki/Hot_Streak).
Wrath-Logo-Small [Patch 3.2.0](https://wowpedia.fandom.com/wiki/Patch_3.2.0) (2009-08-04):
Can now be active on multiple targets at the same time.
Periodic critical strikes from this ability can now trigger Ignite and Hot Streak.
Wrath-Logo-Small [Patch 3.0.8](https://wowpedia.fandom.com/wiki/Patch_3.0.8) (2009-01-20): Hot Streak is now also affected by Living Bomb.
Wrath-Logo-Small [Patch 3.0.3](https://wowpedia.fandom.com/wiki/Patch_3.0.3) (2008-11-04):
Mana cost reduced to be the same as Spell nature wispsplode [[Arcane Explosion]](https://wowpedia.fandom.com/wiki/Arcane_Explosion).
Living Bomb's "explosion effect" will now be properly classified.
Wrath-Logo-Small [Patch 3.0.2](https://wowpedia.fandom.com/wiki/Patch_3.0.2) (2008-10-14): Added.

**Comment by JamminL** [comment]
> Not sure why you think living bomb explosion _shouldn't_ proc ignite. In wrath it was changed that periodic critical strikes from the ability can trigger ignite (it shouldn't proc Hot Streak)
> 
> Cataclysm [Patch 4.3.0](https://wowpedia.fandom.com/wiki/Patch_4.3.0) (2011-11-29): Damage over time has been increased by approximately 10%, and explosion damage has been increased by approximately 120%. Cataclysm [Patch 4.2.0](https://wowpedia.fandom.com/wiki/Patch_4.2.0) (2011-06-28): When Spell fire meteorstorm [[Impact]](https://wowpedia.fandom.com/wiki/Impact_(mage_talent)) spreads Living Bomb, it will only be spread to two additional targets. The net effect is that if the mage's most recent Living Bomb target is the same as their Impact target, that target will no longer lose the Living Bomb effect. If Living Bomb is active on multiple targets when the Impact effect is cast, Living Bomb will remain active on the most recent Living Bomb target, and will be added to two other nearby targets. Cataclysm [Patch 4.0.6](https://wowpedia.fandom.com/wiki/Patch_4.0.6) (2011-02-08): Mana cost has been reduced by 22%. Cataclysm [Patch 4.0.1](https://wowpedia.fandom.com/wiki/Patch_4.0.1) (2010-10-12): Now limited to 3 targets, hits a maximum of 3 targets with its explosion, and no longer explodes when dispelled. Moved to tier 7 (was tier 11). Wrath-Logo-Small [Hotfix](https://web.archive.org/web/20090809194619/http://forums.worldofwarcraft.com/thread.html?topicId=19110153306&sid=1) (2009-08-05): Periodic damage no longer interacts with Ability mage hotstreak [[Hot Streak]](https://wowpedia.fandom.com/wiki/Hot_Streak). Wrath-Logo-Small [Patch 3.2.0](https://wowpedia.fandom.com/wiki/Patch_3.2.0) (2009-08-04): Can now be active on multiple targets at the same time. Periodic critical strikes from this ability can now trigger Ignite and Hot Streak. Wrath-Logo-Small [Patch 3.0.8](https://wowpedia.fandom.com/wiki/Patch_3.0.8) (2009-01-20): Hot Streak is now also affected by Living Bomb. Wrath-Logo-Small [Patch 3.0.3](https://wowpedia.fandom.com/wiki/Patch_3.0.3) (2008-11-04): Mana cost reduced to be the same as Spell nature wispsplode [[Arcane Explosion]](https://wowpedia.fandom.com/wiki/Arcane_Explosion). Living Bomb's "explosion effect" will now be properly classified. Wrath-Logo-Small [Patch 3.0.2](https://wowpedia.fandom.com/wiki/Patch_3.0.2) (2008-10-14): Added.

Not debating whether it should, just that it didn't

**Comment by Moistxx** [comment]
> > Not sure why you think living bomb explosion _shouldn't_ proc ignite. In wrath it was changed that periodic critical strikes from the ability can trigger ignite (it shouldn't proc Hot Streak)
> > Cataclysm [Patch 4.3.0](https://wowpedia.fandom.com/wiki/Patch_4.3.0) (2011-11-29): Damage over time has been increased by approximately 10%, and explosion damage has been increased by approximately 120%. Cataclysm [Patch 4.2.0](https://wowpedia.fandom.com/wiki/Patch_4.2.0) (2011-06-28): When Spell fire meteorstorm [[Impact]](https://wowpedia.fandom.com/wiki/Impact_(mage_talent)) spreads Living Bomb, it will only be spread to two additional targets. The net effect is that if the mage's most recent Living Bomb target is the same as their Impact target, that target will no longer lose the Living Bomb effect. If Living Bomb is active on multiple targets when the Impact effect is cast, Living Bomb will remain active on the most recent Living Bomb target, and will be added to two other nearby targets. Cataclysm [Patch 4.0.6](https://wowpedia.fandom.com/wiki/Patch_4.0.6) (2011-02-08): Mana cost has been reduced by 22%. Cataclysm [Patch 4.0.1](https://wowpedia.fandom.com/wiki/Patch_4.0.1) (2010-10-12): Now limited to 3 targets, hits a maximum of 3 targets with its explosion, and no longer explodes when dispelled. Moved to tier 7 (was tier 11). Wrath-Logo-Small [Hotfix](https://web.archive.org/web/20090809194619/http://forums.worldofwarcraft.com/thread.html?topicId=19110153306&sid=1) (2009-08-05): Periodic damage no longer interacts with Ability mage hotstreak [[Hot Streak]](https://wowpedia.fandom.com/wiki/Hot_Streak). Wrath-Logo-Small [Patch 3.2.0](https://wowpedia.fandom.com/wiki/Patch_3.2.0) (2009-08-04): Can now be active on multiple targets at the same time. Periodic critical strikes from this ability can now trigger Ignite and Hot Streak. Wrath-Logo-Small [Patch 3.0.8](https://wowpedia.fandom.com/wiki/Patch_3.0.8) (2009-01-20): Hot Streak is now also affected by Living Bomb. Wrath-Logo-Small [Patch 3.0.3](https://wowpedia.fandom.com/wiki/Patch_3.0.3) (2008-11-04): Mana cost reduced to be the same as Spell nature wispsplode [[Arcane Explosion]](https://wowpedia.fandom.com/wiki/Arcane_Explosion). Living Bomb's "explosion effect" will now be properly classified. Wrath-Logo-Small [Patch 3.0.2](https://wowpedia.fandom.com/wiki/Patch_3.0.2) (2008-10-14): Added.
> 
> Not debating whether it should, just that it didn't

Likely that it was wrong in OG, not that it's wrong now =]. Happens with 15+ year old game code.
I wouldn't say this is a bug. It's working 'as intended' as per patch notes, and as per spell ability wording.
