### ISSUE TITLE
[BUG] Hyperspeed Accelerators/Synapse Spring from Ingineering + Trinket on use at the same time.

### ISSUE THREAD

**Issue by Murk825** [JamminL/cata-classic-bugs#1213]
#### 1.1. Description
I can use Tinker : Hyperspeed Accelerators from Ingineering and any on use Trinket at the same time.

  #### 1.2. How to Reproduce
Need  Hyperspeed Accelerators on gloves and any on use trinket.
          
           1.  /use 10
           2. /use 13 or /use 14
           3. and voilá 

  #### 1.3  Source Material
https://ibb.co/xGYHWK5

#### 2.1. Description
In original Cataclysm you can only have one on use at a time, like trinket pvp burst first then (20s after) Synpase Spring after the buff from the trinket end.

  #### 2.2 Source Material
https://youtu.be/Zz6VW8cXwKk?si=gkZ_NicSjizXWibR&t=37
https://ibb.co/yyknZmv

**Comment by CharWS** [comment]
https://us.forums.blizzard.com/en/wow/t/wrath-of-the-lich-king-classic-hotfixes-updated-january-9/1323891/220 that behavior was intentionally changed to function that way in wotlk classic

**Comment by Murk825** [comment]
> https://us.forums.blizzard.com/en/wow/t/wrath-of-the-lich-king-classic-hotfixes-updated-january-9/1323891/220 that behavior was intentionally changed to function that way in wotlk classic

I see Thanks for reply! I hope it's not gonna work like this for Cata (Synapse Spring), In OG Cata dev intentionally balance all profession to be roughly the same. I dont want to be force to have Ingineering on all my chars ... like previous extension did.

**Comment by Woffl8** [comment]
Currently sharing a CD on Cata, is this abug Char as they should not be sharing like in WoTLK?

**Comment by Woffl8** [comment]
@CharWS

**Comment by CharWS** [comment]
The initial report specifically tested the wotlk Hyperspeed Accelerators which weren't bugged in their function because of the wotlk change. If blizz has decided to adjust this behavior now for Cataclysm that'd also be not a bug so long as engi cds are usable in macros with other off gcd abilities (the original bug that brought about the change in wotlk). 

If you notice issues with engi cds paired with other abilities in macros not working feel free to post here or in a new issue, but otherwise should be working fine.

**Comment by diamondsprings** [comment]
it would be lovely to get some sort of confirmation on whether or not this will be changed. most players seem to be fine with it working either which way, but this one interaction changes the value of the profession immensely and as such it will single-handedly decide if the profession is worth keeping for a lot of players. 

with the wotlk precedent it very much feels like a situation where it inevitably gets changed in a couple of weeks just in time for everybody to have dropped engineering for another profession after thinking it would work like it did in wotlk - not only does needlessly re-leveling professions cost heaps of gold, but some classes will actually gear differently depending on the interaction of this enchant.
