### ISSUE TITLE
Bad Manner cancels itself [BUG]

### ISSUE THREAD

**Issue by Pozzel** [JamminL/cata-classic-bugs#1220]
#### 1.1. Description
Right now, if you use bad Manner on a target it will cancel itself, because the cast starts as soon, as the Monkey reaches the range of the target and then the Monkey instantly runs away, back to the location it should be in (towards the hunter if on passive, or the target, if it's on attack). This will cancel the cast, because the Monkey is out of range ones the cast finishes. It makes the ability very hard to use, and it's not predicable, when the monkey will be in range for it. This seems like a mechanic, which by itself is contra intuitive, as it makes the ability not usable. 

Check this youtube video from beta: 
https://www.youtube.com/watch?v=rTG9r8MGT2E
  #### 1.2. How to Reproduce
Go to training dummy.
Use Bad Manner on a target, that is not instantly in range (with dash active, to make it more realistic). 
 
  #### 1.3  Source Material
U can see it here on my video. Just a test on how it is right now on beta. 
https://www.youtube.com/watch?v=rTG9r8MGT2E
### 2. Expected Behavior
It should finish the cast before going back, if the target is in range and in line of sight. 

  #### 2.2 Source Material
on 0:22 or 1:32, just to name an example
https://www.youtube.com/watch?v=avdaBz2JZfc

**Comment by Kenniflopper** [comment]
It seems to be related to movement speed increases such as dash, if dash is up and you try to bad manner a target it will attempt to bad manner and then automatically run back to you before the cast is over, cancelling its own cast.

**Comment by MannySJH** [comment]
I found something similar which could be related
https://streamable.com/xr52hk
Seems like other pet actions will resume before the bad manner cast is finished. The case here being a mouseover cast of bad manners while the pet is attacking another target. I also tested this with a felhunter and spell lock went off in the same scenario flawlessly.

**Comment by Aggrend** [comment]
We just sent a fix for this issue late last week and it should now be resolved.
