### ISSUE TITLE
[BUG] Prayer of Mending Glyph should increase the initial heal by 60%

### ISSUE THREAD

**Issue by SkriemNL** [JamminL/cata-classic-bugs#1221]
#### 1.1. Description
  
Prayer of Mending, while Glyphed, heals 100% extra on the first target. Instead of 60%.
It was mentioned that Prayer of Mending wasnt working right and got fixed.
In the same post it was mentioned that the Glyph now increases the initial heal by 100%.
But this should not be the case, see sources below.

  #### 1.2. How to Reproduce

           1. Cast Prayer of Mending on target that takes damage -> check amount healed
           2. Apply Glyph of Prayer of Mending and repeat -> check amount healed
           (Or read tooltip description of Glyph of Prayer of Mending)
           
  #### 1.3  Source Material
  
[https://www.bluetracker.gg/wow/topic/eu-en/510644-cataclysm-classic-hotfixes-10-may/ ](url)

#### 2.1. Description

Glyph of Prayer of Mending should be increasing the initial heal by 60% not 100% 

For reference:
Majorglyph - small improvement OR big improvement with a downside attached to it
Prime Glyph - big spell improvements

Increasing the Heal by 100% should not be in the Major Glyph Category
Even 60% is a lot but that is what it was during the entirety of Cataclysm

In MoP it was even changed to 60% + 1 Less Bource
To make it more balanced against other (classes) Major Glyphs as it was too strong.

I think this 100% thing is an oversight from Blizzard and should be reverted back to 60%

See sources below

  #### 2.2 Source Material
  
  **Patch notes on the Glyph itself** (no 100% mentioned in any of the itterations)
  [https://wowpedia.fandom.com/wiki/Glyph_of_Prayer_of_Mending](url)
  
  **Priest healing guide from 2014 - Patch 4.3.4**
[https://www.tauri-veins.com/discipline-priest-wow-pve-healing-spec-builds-talents-glyphs](url)
  
**Priest guide from 2011/2012 - Patch 4.3**
[https://gotwarcraft.com/guides/classguides/disciplinepriest.php](url)

**Holy Priest guide from  - Patch 4.3.4**
[https://wowbesttalentguides.blogspot.com/2014/04/Best-Priest-Guide-PVE-Raid-Healer-Talent-Build-Glyphs-Cataclysm-4-3-4.html](url)

**Youtube Video from 2012 - Patch 4.3** (4 Minute 37 Seconds in)
[https://youtu.be/CsCdPuS6cK8?si=5CpxBgKdq2Q5BzPH&t=277](url)

**Further i went though all the patch notes of Cataclysm here:** (no mention anywhere about changing the Glyph to 100%)
[https://wowwiki-archive.fandom.com/wiki/Category:World_of_Warcraft_patches](url)

**The Glyph started and ended Cataclysm with 60% 
No Change was made to this value from 4.0.1 all the way to 4.3.4**

**Comment by AidanZMoon** [comment]
This is Not A Bug.

This was to compensate Grace priests for the loss of Grace double dipping on PoM (a bug fix).
So PoM will do the almost the same as 4.3.4 with Glyph + Grace.
It's a buff to all PoM glyph using priests, but it means Grace bug isn't reintroduced, and it also means Grace + Glyph priests aren't nerfed. It would've been the difference between 27k heals and 21k heals if it hadn't been compensated.

**Comment by SkriemNL** [comment]
Thanks for clarifying - (this explanation would have been nice in the blue post together with the change) 
This buffs Holy priests tank heals a bit which i can fully get behind ;)
<3
