### ISSUE TITLE
[#SomeChanges Suggestion] Make RMP less oppressive in arenas.

### ISSUE THREAD

**Issue by Kenniflopper** [JamminL/cata-classic-bugs#1224]
Introduction:
The Rogue-Mage-Priest (RMP) composition has established itself as a formidable force in World of Warcraft Cataclysm arenas. This setup, featuring a blend of crowd control, burst damage, and sustained pressure, has left many players feeling frustrated and overwhelmed. In this report, we delve into the specific aspects of RMP that make it obnoxious to face and propose potential solutions to restore balance and enjoyment to arena matches.

The Menace of Blazing Speed and Impact Talents:
Blazing Speed and Impact talents provide RMP with unparalleled mobility and control over the battlefield. The ability to quickly close gaps, escape sticky situations, and disrupt enemy strategies significantly tips the scales in their favor. This combination not only enhances their offensive capabilities but also amplifies their defensive prowess, making it exceedingly challenging for opponents to gain any meaningful momentum.

Smoke Bomb's Disruptive Influence:
Smoke Bomb serves as a linchpin in the RMP arsenal, offering a zone of control that cripples enemy visibility and coordination. Its ability to nullify incoming attacks and force opponents into unfavorable positions creates chaos and frustration among adversaries. This disruptive nature not only undermines the strategic depth of arena gameplay but also diminishes the sense of agency for opposing teams.

Persistent Crowd Control with Dragons Breath and Ring of Frost:
Dragons Breath and Ring of Frost further compound the issue by providing RMP with potent crowd control tools that defy conventional counters. The inability for these abilities to break on Damage over Time (DoT) effects grants RMP an unfair advantage, allowing them to maintain control and dictate the tempo of engagements with relative ease. This unrelenting pressure stifles any attempts at retaliation and leaves opponents feeling helpless against the onslaught.

Insane Burst Damage and Healing Denial:
One of the most egregious aspects of RMP is its capacity for insane burst damage coupled with nearly unhealable pressure. The synergy between Rogue's burst, Mage's spell damage, and Priest's utility results in devastating spikes of damage that can quickly overwhelm even the most prepared opponents. Furthermore, the combination of crowd control and damage output makes it exceptionally challenging for enemy healers to keep their teammates alive, leading to situations where sustained healing becomes nearly impossible.

Unrivaled Crowd Control:
RMP boasts the most extensive array of crowd control abilities compared to any other composition in the game. With the Rogue's numerous stuns, the Mage's polymorphs and freezes, and the Priest's fears and silences, RMP can effectively lock down multiple targets simultaneously, rendering them unable to act or retaliate. This overwhelming control severely limits the options for opposing teams, leaving them vulnerable to coordinated assaults and strategic maneuvers from the RMP squad.

Proposal: Implementing Composition Restrictions:
To address the overwhelming dominance of RMP in Cataclysm arenas, one potential solution is to introduce composition restrictions that prevent certain classes from queuing together. By disallowing Rogue, Mage, and Priest from forming a team in 3v3 arenas, the prevalence of RMP compositions would be mitigated, fostering greater diversity and balance in competitive play. This measure would not only alleviate the frustration experienced by opponents but also encourage experimentation with alternative strategies and compositions.

Conclusion:
The prominence of RMP compositions in WoW Cataclysm arenas poses a significant challenge to the integrity and enjoyment of competitive gameplay. The combination of Blazing Speed, Impact talents, Smoke Bomb, Dragons Breath, Ring of Frost, devastating burst damage, and unrivaled crowd control creates an oppressive environment where opponents are left feeling outmatched and outmaneuvered. By implementing composition restrictions, such as disallowing Rogue, Mage, and Priest from queuing together in 3v3 arenas, the balance of power can be restored, ensuring a more diverse and engaging experience for all players involved.

**Comment by perpabc** [comment]
lol

**Comment by MoreLikeX** [comment]
pop off chat gpt

**Comment by dedestus** [comment]
Y I K E S

**Comment by tmpnm099** [comment]
Thanks kenni for providing absolutely nothing of value to this github while bloating it with spam and burner accounts, only to accomplish nothing
