### ISSUE TITLE
[BUG] Heirlooms are not stacking experience bonus on lvl 80

### ISSUE THREAD

**Issue by RevinderDev** [JamminL/cata-classic-bugs#1225]
#### 1.1. Description
Heirlooms don't stack (chest + shoulders) don't give additional 20% experience, but rather give 10%. This is significant because it could possibly mean that stacking with helmet (which would total to 30%) would not work either, which combined with prequesting would make a huge advantage.

  #### 1.2. How to Reproduce
           1. Equip both shoulder and chest heirlooms.
           2. Finish a quest of your choice
           3. voilá

![image](https://github.com/JamminL/cata-classic-bugs/assets/32570664/e5dea7a9-11b2-4d69-afdc-8ecf70ac788e)
![image](https://github.com/JamminL/cata-classic-bugs/assets/32570664/100289d9-16c0-420b-86e7-977a12cde6bc)
![image](https://github.com/JamminL/cata-classic-bugs/assets/32570664/7a53974e-64c1-4660-9311-b582a4ca9c68)

Experienced gained is 6050 (increased from 5500) which means it was increased by 10% not 20%. Unless I am misunderstanding how increased experience gained is working it should rather be equal to 6600, and not 6050.

5500 * 0.2 + 5500 = 6600
5500 * 0.1 + 5500 = 6050

  #### 1.3  Source Material
[Athene's world first lvl 85 video](https://youtu.be/txdtw_Wtet4?t=83)
Not really necessary to look for source,  since it's looks like a math error but, blue posts indicates that they would work on lvl 80 (thus helping 80-81). Good source is from Athene world first lvl 85 video where he leveraged similar trick.

#### 2.1. Description
Given 20% bonus gained experience (or 30% with helmet, though I don't have access to it yet so couldn't test it).
  #### 2.2 Source Material
See 1.3.

**Comment by JamminL** [comment]
The 10% comes from the guild perk, heirlooms will not work at 80 to 85 on launch
