### ISSUE TITLE
talent points glow as if you gained a talent point every ding- minor bug[BUG]

### ISSUE THREAD

**Issue by oldspices** [JamminL/cata-classic-bugs#1235]
#### 1.1. Description
![image](https://github.com/JamminL/cata-classic-bugs/assets/26885524/3ed884f8-872c-4118-ac65-bf9377d9e95c)
this icon shown in picture flashes when you level even if you dont gain a talent point, its just annoying. 
{Describe how that mechanic/spell/npc is currently working, in detail}
  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. level 
           2. it glows when it shouldnt
          
  #### 1.3  Source Materialoilá}
  #### 1.3  Source Material
{Video, Posts, etc..}

**Comment by CharWS** [comment]
duplicate of https://github.com/JamminL/cata-classic-bugs/issues/1106
