### ISSUE TITLE
[BUG] Ignite is not being removed by Blind

### ISSUE THREAD

**Issue by JamminL** [JamminL/cata-classic-bugs#1249]
#### 1.1. Description
Blind is supposed to remove all dot/bleed effects on the target, but it currently isn't removing ignite.
  #### 1.2. How to Reproduce
           1. Proc Ignite on a target
           2. Blind the target
           3. Notice Ignite is not removed
  #### 1.3  Source Material
[{Video, Posts, etc..}](https://www.twitch.tv/videos/2146372676?t=03h12m54s)

Might be worth checking Piercing Shots and Deepwounds as well!

**Comment by Snipin** [comment]
Can confirm piercing shots is not removed by Blind either.
