### ISSUE TITLE
[BUG] Hand of Sacrifice transfered damage not breaking cc

### ISSUE THREAD

**Issue by JamminL** [JamminL/cata-classic-bugs#1271]
#### 1.1. Description
Hand of Sacrifice transfered damage is not breaking ccs that should break on direct damage. E.g Dragon's Breath and Repentance.
  #### 1.2. How to Reproduce
           1. Hand of Sacrifice someone
           2. Get Dragon's Breathed
           3. Have the person with Hand of Sacrifice take damage
           4. Notice that despite you took damage during Dragon's Breath from the sac, the dragon's breath didn't break
  #### 1.3. Source
https://streamable.com/71z5jy
https://streamable.com/hjulqs
#### 2.1. Description
Dragon's Breath and Repentance should break on any direct damage, including Hand of Sacrifice damage you take
  #### 2.2 Source Material
https://youtu.be/VetEVJg1sWI?t=111

**Comment by Bugtrack123** [comment]
Hand of Sacrafice also doesnt break scatter shot atm

**Comment by Heroclassx** [comment]
https://clips.twitch.tv/FitTenaciousPrariedogBudStar-5M0wiAZ1wT14JE5k
