### ISSUE TITLE
[BUG] Force of Nature breaking drinks

### ISSUE THREAD

**Issue by JamminL** [JamminL/cata-classic-bugs#1272]
#### 1.1. Description
Currently, if treats are up, enemies are not able to sit down for a drink. Aslong as the treants are around, even if they don't attack you or put you in combat, they constantly interrupt your drink/eating
  #### 1.2. How to Reproduce
           1. Have a Druid cast Force of Nature, then set it to passive and /petfollow so they're afk following the Druid
           2. As an enemy of the druid, attempt to drink/eat
           3. Notice you keep canceling the drink instantly
  #### 1.3 Source
https://streamable.com/c4z144

**Comment by SimonBpvp** [comment]
There was a bug on retail where you could never be sapped with your treants out if you sent them to attack. Not sure if this is related to that though.
