### ISSUE TITLE
[BUG] Unused Blood of Zul'jin from TBC ZA Converted to Lvl 85

### ISSUE THREAD

**Issue by ssabbyccatt** [JamminL/cata-classic-bugs#1277]
#### 1.1. Description
Blood of Zul'jin from TBC ZA has converted into the level 85 version if unused. 
  #### 1.2. How to Reproduce
           1. Find a character that didn't turn in their Blood of Zul'jin during TBC and still has it.
           2. Item has converted into lvl 85 version
  #### 1.3  Source Material
![Screenshot 2024-05-19 131556](https://github.com/JamminL/cata-classic-bugs/assets/99249505/c4999a30-3a78-48bb-8efc-f3db9e446aaa)
#### 2.1. Description
Suggest turning all existing Blood of Zul'jins into a grey item prior to ZA/ZG's Cata release, to prevent players who still have this from having a potential/slight advantage over other players (admittedly, not a huge advantage as the quest only leads to 353s)
  #### 2.2 Source Material
Quest added in 4.1 + rewards available here: https://wowpedia.fandom.com/wiki/Warlord_of_the_Amani

**Comment by Lillyton** [comment]
ZG/ZA will not only be closed until they release, but this item only starts a quest. The quest it starts will require you to kill a boss in ZA, so it doesn't do anything until ZA is released.

**Comment by ssabbyccatt** [comment]
> ZG/ZA will not only be closed until they release, but this item only starts a quest. The quest it starts will require you to kill a boss in ZA, so it doesn't do anything until ZA is released. The turn-in for this quest will also be inside the instance. You can also skip this item completely and pick up the quest from a npc at the start of ZA, so there is no advantage to be gained with having this item.

Oh, great. It was super hard to discern what the hell was the point of this item, wowhead made it seem like it'd give you a quest that you could turn in for an insta-353. Will close this since it doesn't matter, ty!
