### ISSUE TITLE
[BUG] [item] [live realms] craftable 377ilvl cloak

### ISSUE THREAD

**Issue by SimonBpvp** [JamminL/cata-classic-bugs#1284]
![image](https://github.com/JamminL/cata-classic-bugs/assets/94299191/77de10bc-7fab-4880-bc74-5c512c6f0172)

it should be 339

**Comment by aneq** [comment]
Probably someone bought their recipes off live vendors while they were available somehow. Should be converted to 339 versions retroactively.
