### ISSUE TITLE
[BUG] Grove of Aessina does not properly phase after completing Aessina's Miracle, hardlocking the zone

### ISSUE THREAD

**Issue by ssabbyccatt** [JamminL/cata-classic-bugs#1289]
#### 1.1. Description
Once the quest Aessina's Miracle is complete, the phasing that is supposed to occur may fail. When this happens, all other quest hubs are completely empty of NPCs except for Nordrassil, and you cannot complete the zone (hard locks at 91/115 on the achiev)
  #### 1.2. How to Reproduce
           1. Complete Aessina's Miracle
           2. Other reproduction steps are unknown
  #### 1.3  Source Material
![Screenshot 2024-05-21 222231](https://github.com/JamminL/cata-classic-bugs/assets/99249505/ae8c5b8f-19e3-4def-b40e-d76ccbce840e)
Reddit post with more people experiencing this issue: https://www.reddit.com/r/cataclysm/comments/1cxbn77/aessinas_miracle_in_mount_hyjal/
Forum posts highlighting this bug: https://us.forums.blizzard.com/en/wow/t/hyjal-phasing-bug/1859107; https://us.forums.blizzard.com/en/wow/t/cata-hyjal-phasing-bug/1859110
#### 2.1. Description
Tortolla's Revenge quest should become available upon completing Aessina's Miracle, and completing this quest should also trigger a new phase of Mount Hyjal.
  #### 2.2 Source Material
https://www.wowhead.com/quest=25372/aessinas-miracle
https://www.wowhead.com/cata/quest=25843/tortollas-revenge

**Comment by ssabbyccatt** [comment]
Also hearing this has occurred to others in Uldum and Vashj, so seems to be a general phasing area that is not at all specific to Hyjal.

**Comment by ssabbyccatt** [comment]
More info: going into AQ40 and leaving fixes the phasing issues in Uldum. Will report back if it also fixes other zones' phasing issues.

**Comment by AidanZMoon** [comment]
Hamuul has 3 locations. Did you check all 3?
The Grove of Aessina, Shrine of Malorne, and then on the Road I believe.
https://www.wowhead.com/quest=25843/tortollas-revenge check all 3 locations of the Exclamation Point and let me know

**Comment by ssabbyccatt** [comment]
> Hamuul has 3 locations. Did you check all 3? The Grove of Aessina, Shrine of Malorne, and then on the Road I believe. https://www.wowhead.com/quest=25843/tortollas-revenge check all 3 locations of the Exclamation Point and let me know
> 
> ALSO are you level 85? We have a fix going out where being level 85 puts you in the "Firelands" phase

Yup, checked all 3, but I am 85 (and started Mt Hyjal at lvl 85)

**Comment by ssabbyccatt** [comment]
This is now fixed, thanks devs!
