### ISSUE TITLE
[BUG] Enchant Chest - Mighty Resilience 

### ISSUE THREAD

**Issue by Azmoddan** [JamminL/cata-classic-bugs#1297]
#### 1.1. Description
Enchant either doesn't give the benefit of 40 resilience or is not included in Character Pane -> Defense -> Resilience. Checked after both reload & relog & checked if its not the gem/gem bonus bug, the issue is still there so its not visual.
  #### 1.2. How to Reproduce

           1. Check your resilience without chest.
           2. Check your resilience with chest already enchanted with 40 resil.
           
   #### 1.3 Proof
   
   Resil without chest - 623
![image](https://github.com/JamminL/cata-classic-bugs/assets/42694757/3fefa9f3-3170-4dc3-9110-0ea480a049bf)
![image](https://github.com/JamminL/cata-classic-bugs/assets/42694757/9951a18a-bf45-478a-a468-d4323eb955ea)

   Resil with chest - 896 (supposed to be 936)
![image](https://github.com/JamminL/cata-classic-bugs/assets/42694757/664fffc9-d950-4b62-b97b-749a31e3e871)
![image](https://github.com/JamminL/cata-classic-bugs/assets/42694757/a2cc3d67-67a7-4c6b-a8e0-1173dc5a14c0)

**Comment by SimonBpvp** [comment]
+1 the math checks out

**Comment by Woffl8** [comment]
Was just going to post this bug, still broken :)

**Comment by Bisonpasfute** [comment]
Still bugged today :(
