### ISSUE TITLE
[BUG] Many Achievements Bugged

### ISSUE THREAD

**Issue by t3hWheez** [JamminL/cata-classic-bugs#1312]
## Dungeon Achievements

It’s Frost Damage
Acrocalypse Now
Rotten to the Core
Kill It With Fire!
Faster Than the Speed of Light
~~Vigorous VanCleef Vindicator~~
~~Ready for Raiding~~

## Quest Achievements

~~Rock Lover~~ The quest is available and not bugged, some realms just have bad RNG not seeing it.
~~[My Very Own Broodmother](https://github.com/JamminL/cata-classic-bugs/issues/1313)~~ - does not award achievement while doing this within the timeframe
[Bounce](https://github.com/JamminL/cata-classic-bugs/issues/1230) - can never get more than a single tick of 20 while bouncing no matter what
~~[Help the Bombardier! I’m the Bombardier!](https://github.com/JamminL/cata-classic-bugs/issues/1304)~~ - hitting 10 targets and watching quest go up by 10 still does not award credit
Ready, Set, Goat! - no progress ever tracks during this

**Comment by Zereges** [comment]
I've seen people with *Glory of the Cataclysm Hero* mount so I believe all of those achievements can be completed.

*Ready, Set, Goat!* can also be completed.

This issue should be closed.
