### ISSUE TITLE
Wormhole Generator: Northrend cant be used by party members [BUG]

### ISSUE THREAD

**Issue by oldspices** [JamminL/cata-classic-bugs#1316]
#### 1.1. the wormhole appears for one second then disappears to other party members- the user still can see it and use it but others cannot. 
{Describe how that mechanic/spell/npc is currently working, in detail}
  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. invite someone to party
           2. drop portal device
           3. they cannot use it
  #### 1.3  Source Material
![image](https://github.com/JamminL/cata-classic-bugs/assets/26885524/24914cb8-800a-47b8-8caa-fe40d394bf5c)

{Video, Posts, etc..}
#### 2.1. it should be usable by others 
{Describe how that mechanic/spell/npc should be working, in detail}
  #### 2.2 Source Material
i couldn't find anything stating they changed this 
{Video, Posts, etc..}

**Comment by CharWS** [comment]
https://warcraft.wiki.gg/index.php?title=Wormhole_Generator:_Northrend&oldid=662736
"Unlike a mage's portal, other party members are not able to see or use your portal, even if they have the required engineering skill."

**Comment by oldspices** [comment]
> https://warcraft.wiki.gg/index.php?title=Wormhole_Generator:_Northrend&oldid=662736 "Unlike a mage's portal, other party members are not able to see or use your portal, even if they have the required engineering skill."

thats weird because all of wotlk you could use it like a mage portal :D

**Comment by AidanZMoon** [comment]
There were some things in Wrath that were never supposed to be there but were kept because they didn't seem to cause any harm.

For example in OG Wrath the parachute cloak could actually only be activated if you were already off the ground or jumping. Unlike in wrath classic where if you pressed it the parachute deployed even if you were on the ground still.
