### ISSUE TITLE
[BUG] Achievement "Got My Mind On My Money" criteria is not formatted

### ISSUE THREAD

**Issue by raethkcj** [JamminL/cata-classic-bugs#1329]
#### 1.1. Description
  The achievement's criteria displays an unformatted copper amount, rather than broken down into Gold, Silver, and Copper.
  #### 1.2. How to Reproduce
           1. View Got My Mind On My Money in General tab of Achievements window.
           2. Observe it displays both the current and total amount as copper (10000 times the expected gold requirement)
  #### 1.3  Source Material
![image](https://github.com/JamminL/cata-classic-bugs/assets/7716908/6ffa6748-3e87-4ac4-b596-08c7efe1e6e2)

#### 2.1. Description
  The criteria should be formatted using `C_CurrencyInfo.GetCoinTextureString()` or similar, e.g.
![image](https://github.com/JamminL/cata-classic-bugs/assets/7716908/3d193103-553b-4bbd-a074-05aaa7ac8c99)

  #### 2.2 Source Material
https://everquest.allakhazam.com/wiki/Azuarc%27s_Lich_King_Journal_5

**Comment by ssabbyccatt** [comment]
Likely related to this - https://github.com/JamminL/cata-classic-bugs/issues/1286
seems all gold-related achievs are tracking copper rather than gold

**Comment by raethkcj** [comment]
Fixed in build 55141!
