### ISSUE TITLE
[BUG] Hand of Protection not being usable in a friendly targets while being in physical cc that can be removed by the abillity itself.

### ISSUE THREAD

**Issue by holylolz** [JamminL/cata-classic-bugs#1331]
#### 1.1. Description
You cannot use HoP on your friendly targets when u are in physical cc like "Blind", "Sap", "Warrior Fear", "Scatter shot"
  #### 1.2. How to Reproduce
           1. Be with a friendly in open world or arena
           2. Get any physical cc that can be removed by the abillity
           3. Try yo use Hand of Protection on your friend
  #### 1.3  Source Material
https://www.youtube.com/watch?v=lQBe7B54LmA (Current cata classic video)
#### 2.1. Description
U should be able to use Hand of Protection on friendly target while being in physical cc that can be removed by the abillity itself
  #### 2.2 Source Material
https://www.youtube.com/watch?v=lj9fN07W7wg&t=38s (Retail cataclyssm)

**Comment by Heroclassx** [comment]
Pretty much same thread as this:

https://github.com/JamminL/cata-classic-bugs/issues/1151

You mentioned in your post that you can't bop out of warrior fear tho, this is a bug tho as shown in this video, you should be able to use bop on a friendly target in intimidating shout.
https://www.youtube.com/watch?v=lj9fN07W7wg&t=38s

**Comment by JamminL** [comment]
> Pretty much same thread as this:
> 
> #1151
> 
> You mentioned in your post that you can't bop out of warrior fear tho, this is a bug tho as shown in this video, you should be able to use bop on a friendly target in intimidating shout. https://www.youtube.com/watch?v=lj9fN07W7wg&t=38s

You can when you're not the one targeted by the warrior fear. This also works on classic
