### ISSUE TITLE
[BUG] Eclipse Stops working after teleporting

### ISSUE THREAD

**Issue by JamminL** [JamminL/cata-classic-bugs#1335]
#### 1.1. Description
If you teleport somewhere while you're at 100 energy then you won't be able to proc eclipse until you cast a spell to reduce that energy by 100.
  #### 1.2. How to Reproduce
           1. Get 100 lunar or solar energy
           2. Take a teleport (enter a dungeon, join arena)
           3. Notice how you're not able to get eclipse anymore until you reduce your energy
  #### 1.3  Source Material
https://clips.twitch.tv/OnerousInterestingFungusGOWSkull-6dvGvVngKclLh9X7

**Comment by ssabbyccatt** [comment]
FYI when this happens, you don't need to reduce your energy by 100 to fix the issue. Reducing your energy by even 1 single cast and then adding energy with 1 more cast will allow eclipse to properly proc. For example:
Enter instance at 100 solar energy
Cast wrath to reduce energy from 100 to 87
Cast starfire/starsurge to increase energy to 100
Eclipse will proc.
