### ISSUE TITLE
[BUG?] mount speed buffs?

### ISSUE THREAD

**Issue by SimonBpvp** [JamminL/cata-classic-bugs#1344]
![image](https://github.com/JamminL/cata-classic-bugs/assets/94299191/30b3fe86-4b0a-4dc4-b385-c10364b0893a)

this gives you 220% speed mounted which means it's working multiplicatively, is that right? For some reason I remember it being additive aka giving 210% speed.  I could be completely wrong.

**Comment by lordblackadder** [comment]
Not a bug, takes 2 minutes to check:

https://www.wowhead.com/cata/spell=78633/mount-up#comments

https://warcraft.wiki.gg/index.php?title=Mount&oldid=4410922
![image](https://github.com/JamminL/cata-classic-bugs/assets/12127284/145c8b42-8478-4faa-9d57-e72811df54a3)
