### ISSUE TITLE
[BUG] Retribution talent Seals of Command procc rate is way off

### ISSUE THREAD

**Issue by hillerstorm** [JamminL/cata-classic-bugs#1350]
#### 1.1. Description
The talent [Seals of Command](https://www.wowhead.com/cata/spell=85126/seals-of-command) is supposed to have a 100% procc chance on every trigger of our seals but the observed chance is far lower.
A comment [on Wowpedia](https://wowpedia.fandom.com/wiki/Seals_of_Command) from 2012 mentions this bug as well.
  #### 1.2. How to Reproduce
1. Talent into [Seals of Command](https://www.wowhead.com/cata/spell=85126/seals-of-command)
2. Apply e.g. [Seal of Truth](https://www.wowhead.com/cata/spell=31801/seal-of-truth)
3. Start hitting stuff and notice a much lower than 100% procc chance.
  #### 1.3  Source Material
![image](https://github.com/JamminL/cata-classic-bugs/assets/779488/557b78e1-b2f8-4eb3-a387-a549d367355f)
https://classic.warcraftlogs.com/reports/D9tQGvjh7awp3Wqg#fight=2&type=damage-done&source=5&view=events&eventstart=1887503
#### 2.1. Description
It should have a 100% procc chance!
  #### 2.2 Source Material
https://wago.tools/db2/SpellAuraOptions?build=4.4.0.54901&filter[SpellID]=85126&page=1

**Comment by JamminL** [comment]
Because this bug is reference accurate, it's considered not a bug. You should reopen a ticket with the tag #somechanges
