### ISSUE TITLE
[#SomeChanges Suggestion] Retribution talent Seals of Command procc rate should be 100%

### ISSUE THREAD

**Issue by hillerstorm** [JamminL/cata-classic-bugs#1351]
#### Description
The talent [Seals of Command](https://www.wowhead.com/cata/spell=85126/seals-of-command) is supposed to have a 100% procc chance on every trigger of our seals but the observed chance is far lower.
A comment [on Wowpedia](https://wowpedia.fandom.com/wiki/Seals_of_Command) from 2012 mentions this bug as well.

![image](https://github.com/JamminL/cata-classic-bugs/assets/779488/557b78e1-b2f8-4eb3-a387-a549d367355f)

12min log above with ~66% procc chance
https://classic.warcraftlogs.com/reports/D9tQGvjh7awp3Wqg#fight=2&type=damage-done&source=5&pins=2%24Off%24%23244F4B%24expression%24ability.id%20in%20(20424,42463)

https://wago.tools/db2/SpellAuraOptions?build=4.4.0.54901&filter[SpellID]=85126&page=1

**Comment by Teebown** [comment]
Your log is private, can you make it unlisted or public?

**Comment by hillerstorm** [comment]
> Your log is private, can you make it unlisted or public?

oh shoot, sorry fixed :)

**Comment by hillerstorm** [comment]
![image](https://github.com/JamminL/cata-classic-bugs/assets/779488/9d2c5120-1a98-4b5b-be96-c3b8b9f2c18c)
![image](https://github.com/JamminL/cata-classic-bugs/assets/779488/f3b5ccc3-22e3-4637-b4d7-2afe14dc8bb8)
Okay false alarm apparently... I did my first test with 0% hit or exp and Seals of Command rolls for both of those but never shows up in the log when it fails...
Running below hit/exp cap shouldn't really happen so I guess it won't be an issue but the tooltip just threw me off since it states "... now also deal 7% weapon damage when triggered." instead of like Tiny Aboms "... causing you to instantly attack for 50% weapon damage with one of your melee weapons."
