### ISSUE TITLE
[BUG] Soulshard refund system still active for arena

### ISSUE THREAD

**Issue by SimonBpvp** [JamminL/cata-classic-bugs#1364]
#### 1.1. Description
Soul shards refund system was created in wrath where at the end of an arena match you'd receive all the soulshards you spent during the game back. It seems like that system is still in place.
  #### 1.3  Source Material
![image](https://github.com/JamminL/cata-classic-bugs/assets/94299191/587a4376-796d-44e0-9e50-ba42d353967b)
#### 2.1. Description
There should be no soulshards in cataclysm so that system can now be disabled.
  #### 2.2 Source Material
Cataclysm [Patch 4.0.1](https://wowpedia.fandom.com/wiki/Patch_4.0.1) (2010-10-12): [Soul Shards](https://wowpedia.fandom.com/wiki/Soul_Shard_(item)) have been removed from the game as items. Instead, they now exist as a resource system necessary for using or altering the mechanics of certain spells.

**Comment by JamminL** [comment]
Edited the post to follow proper format, please make sure to use it in the future!

**Comment by SimonBpvp** [comment]
I think this is fixed, it hasn’t happened to me in a long time. Not since the day of the report I think. Fixed ?

**Comment by CharWS** [comment]
can always reopen if anyone sees it happening again

**Comment by SimonBpvp** [comment]
![image](https://github.com/user-attachments/assets/722e538c-2e2c-468e-a503-0392561a7a12)
I got this bug again just now

**Comment by SimonBpvp** [comment]
I think you have to soulburn a demon in the arena to repro this

**Comment by SimonBpvp** [comment]
this is 100% fixed now i believe, don't remember seeing this happen one single time in months
