### ISSUE TITLE
[BUG]Player Frame Status Text missing on NA ( post tuesday update)

### ISSUE THREAD

**Issue by Snipin** [JamminL/cata-classic-bugs#1367]
#### 1.1. Description
{Describe how that mechanic/spell/npc is currently working, in detail}
  #### 1.2. How to Reproduce
           1. Enable Status Text
           2. Check Player Frame
           3. See all other frames have status text except for Player Frame
  #### 1.3  Source Material
(https://i.imgur.com/AlmSEBH.png)
#### 2.1. Description
Every frame should have Status Text enabled
  #### 2.2 Source Material
(https://i.imgur.com/P0fZuBI.png)

**Comment by Woffl8** [comment]
This has also broke other unitframe addons.
Seems blizzard has enabled predictive healing on the default Frames.
