### ISSUE TITLE
[BUG] inviting someone who is in a group already

### ISSUE THREAD

**Issue by SimonBpvp** [JamminL/cata-classic-bugs#1374]
#### 1.1. Description
If you invite someone who is in a group then the invite will lock you into a group status, then when the other player tries to invite you it won't work and you have to relog
  #### 1.2. How to Reproduce
         
           1. Join a group
           2. Friend tries to invite you
           3. You try to invite friend, it will say "already in a group" even though they aren't

#### 2.1. Description
it should allow you to invite the friend and not label them as "in a group" when they aren't

**Comment by JamminL** [comment]
> maybe it's intended but the part which makes it feel bugged is that you have to relog and then it works again.

If the person doesn't reject it, you'll just have to wait for the invite to timeout
