### ISSUE TITLE
[BUG] soul harvest interrupts itself since update

### ISSUE THREAD

**Issue by SimonBpvp** [JamminL/cata-classic-bugs#1385]
#### 1.1. Description
basically title, since the update my soul harvest interrupts itself like 50% of the time before the 2nd tick, and I'm chilling in SW not in a BG or something. I feel like it particularly occurs right after I get off mount.
https://www.wowhead.com/cata/spell=79268/soul-harvest

  #### 1.2. How to Reproduce
        
          1. hang out in stormwind and do some soul harvests

#### 2.1. Description
it should never interrupt itself while the player is doing nothing

**Comment by AidanZMoon** [comment]
Will need more information.
I am not experiencing this over 20 Soul Harvest casts in Stormwind.
Mounted recently, using it to break mount.
Attempting with 3 soul shards, 2 soul shards, 1 soul shard, 0 soul shards and it never interrupted itself.
Put on trinkets that can proc as well and they could only proc from the initial cast so it wasn't anything there interrupting me.

Will appreciate more info/a video of it happening as you get it.

Could be an addon, could be layering while channeling - unsure.

**Comment by SimonBpvp** [comment]
It only happens when my OBS isn't recording!

**Comment by SimonBpvp** [comment]
This seems fixed, or maybe it was my imagination all along…
