### ISSUE TITLE
[BUG] Living Bomb and Impact's interaction is very broken, thus breaking Pyromaniac as well

### ISSUE THREAD

**Issue by TheHate123** [JamminL/cata-classic-bugs#1390]
#### 1.1. Description
The game is miscalculating something, by the looks of it it's counting a bomb that was overwritten by another bomb via spreading with Impact as if the 1 mob has 2 bombs at once?
  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Put 2 bombs up
           2. Spread to a 3rd mob with Impact
           3. Refresh the Living Bomb early or dot something else, it will now delete a bomb from either target 1 or target 2, despite you only having 2 Living Bombs up at once.
           4. If you refresh the Living Bomb on the target that lost it, it will delete the other bomb that was left, again miscalculating.
           5. If you then refresh on that target, it will delete the Bomb from target 3, and if you refresh that one, you now have x3 Living Bombs, but no Pyromaniac buff
  #### 1.3  Source Material
{Video, Posts, etc..}
#### 2.1. Description
{Describe how that mechanic/spell/npc should be working, in detail}
  #### 2.2 Source Material
https://www.youtube.com/watch?v=PMoBBepkdiU

**Comment by AidanZMoon** [comment]
This has nothing to do with Impact or Pyromaniac.

This is Living Bomb canceling Bomb #1 when a Bomb above #3 is placed.

Three dummies.
Cast Living Bomb on Dummy #1
Cast Living Bomb on Dummy #2
Cast Living Bomb on Dummy #3
Recast Living Bomb on Dummy #3
Look at Dummy #1.

So yeah nothing to do with Impact or Pyromaniac. You are at 3 bombs, and you're casting a 4th bomb onto the already active Bomb #3. Reference accurate behavior but looks like typos so definitely a bug.
