### ISSUE TITLE
[BUG] anti-magic zone breaking

### ISSUE THREAD

**Issue by SimonBpvp** [JamminL/cata-classic-bugs#1401]
#### 1.1. Description
![image](https://github.com/JamminL/cata-classic-bugs/assets/94299191/0361e7fd-a49f-40e9-821e-674ec1471508)
AMZ breaks really fast. My guess is it's either not absorbing the amount that it says it should, or it's not providing the 75% damage reduction.
  #### 1.2. How to Reproduce
           1. get a dk to use AMZ 
           2. test some damage numbers and absorbs into it
  #### 1.3  Source Material
https://clips.twitch.tv/MuddyRelatedMonkeyCopyThis-gwykDjqCOpX4hJoD
#### 2.1. Description
The thing should provite 75% reduction to magic damage AND absorb the full amount displayed on the tooltip.
  #### 2.2 Source Material
https://youtu.be/BcFOD5BaXdE?feature=shared&t=1016

**Comment by JamminL** [comment]
This has already been tested and found not to be bugged. AMZ is really bad in a way that absorbs 30k before it breaks. Tests during beta and PTR have shown the numbers to be correct. If you have any other evidence I'll re-open.

**Comment by SimonBpvp** [comment]
Ok but I don't really agree, I think AMZ is not bad, it's supposed to be very strong but it's obviously bugged right now!
It should reduce incoming magic damage by 75% first, and then absorb what's left. So if you shoot a 35k chimera it shouldn't break the zone, it should do a 8750 damage chimera and subtract that from the 30k absorb so now the remaining absorb is now at 21,250. 

But I've not tested it myself, it just looked bugged to me from watching a bit of twitch streams.

**Comment by SimonBpvp** [comment]
I mean something is quite obviously bugged with it, the only time AMZ could despawn in one global like that is if you used it  right after your team got the the fattiest triple combust spread on all of you.

**Comment by JamminL** [comment]
You're welcome to do some tests, PTR is open! I've been down this rabbit hole and so have a few friends

**Comment by Palmie** [comment]
> So if you shoot a 35k chimera it shouldn't break the zone, it should do a 8750 damage chimera and subtract that from the 30k absorb so now the remaining absorb is now at 21,250.

This makes no sense.  The absorb portion is what gets subtracted, not the damage portion.  In this scenario 26250 would be subtracted from the absorb total and the remaining would be 8,750.

**Comment by SimonBpvp** [comment]
> > So if you shoot a 35k chimera it shouldn't break the zone, it should do a 8750 damage chimera and subtract that from the 30k absorb so now the remaining absorb is now at 21,250.
> 
> This makes no sense. The absorb portion is what gets subtracted, not the damage portion. In this scenario 26250 would be subtracted from the absorb total and the remaining would be 8,750.

it does make sense!
the absorb starts at 30,000
hit it with a 35,000 chimera shot, that gets reduced by 75%, down to 8,750
the remaining absorb is 21,250

the key part is the 75% damage reduction, it's in the tooltip!

**Comment by JamminL** [comment]
> > > So if you shoot a 35k chimera it shouldn't break the zone, it should do a 8750 damage chimera and subtract that from the 30k absorb so now the remaining absorb is now at 21,250.
> > 
> > 
> > This makes no sense. The absorb portion is what gets subtracted, not the damage portion. In this scenario 26250 would be subtracted from the absorb total and the remaining would be 8,750.
> 
> it does make sense! the absorb starts at 30,000 hit it with a 35,000 chimera shot, that gets reduced by 75%, down to 8,750 the remaining absorb is 21,250
> 
> the key part is the 75% damage reduction, it's in the tooltip!

That's not true, if you have a 75% reduction, it means it absorbed 75% of it. You can check wowhead comments as well

**Comment by SimonBpvp** [comment]
![image](https://github.com/JamminL/cata-classic-bugs/assets/94299191/78c6e6c5-4b23-49b8-9085-155947632c5e)

every single piece of magic damage that anyone takes while inside this thing should be reduced by 75%. In other words multiply every piece of damage by 0.25.

**Comment by Palmie** [comment]
It doesn't work like a reduction.  It works just like AMS does.  75% of damage is absorbed.  25% of the damage is still done to you.  I would advise testing it and reading the combat log to get a better understanding of the spell.

**Comment by JamminL** [comment]
> ![image](https://private-user-images.githubusercontent.com/94299191/338276700-78c6e6c5-4b23-49b8-9085-155947632c5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMzkzMDgsIm5iZiI6MTcxODAzOTAwOCwicGF0aCI6Ii85NDI5OTE5MS8zMzgyNzY3MDAtNzhjNmU2YzUtNGIyMy00OWI4LTkwODUtMTU1OTQ3NjMyYzVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDE3MDMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3MWM3MzU1NGI2MmZmNjE1NTY3YzMyYTFlYzllNDQ3MmQ2ZTEwMDI1NWQ0ZWEzYzQ3NzY2ZWQyNTFmMDIwMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y7GtJ-QezK0rtz2XMruF8n1v8DXZ7J4vNR2drZlMRc8)
> 
> every single piece of magic damage that anyone takes while inside this thing should be reduced by 75%. In other words multiply every piece of damage by 0.25.

That's not what it says. What this means is that the mitigation will happen before the total cap calculation. This also currently works.

But what you need to know is the way AMZ works. If it says you can absorb 30,000 damage, then if you get hit by a 40,000 spell, 30,000 will be absorbed and you'll be hit for 10k. And since the AMZ only absorbs 30,0000 the AMZ will disappear after the spell lands.

**Comment by SimonBpvp** [comment]
> It doesn't work like a reduction. It works just like AMS does. 75% of damage is absorbed. 25% of the damage is still done to you. I would advise testing it and reading the combat log to get a better understanding of the spell.

It works differently to AMS
![image](https://github.com/JamminL/cata-classic-bugs/assets/94299191/5b35525f-31cf-40d4-8b30-ec62f4bd41a5)
![image](https://github.com/JamminL/cata-classic-bugs/assets/94299191/a3884088-7b87-4ef1-9bc1-65eb643eaebd)

one says 'absorb' and the other says 'reduce'

If you guys have some extra knowledge that I don't know then I will love to learn it but just going off tooltips, twitch streams and retail videos / memory, something is completely bugged with AMZ. And I think it's the 75% thing. Every point of magic damage you take while inside the thing should be multiplied 0.25 (reduced 75%) and then that should be subtracted from the 30k or w/e it is.

**Comment by SimonBpvp** [comment]
> > ![image](https://private-user-images.githubusercontent.com/94299191/338276700-78c6e6c5-4b23-49b8-9085-155947632c5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMzkzMDgsIm5iZiI6MTcxODAzOTAwOCwicGF0aCI6Ii85NDI5OTE5MS8zMzgyNzY3MDAtNzhjNmU2YzUtNGIyMy00OWI4LTkwODUtMTU1OTQ3NjMyYzVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDE3MDMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3MWM3MzU1NGI2MmZmNjE1NTY3YzMyYTFlYzllNDQ3MmQ2ZTEwMDI1NWQ0ZWEzYzQ3NzY2ZWQyNTFmMDIwMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y7GtJ-QezK0rtz2XMruF8n1v8DXZ7J4vNR2drZlMRc8)
> > every single piece of magic damage that anyone takes while inside this thing should be reduced by 75%. In other words multiply every piece of damage by 0.25.
> 
> That's not what it says. What this means is that the mitigation will happen before the total cap calculation. This also currently works.
> 
> But what you need to know is the way AMZ works. If it says you can absorb 30,000 damage, then if you get hit by a 40,000 spell, 30,000 will be absorbed and you'll be hit for 10k. And since the AMZ only absorbs 30,0000 the AMZ will disappear after the spell lands.

i think you shouldn't BE hit by the 40k spell, because that 40k spell should 'become' a 10k spell

**Comment by CharWS** [comment]
tooltips don't define how spells function in game, they try to, but they don't always hit the mark, and this would be one such occasion, amz and ams both work as absorbs which you can see in the combatlog when using either, the absorbed amount of either is what's counted against their caps as to whether they should remove or persist after taking dmg

**Comment by SimonBpvp** [comment]
> tooltips don't define how spells function in game, they try to, but they don't always hit the mark, and this would be one such occasion, amz and ams both work as absorbs which you can see in the combatlog when using either, the absorbed amount of either is what's counted against their caps as to whether they should remove or persist after taking dmg

Totally agree with the first statement, however if you're only looking at the fact that they both absorb that doesn't falsify my claims at all, I'm saying that yes they both should absorb, but that the AMZ is a wall AND an absorb combined into one unique spell. 

I don't really understand the combat log thing, if we are talking about a bugged spell from my POV. So how it reads into the combat log on classic doesn't really tell me anything. If we had logs from retail to compare it to now, then that would be amazing.

**Comment by SimonBpvp** [comment]
check this, look how many spells and dots Sleepings tanks, if you get sent like this on classic your zone will break I think:
https://youtu.be/Vf45oASIDe0?feature=shared&t=2311

**Comment by CharWS** [comment]
that's one individual player taking a couple instances of dmg and walking out of the zone, the example you gave from classic had multiple players in the amz all getting hit by spells, so it broke sooner

**Comment by CharWS** [comment]
and AMZ was an absorb when cataclysm originally launched as well, not understanding how a spell works does not make the spell bugged

**Comment by SimonBpvp** [comment]
here, better example:
https://youtu.be/Vf45oASIDe0?feature=shared&t=789
