### ISSUE TITLE
[BUG] sometimes dungeons don't insta pop with 5 man

### ISSUE THREAD

**Issue by SimonBpvp** [JamminL/cata-classic-bugs#1403]
#### 1.1. Description
we queued 5 man hc dungos, we tried random and specific, but the queue didn't pop fast, it took a few minutes
  #### 1.2. How to Reproduce
           1. get 5 people 
           2. queue specific hc
           3. queue random hc
  #### 1.3  Source Material
![image](https://github.com/JamminL/cata-classic-bugs/assets/94299191/a7f79b05-5bed-4423-b570-02bd35ef23e3)
#### 2.1. Description
I believe it should insta pop because we queue as 5

**Comment by JamminL** [comment]
It may take around 1min ish for the dungeon to pop
