### ISSUE TITLE
[BUG] Retribution paladin crusader strike holy power generation on hit CRITICAL FOR HIGH END PVP

### ISSUE THREAD

**Issue by Traine9** [JamminL/cata-classic-bugs#1405]
#### 1.1. Description
If crusader strike  parried, dodged, hit mages, ice block or paladins bubble it DOESN'T generate holy power
  #### 1.2. How to Reproduce
         hit raid dummy with crusader strike until you get parried or dodged
  #### 1.3  Source Material
you can test it on any 10lvl+ pala
#### 2.1. Description
If crusader strike parried, dodged, hit mages, ice block or paladins bubble it DOES generate holy power
  #### 2.2 Source Material
see comment https://www.wowhead.com/cata/spell=35395/crusader-strike#comments:id=1321388:reply=223551

Retribution paladin survivability  suffers hard from current behavior in pvp 

P.S. does blizzard  use this bug tracker? because i cant create bug on forum from eu account

**Comment by JamminL** [comment]
As your comment on wowhead says, it should not proc off parry dodge or immunes.
