### ISSUE TITLE
[BUG] Vicious Gladiator's Pummeler T2 weapon impossible to obtain

### ISSUE THREAD

**Issue by JamminL** [JamminL/cata-classic-bugs#1421]
#### 1.1. Description
The Vicious Gladiator's Pummeler Elite Weapon is currently not purchasable. The theory is that the purchase requirements include the ruthless version of the weapon (s10) instead of the s9 counterpart.
  #### 1.2. How to Reproduce
           1. Go to Lieutenant Tristia in stormwind
           2. With conquest pts, rating and the normal version of Vicious Gladiator's Pummeler attempt to buy the elite counterpart
           3. Notice how you can't
  #### 1.3  Source Material
[{Video, Posts, etc..}](https://gyazo.com/d01095f45c5330c094d07cde67b8108b)
#### 2.1. Description
As with other elite weapons, it should be purchasable

**Comment by crossfactioninstancedpvp** [comment]
good find. make ALL 2.6 speed offhands cost 950, instead of just fist weapons. absolutely no authentic reason why orcs get fist wep expertise with 950 conquest, while dwarves have to fork up 2450 for off-hand Mace to take advantage of mace expertise. Thank you.

**Comment by Somatics23** [comment]
Fix this please

**Comment by Somatics23** [comment]
need this fixed asap..

**Comment by JamminL** [comment]
> need this fixed asap..

It was fixed today!

**Comment by Somatics23** [comment]
> > need this fixed asap..
> 
> It was fixed today!

Huge, thank you so much. Just tryna take advantage of my dwarf enh shams mace expertise racial, I almost bought fist weapons instead because I wasn’t sure about this getting fixed timely LOL, appreciate it a ton.
