### ISSUE TITLE
[#SomeChanges Suggestion] Change summoned guardians to inherit stats more quickly when spawned

### ISSUE THREAD

**Issue by danniellos94** [JamminL/cata-classic-bugs#194]
#### 1.1. Description
Dancing rune weapon incorrect damage on first hit. This only appears to be the first hit rest hits are consistent and almost the  same damage. This doesn't happen always.
Spell id 49028
  #### 1.2. How to Reproduce
           1.  Summon rune weapon.
           2.  Sometimes observe incorrect damage.
           
  #### 1.3  Source Material
https://classic.warcraftlogs.com/reports/BXWxGw8RDAY49ykV/#fight=4&type=damage-done&source=13

00:24.301	Rune Weapon 1 (Rugstox) Melee Loatheb 514
00:28.432	Rune Weapon 1 (Rugstox) Melee Loatheb 1354 Glancing    

00:14.826	Rune Weapon 1 (Rugstox) Melee Instructor Razuvious 551
00:16.909	Rune Weapon 1 (Rugstox) Melee Instructor Razuvious 1502   

02:27.380	Rugstox gains Dancing Rune Weapon from Rugstox
02:27.380	Rune Weapon 2 (Rugstox) Melee Kel'Thuzad 384 Glancing
02:29.730	Rugstox Melee Kel'Thuzad 1424 Glancing

#### 2.1. Description
DRW snapshots hit,haste,attack power and crit rating and %dmg buffs/debuffs.
  #### 2.2 Source Material

https://www.warcraftmovies.com/movieview.php?id=159567&__cf_chl_jschl_tk__=fe74e20672c61afa7427397e122b8546e84c3566-1618075195-0-AXPkg9hx47JPyGWd7Z-yVsBMopaNDOBlXzOUV-x5e8f2vTr_Pk9kCzUn6S_jNXW5QvUwPFQLacpUpX3CbdDRhwd-6RMPssgfjN7bGw_i2-UOMtvL0sS4vTO5iQmZeifYmd7-kz94f7SP7Eq-6XC9e025v0MHbyBJQmy7HYR87MLYyvvEve8sLZRjywFBP7J11_MjyDx3y3G4jLHCcHGM4SWrHA678OwIKzSdUAPNAKe_hKq4MLgtTo0eT86ZC-bZdYL5WvJlk7v9p-GYrpfxZ_PzbyEiUaBeH1r7aukPb7LNKkXPGaoPy_l04NJDlj2dl_eJOoG1uB2UatPA13heZhcO0ai6wKPd4RYV6nanBr4oTEAxwQ2fCZePMZ06TjUU2KHGxPYRtZtVfVYL9Pbb4m8Xcs8a09Xca5A6mh0my-7Q

**Comment by JamminL** [comment]
In the "expected behavior" part:

Desciption: describe how it should work
Source Material: Video evidence from back in the day

**Comment by danniellos94** [comment]
Updated with video.

**Comment by JamminL** [comment]
I'll edit the issue with the proper formatting, try to follow it please

**Comment by danniellos94** [comment]
This seems also happening for a gargoyle sometimes.

https://prnt.sc/KXYX9ktVzTF-

**Comment by Cleavis** [comment]
related to #239

**Comment by danniellos94** [comment]
Any answer for that? Looking at it incosistency behaviour I've doubt this is expected behaviour also this is really annoying for the player.

**Comment by MHMabrito** [comment]
@CharWS what additional research is needed when we can replicate it, and it's happening with other classes?

**Comment by Miyur1** [comment]
This is not a bug, all pets after being summoned have a small delay when adding stats, so 1 hit can deal base damage. Example:
You can see how pets are summoned with incomplete (base) health and then stats are added
https://youtu.be/HpthT7jE_oo?t=340
https://youtu.be/_YMPcyq4iVQ?t=120
https://youtu.be/IQYrH72-oXI?t=721
https://youtu.be/hXSswHbQ_xI?t=223
https://www.warcraftmovies.com/movieview.php?id=160861 @ 1:49

**Comment by danniellos94** [comment]
I mean I don't want to undermine someone's opinion and I do understand this was happenning (sometimes) in og game back in the day however I would repeat myself once more that it doesn't happen always even when I'm using dancing rune weapon in melee and it is start attacking immediately always. My question is why is that and why we don't change it? The thing is, it also looks like not intended mechanic with inconsistency behaviour which means it should be looked for.

**Comment by raethkcj** [comment]
Since this bug affects all stats that a summoned creature inherits from its owner, it also significantly impacts the usefulness of Shaman's Earth Elemental Totem (and likely other similar abilities like Army of the Dead). The primary purpose of Earth Elemental Totem is to instantly AOE Taunt a group of enemies. On paper, Earth Elemental Totem inherits 130% of the shaman's Stamina, making it decently durable. However, its max health on spawn does not include this inherited Stamina, which makes it very likely that it will instantly die before it even has the appropriate health.

In this excerpt from a combat log, you can see that the Greater Earth Elemental immediately takes a swing from High Tinker Mekkatorque for 7736, while it only had a max health of 6945:
```
4/7 11:42:20.658  SPELL_SUMMON,Player-4904-00728452,"Brogarm-ClassicPTRRealm1",0x511,0x0,Creature-0-4908-0-4-15430-00003047EB,"Earth Elemental Totem",0xa28,0x0,2062,"Earth Elemental Totem",0x1
4/7 11:42:20.658  SWING_DAMAGE,Creature-0-4908-0-4-15352-00003047EB,"Greater Earth Elemental",0x2111,0x0,Creature-0-4908-0-4-7937-00002B0946,"High Tinker Mekkatorque",0x10a48,0x0,Creature-0-4908-0-4-15352-00003047EB,Creature-0-4908-0-4-15430-00003047EB,6945,6945,0,0,0,-1,0,0,0,-4829.98,-1256.84,1455,1.6461,187,159,270,-1,1,0,0,0,nil,nil,nil
4/7 11:42:20.658  SPELL_CAST_SUCCESS,Creature-0-4908-0-4-15430-00003047EB,"Earth Elemental Totem",0x2111,0x0,0000000000000000,nil,0x80000000,0x80000000,33663,"Earth Elemental Totem",0x1,Creature-0-4908-0-4-15430-00003047EB,Player-4904-00728452,7400,7400,0,0,0,-1,0,0,0,-4826.19,-1260.10,1455,1.6461,187
4/7 11:42:20.658  SPELL_SUMMON,Creature-0-4908-0-4-15430-00003047EB,"Earth Elemental Totem",0x2111,0x0,Creature-0-4908-0-4-15352-00003047EB,"Greater Earth Elemental",0x2111,0x0,33663,"Earth Elemental Totem",0x1
4/7 11:42:20.658  SWING_DAMAGE_LANDED,Creature-0-4908-0-4-15352-00003047EB,"Greater Earth Elemental",0x2111,0x0,Creature-0-4908-0-4-7937-00002B0946,"High Tinker Mekkatorque",0x10a48,0x0,Creature-0-4908-0-4-7937-00002B0946,0000000000000000,5577841,5578000,0,0,0,-1,0,0,0,-4828.57,-1258.24,1455,4.4226,83,159,270,-1,1,0,0,0,nil,nil,nil
4/7 11:42:20.658  SWING_DAMAGE,Creature-0-4908-0-4-7937-00002B0946,"High Tinker Mekkatorque",0x10a48,0x0,Creature-0-4908-0-4-15352-00003047EB,"Greater Earth Elemental",0x2111,0x0,Creature-0-4908-0-4-7937-00002B0946,0000000000000000,5577841,5578000,0,0,0,-1,0,0,0,-4828.57,-1258.24,1455,4.4226,83,7736,16026,791,1,0,0,0,nil,nil,nil
4/7 11:42:20.658  SWING_DAMAGE_LANDED,Creature-0-4908-0-4-7937-00002B0946,"High Tinker Mekkatorque",0x10a48,0x0,Creature-0-4908-0-4-15352-00003047EB,"Greater Earth Elemental",0x2111,0x0,Creature-0-4908-0-4-15352-00003047EB,Creature-0-4908-0-4-15430-00003047EB,0,6945,0,0,0,-1,0,0,0,-4829.98,-1256.84,1455,5.5032,187,7736,16026,791,1,0,0,0,nil,nil,nil
4/7 11:42:20.658  UNIT_DIED,0000000000000000,nil,0x80000000,0x80000000,Creature-0-4908-0-4-15352-00003047EB,"Greater Earth Elemental",0x2111,0x0,0
```

When summoning the elemental with the same gear out of combat, it has 17189 after inheriting the Shaman's Stamina, so it would have survived several hits.
![image](https://user-images.githubusercontent.com/7716908/230647155-f174efc8-f56f-4549-8b0a-36b11ca060e6.png)

**Comment by danniellos94** [comment]
This got fixed instantly in cata prepatch dunno why it wasn't looked at before but maybe because of low priority to fixing the spell anyway, thank you.
