### ISSUE TITLE
[BUG] Runic Focus and Death Coil - crit heal

### ISSUE THREAD

**Issue by Miyur1** [JamminL/cata-classic-bugs#773]
#### 1.1. Description
  https://www.wowhead.com/wotlk/spell=61455/runic-focus
  https://www.wowhead.com/wotlk/spell=49895/death-coil
Healing from Death Coil is affected by the class passive skill Runic Focus, causing critical healing to be 200%
  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Do this
           2. Do that
           3. Do this again and voilá}
  #### 1.3  Source Material
https://www.youtube.com/watch?v=ohohAD8H1Pg
#### 2.1. Description
Runic Focus should not increase the critical healing from Death Coil, so the healing should be 150%
  #### 2.2 Source Material
"Unlike most casters, a Death Knight's spells cause double **damage** on critical hits."

https://www.warcraftmovies.com/movieview.php?id=160059
3:32 - crit healing with mortal 20% - 3754
3:40 - non crit heal without mortal 20% - 3129/3128
3128 * 0,8 * 1,5 = ~3754

5:10 - crit healing - 5724, non crit - 3815
5724/3815 = 1,5

https://youtu.be/sDmioR4UUGE?si=HtiGbt5GyB8_jbuF&t=276
2888 * 1,5 = ~4333

**Comment by JamminL** [comment]
Still happening in 4.4.0550
![image](https://github.com/JamminL/cata-classic-bugs/assets/107503518/75302dd1-d881-49dd-8671-28919f975c8e)
![image](https://github.com/JamminL/cata-classic-bugs/assets/107503518/4f003893-0517-433e-96ec-4364a78dfa8d)

**Comment by Avizurax7** [comment]
![image](https://github.com/JamminL/cata-classic-bugs/assets/167564762/743cfa36-c9b2-4b3e-8bfc-9bd2a9eeaf4b)

Experienced a 102k death coil HEAL today in arena, clearly bugged and has been for a very long time.

**Comment by CharWS** [comment]
https://www.bluetracker.gg/wow/topic/us-en/1843458-cataclysm-classic-hotfixes-june-13/ should be fixed now
