### ISSUE TITLE
[BUG] Judgements of the Wise giving back incorrect mana

### ISSUE THREAD

**Issue by Undertoe** [JamminL/cata-classic-bugs#801]
#### 1.1. Description
![image](https://github.com/JamminL/cata-classic-bugs/assets/3249986/65057793-9d6a-4dab-9e1b-353d271284b3)
JOTW should be restoring 3% mana per tick according to tooltips: 
![image](https://github.com/JamminL/cata-classic-bugs/assets/3249986/ede76374-7453-454b-a54b-e2f627bd3059)
![image](https://github.com/JamminL/cata-classic-bugs/assets/3249986/a2ca70bb-0312-410d-b521-d921f89603c0)
According to the current mana of this charactor (no int gear equipped) jotw should be giving ~11-12 mana per tick.
  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. have a prot paladin lvl 10+
           2. judge

**Comment by hypernormalisation** [comment]
I can confirm Judgements of the Bold is working properly. I have 284 total mana, 65 mana from intellect, 219 total. My total regenerated from a low mana state was 55, this is 25.1%.

![image](https://github.com/JamminL/cata-classic-bugs/assets/52763122/329b8e13-c463-4481-bf60-efb955132bd2)
