### ISSUE TITLE
[BUG] Upon joining group, you get an error

### ISSUE THREAD

**Issue by JamminL** [JamminL/cata-classic-bugs#803]
#### 1.1. Description
After joining a group, you get a lua error and this error message.
  #### 1.2. How to Reproduce
           1. Accept a group invite
  #### 1.3  Source Material
![image](https://github.com/JamminL/cata-classic-bugs/assets/107503518/1636d08b-b0a1-42cf-8013-da47d97e94e9)
#### 2.1. Description
N/A
  #### 2.2 Source Material
N/A

**Comment by CharWS** [comment]
there's also an updating issues when in grp if a member levels up, joins, or leaves

**Comment by Kethryllia** [comment]
Gross, thanks for the report.
