### ISSUE TITLE
[BUG] Hunter Focus lacking client-side regen update

### ISSUE THREAD

**Issue by JamminL** [JamminL/cata-classic-bugs#804]
#### 1.1. Description
Currently in beta, it seems to only be updating on specific ticks.
  #### 1.2. How to Reproduce
           1. Use up all your focus
           2. Notice how your energy regen is tick-based
  #### 1.3  Source Material
[{Video, Posts, etc..}](https://clips.twitch.tv/SavageSmoggyGooseDxCat-_YzFTGC3gPsPJuUS)
#### 2.1. Description
During OG Cata, hunter focus was updated client-side so it's a smooth regen. 
  #### 2.2 Source Material
[{Video, Posts, etc..}](https://www.youtube.com/watch?v=b1jk5nxa2nU&t=209s)

**Comment by Artemishowl** [comment]
Fixed as of April 26th
