### ISSUE TITLE
[BUG] Barrens North map doesn't align with map markers

### ISSUE THREAD

**Issue by hypernormalisation** [JamminL/cata-classic-bugs#805]
#### 1.1. Description
The map markers are all a few hundred yards north of where they should be. I'm clearly in Ratchet, the game map displays me as north of Far Watch Post.
![image](https://github.com/JamminL/cata-classic-bugs/assets/52763122/3a8349c6-e9af-48d6-b980-450d1061e9a5)

  #### 1.2. How to Reproduce
Go to barrens, open map

**Comment by raethkcj** [comment]
Fixed in or before build 54339
![image](https://github.com/JamminL/cata-classic-bugs/assets/7716908/2c835d48-893f-4b01-af2b-bbb7c38d3572)
