### ISSUE TITLE
[BUG] Cleft of Shadows fog effect too powerful and minimap bugged in the area

### ISSUE THREAD

**Issue by CharWS** [JamminL/cata-classic-bugs#806]
#### 1.1. Description
In the Cleft of Shadows there is a subtle purple fog effect, on the cataclysm beta that fog effect is currently far too thick and is completely obscuring visibility

  #### 1.3  Source Material
the current zone fog: https://cdn.discordapp.com/attachments/1072268937674371142/1215739433857581188/image.png?ex=65fdd894&is=65eb6394&hm=0b58b77d4905f12fb1fd8683c151fe17bb7c3575ef0ce8e1d8eb13fd5a2f099b&
#### 2.1. Description
The fog should be much less such that can still visibly see npcs and the ground through it
  #### 2.2 Source Material
video of the cleft of shadows circa 2010: https://www.youtube.com/watch?v=zxsnqLkQDU8

**Comment by Jumanjiofc** [comment]
fixed in build 54339
