### ISSUE TITLE
[BUG] Orgrimmar Wind Riders do not have mounts

### ISSUE THREAD

**Issue by CharWS** [JamminL/cata-classic-bugs#807]
#### 1.1. Description
The wind riders are currently swimming through the air

  #### 1.3  Source Material
https://cdn.discordapp.com/attachments/1215729195955523624/1215740009823600730/image.png?ex=65fdd91d&is=65eb641d&hm=d7014e72277706cd8a38a995e9d24abbf40c2e514d443366bfab2f8944d319fe&
#### 2.1. Description
The Orgrimmar Wind Riders should have flying mounts that they're riding on

**Comment by WaltherLeopold** [comment]
Thunder Bluff Wind Riders can also do this

https://cdn.discordapp.com/attachments/1215729195955523624/1215746042457227264/WoWScrnShot_030824_193137.jpg?ex=65fddebb&is=65eb69bb&hm=cd94386cb4ccf8b32792472ccfe3dcd2b977184a3f3d9ab0b3f88f3b920d5cc3&
