### ISSUE TITLE
[BUG] Warlock Pet Actionbars not showing and cannot use a Demon

### ISSUE THREAD

**Issue by Crixiouss** [JamminL/cata-classic-bugs#814]
#### 1.1. Description
I can't see any Pet(demon) actionbars. I've tried Scripts, macros, keybinding, relogging, deleting cache and WTF, reinstalling, etc. You are able to summon a pet, but he just follows you around. Can't use keybinds for pet send/stay/attack etc. Example; I can have my Imp out, and it shows that I have the Blood Pact buff, but I don't gain the Stamina from it and he doesn't attack or anything. It's like I don't have a demon out. Been like this for most of the Beta. I was able to relog one time and get actionbars, but then it went away.
  #### 1.2. How to Reproduce
          
           1. Summon Demon
           2. He does nothing
           
  #### 1.3  Source Material
This is a clip from my stream - https://clips.twitch.tv/ShinySnappyPuddingTBTacoRight-lW8rFsnxGowxmsSp
#### 2.1. Description
You should be able to use your demon. Send/Attack/Stay/Move to/demon spells as well as gain the buff benefiting from the demon choice(IE Blood Pact, Soul Link, etc)
  #### 2.2 Source Material

https://clips.twitch.tv/ShinySnappyPuddingTBTacoRight-lW8rFsnxGowxmsSp

**Comment by Kethryllia** [comment]
Just to check, had you purchased Control demon from the trainer?

**Comment by TamerLee** [comment]
> Just to check, had you purchased Control demon from the trainer?

Purchasing Control Demon works for a bit, but after changing specs or logging out, the ability to have your pet do anything is lost, and you can't re-learn control demon from a trainer. Unlearning and relearning your talents from a trainer does not fix the issue either.
