### ISSUE TITLE
[BUG] Rejuvenation, and likely other spells, are missing their base values

### ISSUE THREAD

**Issue by raethkcj** [JamminL/cata-classic-bugs#828]
#### 1.1. Description
Rejuvenation heals for very small amounts on the beta.
  #### 1.3  Source Material
  Rejuvenation's tooltip on a level 20 Druid on Beta:
![image](https://github.com/JamminL/cata-classic-bugs/assets/7716908/a823afea-5a3f-4a90-8179-72d274588d03)

#### 2.1. Description
  In 4.3.4, Rejuv, which is [Spell ID 774](<https://old.wow.tools/dbc/?dbc=spell&build=4.3.4.15595#page=1&colFilter[0]=exact%3A774>), had Scaling ID 62. [Scaling ID 62](<https://old.wow.tools/dbc/?dbc=spellscaling&build=4.3.4.15595#page=1&colFilter[0]=exact%3A62>) had a `Coefficient[0]` of `1.325`. This coefficient applies to the [SpellEffect with the matching index 0](<https://old.wow.tools/dbc/?dbc=spelleffect&build=4.3.4.15595#page=1&colFilter[24]=exact%3A774&colFilter[25]=exact%3A0>), aka the HoT part of Rejuv! These Coefficients (which are entirely unrelated to Spell Power Coefficients) simply get multiplied by the corresponding class+level's row in the [SpellScaling GameTable](<https://old.wow.tools/dbc/?dbc=gtspellscaling&build=4.3.4.15595#page=1>). This table contains exactly 100 rows per class, and I believe Druid begins at row 1000, which means the level 20 Druid's Rejuv should have `1.325 * 39.74547 = 52.7` additional healing.

In 4.4.0, these Coefficients have been moved directly into the [SpellEffect table entries](<https://wago.tools/db2/SpellEffect?build=4.4.0.53627&sort[SpellID]=asc&filter[SpellID]=exact%3A774&filter[EffectIndex]=exact%3A0&page=1>), so there's no longer any need to match up the indices. However, the HoT effect of Rejuv in 4.4.0 is missing that `1.325` in the `Coefficient` column, causing it to have no base healing value at any level.

Many spells that did have Coefficients in the SpellScaling table did have them properly migrated to 4.4.0, but something caused a few of them to fail to copy over. An example of a spell that was properly copied is Swipe: 4.3.4's [Spell 779](<https://old.wow.tools/dbc/?dbc=spell&build=4.3.4.15595#page=1&colFilter[0]=exact%3A779>) -> [Scaling 67](<https://old.wow.tools/dbc/?dbc=spellscaling&build=4.3.4.15595#page=1&colFilter[0]=exact%3A67>) with `Coefficient[0]` of `0.942`, copied correctly to 4.4.0's [SpellEffect](<https://wago.tools/db2/SpellEffect?build=4.4.0.53627&sort[SpellID]=asc&filter[SpellID]=exact%3A779&filter[EffectIndex]=exact%3A0&page=1>)

**Comment by Kethryllia** [comment]
👍

**Comment by raethkcj** [comment]
Fixed in 54137
