### ISSUE TITLE
[BUG] Dual spec talent switching incurs lua error, player loses access to specialization skills/passives

### ISSUE THREAD

**Issue by hypernormalisation** [JamminL/cata-classic-bugs#838]
#### 1.1. Description
Switching dual spec causes the lua error attached to the end of this report.

It also results in the player permanently losing access to their primary spec active and passive abilities.
As a dual spec prot/ret paladin, I no longer have access to Templar's Verdict as ret spec, or Avenger's shield as prot spec, nor any of the passives associated with those specs.

Judgements of the Bold is no longer applying in ret spec, I do not regenerate any mana on a cast of Judgement.

This persists across logouts.

  #### 1.2. How to Reproduce
1. Train dual spec at level 30.
2. Activate secondary spec and configure talents, you'll have access to everything you should.
3. Re-activate primary spec, at this point you've lost access to the benefits of your primary spec.
4. Switching to your secondary spec shows you've also lost access to the benefits of the secondary spec.

  #### 1.3  Source Material

The ret section of the paladin spellbook normally shows TV, JotB, 2h weapon spec abilities when in ret spec:
![image](https://github.com/JamminL/cata-classic-bugs/assets/52763122/97415aa8-71b2-49fa-b934-8a0eba740a63)

My spec and spellbook after the switch:
![image](https://github.com/JamminL/cata-classic-bugs/assets/52763122/4f433724-3663-496e-9965-b4326ef4e63f)
![image](https://github.com/JamminL/cata-classic-bugs/assets/52763122/b5ef5bf6-2af3-4505-a630-1ff65dd89cc4)

```
Message: .../AddOns/Blizzard_TalentUI/Cata/Blizzard_TalentUI.lua:554: attempt to call global 'MainMenuBar_ToPlayerArt' (a nil value)
Time: Tue Mar 12 11:07:09 2024
Count: 1
Stack: .../AddOns/Blizzard_TalentUI/Cata/Blizzard_TalentUI.lua:554: attempt to call global 'MainMenuBar_ToPlayerArt' (a nil value)
[string "@Interface/AddOns/Blizzard_TalentUI/Cata/Blizzard_TalentUI.lua"]:554: in function <.../AddOns/Blizzard_TalentUI/Cata/Blizzard_TalentUI.lua:505>

Locals: self = PlayerTalentFrame {
 0 = <userdata>
 TitleText = PlayerTalentFrameTitleText {
 }
 PortraitFrame = PlayerTalentFramePortraitFrame {
 }
 LeftBorder = PlayerTalentFrameLeftBorder {
 }
 talentGroup = 1
 portrait = PlayerTalentFramePortrait {
 }
 selectedTab = 1
 numTabs = 3
 GetTitleText = <function> defined @Interface/AddOns/Blizzard_SharedXML/Classic/SharedUIPanelTemplates.lua:829
 TopLeftCorner = PlayerTalentFrameTopLeftCorner {
 }
 Bg = PlayerTalentFrameBg {
 }
 selectedPlayerSpec = "spec1"
 hasBeenShown = true
 TopBorder = PlayerTalentFrameTopBorder {
 }
 inspect = false
 TopTileStreaks = PlayerTalentFrameTopTileStreaks {
 }
 TitleBg = PlayerTalentFrameTitleBg {
 }
 BottomBorder = PlayerTalentFrameBottomBorder {
 }
 pet = false
 Inset = PlayerTalentFrameInset {
 }
 CloseButton = PlayerTalentFrameCloseButton {
 }
 BotRightCorner = PlayerTalentFrameBotRightCorner {
 }
 RightBorder = PlayerTalentFrameRightBorder {
 }
 primaryTree = 3
 BotLeftCorner = PlayerTalentFrameBotLeftCorner {
 }
 OnLoad = <function> defined @Interface/AddOns/Blizzard_SharedXML/Classic/SharedUIPanelTemplates.lua:811
 SetTitle = <function> defined @Interface/AddOns/Blizzard_SharedXML/Classic/SharedUIPanelTemplates.lua:833
 TopRightCorner = PlayerTalentFrameTopRightCorner {
 }
}
event = "ACTIVE_TALENT_GROUP_CHANGED"
arg1 = 1
(*temporary) = nil
(*temporary) = MainMenuBarArtFrame {
 0 = <userdata>
}
(*temporary) = "attempt to call global 'MainMenuBar_ToPlayerArt' (a nil value)"
selectedSpec = "spec1"
```

**Comment by TamerLee** [comment]
This appears to be fixed in today's build. I'm able to swap specs and retain my main ability and passives.
