### ISSUE TITLE
[BUG] Unable to complete "Gasping for Breath" - Worgen starting area 

### ISSUE THREAD

**Issue by ForgeGit** [JamminL/cata-classic-bugs#843]
#### 1.1. Description
The area supposed to be flooded is currently not underwater, making it easy to get stuck.
Additionally, the NPCs that need to be "rescued" cannot be interacted with, making it impossible to finish the quest (as far as I could tell).

  #### 1.2. How to Reproduce
           1. Follow the Gilneas/Worgen storyline.
           2. Accept the quest "Gasping for Breath", which is available after fighting the forsaken invasion.
  #### 1.3  Source Material
Area should be underwater.
![2024_03_14_WowClassicB_o0tSsuWV2u1Z_00_45_40](https://github.com/JamminL/cata-classic-bugs/assets/75605537/7a431746-54ae-490a-b8c7-8a0b22c1ee72)

While possible to cross, it is easy to get stuck.
![2024_03_14_msedge_IwD8885KK63y_00_55_03](https://github.com/JamminL/cata-classic-bugs/assets/75605537/99ce38c1-c2c8-4eff-a2b3-a4afda7b30db)

Cannot interact with the NPCs, making it impossible to complete the quest and progress with the storyline.
![WowClassicB_Fq6DghsSIf](https://github.com/JamminL/cata-classic-bugs/assets/75605537/e20524eb-bd9f-47c3-881f-5ce36286c233)

#### 2.1. Description
Area should be underwater and NPCs should be able to be interacted with.

  #### 2.2 Source Material
![image](https://github.com/JamminL/cata-classic-bugs/assets/75605537/5df0c8d0-5bdf-4ae4-a325-c076fbd547b8)

![msedge_mVpG8a7LCE](https://github.com/JamminL/cata-classic-bugs/assets/75605537/ac3be617-9dc5-422d-a950-3add369641d1)

Source: https://www.youtube.com/watch?v=B3KddtuSnio From June, 2013

**Comment by ForgeGit** [comment]
FWIW I was able to progress, and eventually complete the quest:
- Very few NPCs can be picked up.
- You can pick them up, use your hearth, and repeat 3 more times to complete the quest (4 rescues)
![2024_03_14_WowClassicB_ZSdzeyV0YAPH_01_18_36](https://github.com/JamminL/cata-classic-bugs/assets/75605537/a43b6549-f8b7-4be9-a5e5-b1d99275f395)

With the guild perk, it takes 60 minutes.

**Comment by ForgeGit** [comment]
> * You can pick them up, use your hearth, and repeat 3 more times to complete the quest (4 rescues)

I am also being told you can "parkour" your way out of the ravine.

**Comment by Kethryllia** [comment]
This should be fixed with today's build; can you recheck? I'm particularly interested in knowing if all of the Drowning Watchmen are interactable now.
