### ISSUE TITLE
[BUG] "Personal Riches" cannot be obtained for "The Great Bank Heist"

### ISSUE THREAD

**Issue by raethkcj** [JamminL/cata-classic-bugs#846]
#### 1.1. Description
The bank vault minigame can be played and completed. Upon reaching 100 Vault Breaking Progress, a success message appears, but you do not receive the Personal Riches item required for the quest.
  #### 1.2. How to Reproduce
           1. Accept [The Great Bank Heist](https://www.wowhead.com/quest=14122/the-great-bank-heist)
           2. Complete the vault minigame
  #### 1.3  Source Material
![image](https://github.com/JamminL/cata-classic-bugs/assets/7716908/7d1d6053-49a9-4a00-8162-4d8dc09fcc4b)

#### 2.1. Description
The Personal Riches item should appear in your bags upon completing the vault minigame.
  #### 2.2 Source Material
https://www.youtube.com/watch?v=jpgz6bKpfoE

**Comment by CharWS** [comment]
I found I had to do it a 2nd time and interacted with a different vault, so it could also be linked to either of those things as well (first time tried the far back right vault which didn't work, 2nd time tried the front right vault which did work)

**Comment by raethkcj** [comment]
I've now done 3 different vaults and no dice =\

**Comment by danniellos94** [comment]
The quest doesn't work on warrior some people says if you have mana then the quest can be done but on other characters it's not possible.

**Comment by raethkcj** [comment]
I was able to obtain the item and complete the quest on a Warrior on the first try after build 53863.
