### ISSUE TITLE
[BUG] Lost Isles missing water

### ISSUE THREAD

**Issue by CharWS** [JamminL/cata-classic-bugs#847]
#### 1.1. Description
The water area between Wild Overlook and Town-In-A-Box is missing its water
Also makes it impossible to complete the quest Who's Top of the Food Chain Now? as the sharks are stuck evading as they can't path to the player without water.

  #### 1.3  Source Material

https://cdn.discordapp.com/attachments/1047269591841259570/1217655568240476221/image.png?ex=6604d11e&is=65f25c1e&hm=666dd0ee8354ab6e4b02d73c909d3ca5c3cb20b4e51279f2087559df7f2d7b28&

similar issue to https://github.com/JamminL/cata-classic-bugs/issues/843

**Comment by Kethryllia** [comment]
This should be fixed in today's build.

**Comment by CharWS** [comment]
4.4.0.53863 the water has indeed returned
