### ISSUE TITLE
[BUG] Worgen Mount "Running Wild" Does not have the proper mount animation.

### ISSUE THREAD

**Issue by Riastv** [JamminL/cata-classic-bugs#854]
#### 1.1. Description
When mounted with "Running Wild" Worgen mount it looks like you are sprinting instead of on all fours.
  #### 1.2. How to Reproduce
         Cast Running wild and run around.
{Video, Posts, etc..}
[### 2. https://www.youtube.com/watch?v=d8Kncptb2p0&ab_channel=NightKnight)](https://www.youtube.com/watch?v=d8Kncptb2p0&ab_channel=NightKnight)
  #### 2.1. Description
  #### 2.2 Source Material
https://www.wowhead.com/spell=87840/running-wild

**Comment by TamerLee** [comment]
This appears to have been fixed in today's build.
