### ISSUE TITLE
[BUG] Retribution Talent Sanctity of Battle talent appears non-functional

### ISSUE THREAD

**Issue by hypernormalisation** [JamminL/cata-classic-bugs#859]
#### 1.1. Description
With my current gear and the haste active from the Fury of the Encroaching Storm trinket I am able to reach about 18.3% haste.
![image](https://github.com/JamminL/cata-classic-bugs/assets/52763122/867ec118-40b4-463c-8966-42dd1c767bd6)

The tooltip cooldown for CS/DS are not being reduced from 4.5s, even as other cooldowns display in their reduced form to 2 decimal places.

I tested this is in some logged fights and could verify that successful CS spellcasts were going off 4.46 seconds apart which seems a very low reduction and could just be congruent with latency between client and server? Relevant portion of log (full log attached at end of post):

```
3/15 13:29:38.194  SPELL_CAST_SUCCESS,Player-4619-002B7F2C,"Swedge-ClassicBetaPvP",0x511,0x0,Creature-0-4615-571-56-23874-0001F1F1F0,"Thornvine Creeper",0x10a48,0x0,35395,"Crusader Strike",0x1,Player-4619-002B7F2C,0000000000000000,96,100,1435,69,7146,0,3482,3858,295,2318.18,-4688.16,117,1.8325,117

3/15 13:29:42.656  SPELL_CAST_SUCCESS,Player-4619-002B7F2C,"Swedge-ClassicBetaPvP",0x511,0x0,Creature-0-4615-571-56-23874-0001F1F1F0,"Thornvine Creeper",0x10a48,0x0,35395,"Crusader Strike",0x1,Player-4619-002B7F2C,0000000000000000,91,100,1435,69,7146,0,3619,3858,295,2318.87,-4691.74,117,1.7500,117
```

If the scaling is just naturally this weak then this may not be a bug but with almost 20% haste I would expect some visible reduction.

  #### 1.2. How to Reproduce
1. Talent into this on a high level paladin with lots of haste on gear/haste procs/haste actives.
2. Check tooltip cooldown for CS
3. Verify on a combatlog that the cooldown is not being reduced when the ability is being spammed.

  #### 1.3  Source Material
Combat log with haste trinket active:
[WoWCombatLog-031524_132640.txt](https://github.com/JamminL/cata-classic-bugs/files/14616135/WoWCombatLog-031524_132640.txt)

**Comment by Aggrend** [comment]
I believe this is fixed as of late last week (~4/24 or so)
