### ISSUE TITLE
[BUG] The Plains of Nasam Critical Errors

### ISSUE THREAD

**Issue by Undertoe** [JamminL/cata-classic-bugs#871]
#### 1.1. Description
When starting the quest [The Plains of Nasam Critical](https://www.wowhead.com/wotlk/quest=11652/the-plains-of-nasam), the game is critically erroring very quickly after starting to move.

After coming in from the critical error, the player is desynched similarly to the bug on the putricide mount.  
  #### 1.2. How to Reproduce
          {Describe the steps to reproduce the particular bug, in detail:
           1. Accept the quest [The Plains of Nasam Critical](https://www.wowhead.com/wotlk/quest=11652/the-plains-of-nasam),
           2. Enter a vehicle
           3. Begin moving towards the objective, within about 3-5 seconds of moving the game critical errors.

**Comment by Undertoe** [comment]
As a note, it seems that a number of vehicles are causing a critical error.  There may be a cause across the board that is causing this.

**Comment by Undertoe** [comment]
![image](https://github.com/JamminL/cata-classic-bugs/assets/3249986/2b6f639d-3cb8-4540-bb71-3065bb204033)
Screenshot of critical error.

**Comment by Undertoe** [comment]
[Blightbeasts be Damned! ](https://www.wowhead.com/wotlk/quest=12072/blightbeasts-be-damned) has the same critical error.  This appears to be linked to all vehicle events in game currently.

**Comment by Undertoe** [comment]
Cannons during [The Last Line Of Defense](https://www.wowhead.com/wotlk/quest=13086/the-last-line-of-defense) were also causing this crash.   It seemed like I could keep from being crashed for a bit longer by slowing my fire rate, however a number of times the client crashed with the first shot.

**Comment by Undertoe** [comment]
As of build 53863 still getting crashes in vehicles, got one on the quest [In Defense of Krom'gar Fortress](https://www.wowhead.com/cata/quest=26058/in-defense-of-kromgar-fortress)


B1565D02-3E87-4E7D-AA58-6BAB45070178

**Comment by Undertoe** [comment]
Another bugged vehicle quest: [To Battlescar!](https://www.wowhead.com/quest=26082/to-battlescar)

Crash report: F2023ACD-3D69-4EC3-BBC0-2AC4A59F182C

**Comment by Undertoe** [comment]
Seems to happen whenever i target some things within a vehicle.

**Comment by JamminL** [comment]
Haven't had any similar crash reports lately, closing for now
