### ISSUE TITLE
[BUG] Randomly crashing in Blasted Lands (near The Red Reaches)

### ISSUE THREAD

**Issue by ForgeGit** [JamminL/cata-classic-bugs#873]
#### 1.1. Description
After reaching the south-eastern area of Blasted Lands (near The Red Reaches), my game is crashing/freezing sporadically.

![2024_03_16_mspaint_i9JRHUp1gR8l_15_27_36](https://github.com/JamminL/cata-classic-bugs/assets/75605537/ab9965ba-89f3-431e-95ac-d5f56518e3ca)

This issue happened twice, each of those apart of each other by a couple hours.

- The first time, my game froze at least 3 times, each of them requiring me to alt+F4 and relog only to freeze after a few seconds. The crashing/freezing randomly stopped after the last login attempt took unusually long. There was one addon active at the time of this happening (not working, from some testing done days prior which i forgot to disable)

- The second time happened after I logged out/AFK'd in roughly the same area (trying to reproduce the issue). After relogging, my game froze and subsequently crashed again, but unlike the first time, it only crashed once. There was no addon active at the time of this happening.
![2024_03_16_WowClassicB_qLtG8ZQNqIyV_14_57_50](https://github.com/JamminL/cata-classic-bugs/assets/75605537/852097bb-9349-45b3-bce8-afeb31f28a2f)

#### 1.2. Additional Data
Level 55 mage (Uwuwuowowo - PvE server) 
1st three crashes happened around 04:34 PDT 
2nd time I crashed was 06:56 PDT

**Comment by JamminL** [comment]
Haven't had any similar crash reports, closing for now
