### ISSUE TITLE
[BUG] [QUEST] Spirits Watch Over Us 

### ISSUE THREAD

**Issue by Undertoe** [JamminL/cata-classic-bugs#874]
#### 1.1. Description
[Spirits Watch Over Us ](https://www.wowhead.com/quest=11961/spirits-watch-over-us) is currently uncompleteable, searching his corpse does nothing.

**Comment by Kethryllia** [comment]
It looks like this is the same issue as https://github.com/JamminL/cata-classic-bugs/issues/870
