### ISSUE TITLE
[BUG] Death Knight Blood Tap is not Recharging a used rune

### ISSUE THREAD

**Issue by Jumanjiofc** [JamminL/cata-classic-bugs#880]
#### 1.1. Description
When you use Blood tap while one or both blood runes are on CD, you gain the blood tap affect and the rune changes to a death rune but the rune doesn't come off cd upon cast of Blood Tap.
  #### 1.2. How to Reproduce
           1. Spend a blood Rune
           2. Press Blood tap
  #### 1.3  Source Material
![BloodTap](https://github.com/JamminL/cata-classic-bugs/assets/163789190/5246c5b5-6e7e-4894-8abb-2a5bb6aa744d)
#### 2.1. Description
When you use blood tap when a blood rune is on CD, the rune should recharge immediately as a Death Rune
  #### 2.2 Source Material
![Screenshot 2024-03-18 004002](https://github.com/JamminL/cata-classic-bugs/assets/163789190/bcde67a7-b2ca-4bad-998c-28de532c8d19)

**Comment by CharWS** [comment]
If used while frost specialized blood tap will convert one of your permanent death runes (from blood of the north) into a blood rune that you cannot turn back
