### ISSUE TITLE
[BUG] Omen of Clarity/Clearcasting not working for certain spells

### ISSUE THREAD

**Issue by ssabbyccatt** [JamminL/cata-classic-bugs#884]
#### 1.2. How to Reproduce
           1. Auto attack / cast spells until you proc Clearcasting
           2. Cast Rejuv/Regrowth
  #### 1.3  Source Material
Druid discord (https://discord.gg/qbPEv4Ey): https://discord.com/channels/253205420225724416/1171267821112676363/1219308740860182580
https://discord.com/channels/253205420225724416/1171267821112676363/1219316458245591060
#### 2.1. Description
"The Clearcasting state reduces the Mana, Rage or Energy cost of your next cast-time damaging or healing spell or offensive feral ability by 100%." per tooltip
  #### 2.2 Source Material
https://www.wowhead.com/cata/spell=16864/omen-of-clarity

**Comment by ssabbyccatt** [comment]
Seems to work properly with Balance spells except possibly Typhoon. We are unsure if Typhoon should or should not be affected by the mana reduction.

**Comment by raethkcj** [comment]
The tooltip states "cast-time damaging or healing spell" now, so it should not be affecting any instant balance/resto spells now, right? In that case it should affect Regrowth but not Rejuvenation.

**Comment by ssabbyccatt** [comment]
Yeah, realized I typo'd this lol. Need to have caffeine before typing in the future. Regrowth is working, nourish is not working. Apologies!

**Comment by ssabbyccatt** [comment]
Here's a video of Nourish not consuming Clearcasting https://discord.com/channels/253205420225724416/1171267821112676363/1219316458245591060

**Comment by Tablecloth1** [comment]
I think this is not a bug, Nourish not consuming Clearcasting is consistent with OG Cata (https://wowpedia.fandom.com/wiki/Patch_4.0.3a), which just leaves Healing Touch and Regrowth as the two healing spells which should consume it. I think this is what happens on beta (it's down rn so can't test!).
