### ISSUE TITLE
[BUG] Festering Strike isn't converting the apropriate runes.

### ISSUE THREAD

**Issue by Jumanjiofc** [JamminL/cata-classic-bugs#886]
#### 1.1. Description
When you cast Festering Strike it converts the Blood and Unholy Runes to Death runes.
  #### 1.2. How to Reproduce
           1. Set your spec to Unholy DK
           2. Cast Festering Strike on a mob/dummy
  #### 1.3  Source Material
![FesteringBug](https://github.com/JamminL/cata-classic-bugs/assets/163789190/764a0718-8826-4678-841d-9b1f84e64ee0)
#### 2.1. Description
When you cast Festering Strike while specced as Unholy it converts the Unholy Runes to Death Runes instead of the Frost Runes. The baseline talent for Unholy called Reaping dictates that the Frost runes should be converting, not the Unholy Runes.
  #### 2.2 Source Material
![Screenshot 2024-03-19 113650](https://github.com/JamminL/cata-classic-bugs/assets/163789190/7888b370-d9a2-44c8-be94-fef8ff1a143f)
![Screenshot 2024-03-19 115738](https://github.com/JamminL/cata-classic-bugs/assets/163789190/517ba6a8-bf24-4440-b3ae-5f18dd9c30bb)

**Comment by Jumanjiofc** [comment]
It is no longer converting Unholy Runes to Death runes as of beta build 4.4.0.54339 but it now only converts the left Frost rune and not the right Frost rune

**Comment by lordblackadder** [comment]
![image](https://github.com/JamminL/cata-classic-bugs/assets/12127284/8eb3207b-7fa4-4e62-a63d-98c5521a6eea)
it's broken the old way again

**Comment by CharWS** [comment]
fixed in build 54481
