### ISSUE TITLE
[BUG] Death Knight rune regeneration isn't scaling with haste

### ISSUE THREAD

**Issue by Jumanjiofc** [JamminL/cata-classic-bugs#887]
#### 1.1. Description
Runes are currently taking 10 seconds to regen regardless of what presence you are in or external/personal haste buffs/debuffs are applied to you.
  #### 1.2. How to Reproduce
           1. Start a timer and use an ability in Unholy presence.
           2. Stop timer when rune regens.
           3. Note the time difference between start and end.
           4. Repeat steps 1-3 in Blood presence.
  #### 1.3  Source Material
Unholy Presence:
![UnholyPresence](https://github.com/JamminL/cata-classic-bugs/assets/163789190/a09af6f3-a49e-49dc-aabf-833d6308f1db)

Blood presence:
![BloodPresence](https://github.com/JamminL/cata-classic-bugs/assets/163789190/8f9ba9ff-563c-4f63-85ea-21afbb0b7ae6)

#### 2.1. Description
Haste should adjust the recharge rate of your runes in Cataclysm. Most notably, as a baseline with no gear equipped, specced into Improved Unholy presence, rune regeneration time in Unholy presence should be 8.5s instead of 10s as it is currently.
  #### 2.2 Source Material
Unholy Presence baseline should have 10% rune regen adjustment:
![Screenshot 2024-03-19 125433](https://github.com/JamminL/cata-classic-bugs/assets/163789190/9e8767b4-e7fa-4e1b-84c8-c09a9586821c)
https://warcraft.wiki.gg/index.php?title=Unholy_Presence&oldid=3762680

Imp Unholy presence bonus 5% haste:
![Screenshot 2024-03-19 130153](https://github.com/JamminL/cata-classic-bugs/assets/163789190/a1f8dcb5-1d4e-484d-98db-b32b568ebf3a)
https://warcraft.wiki.gg/wiki/Improved_Unholy_Presence

**Comment by CharWS** [comment]
Related to this, the rune regeneration rate from the Runic Corruption talent proc is also not having any impact on rune regeneration

**Comment by Jumanjiofc** [comment]
Fixed as of beta build 4.4.0.54339
