### ISSUE TITLE
Crash when jumping in org [BUG]

### ISSUE THREAD

**Issue by Undertoe** [JamminL/cata-classic-bugs#895]
#### 1.1. Description
Was jumping down in org and had a memory crash.
Crash report: 587F3021-F17E-486A-B658-F6FA349B3241

**Comment by JamminL** [comment]
Possibly related, possibily unrelated, but also crashed while afk in stormwind, twice:
E373E745-8508-41F0-8246-5547113CBDDB

**Comment by JamminL** [comment]
AEA3DDCA-C6C3-4D37-9D60-6EE961A49617
