### ISSUE TITLE
[BUG] Raise Dead ghoul instantly dies when summoned if not unholy specialization

### ISSUE THREAD

**Issue by CharWS** [JamminL/cata-classic-bugs#897]
#### 1.1. Description
Title
  #### 1.2. How to Reproduce
           1. Talent into the Blood or Frost talent tree
           2. Cast Raise Dead
#### 2.1. Description
The Raise Dead ghoul should live for 1 minute or until its health is reduced to zero after being summoned.

**Comment by lordblackadder** [comment]
this one has been fixed with build 54137
