### ISSUE TITLE
[BUG] Improved Death Strike talent not increasing healing

### ISSUE THREAD

**Issue by CharWS** [JamminL/cata-classic-bugs#898]
#### 1.1. Description
Talenting into Improved Death Strike does not increase the healing done by Death Strike as it should
  #### 1.2. How to Reproduce
           1. Talent into Blood specialization but stop putting talent points into tree before Improved Death Strike
           2. Use Death Strike and note the healing done
           3. Allocate talents into Improved Death Strike
           4. Repeat step 2
  #### 1.3  Source Material
https://cdn.discordapp.com/attachments/364459574327246851/1223064587637887057/image.png?ex=66187ea9&is=660609a9&hm=0a6d3c40404894c5258bfe89c4c1dfdb415382a50b62bd5f727de3ac799902a3& The first 2 casts were without the talent, the 2nd 2 casts are with.
#### 2.1. Description
Improved Death Strike should increase the amount healed by Death Strike by 45%

**Comment by lordblackadder** [comment]
Improved DS is not supposed to increase the minimum healing based on the wiki of that time:
https://warcraft.wiki.gg/index.php?title=Improved_Death_Strike_(Wrath_Classic)&oldid=4798522

Improved DS works properly for the healing based on damage taken as per build 54137 (see https://github.com/JamminL/cata-classic-bugs/issues/902)

**Comment by mikihiso** [comment]
Doesn't mean it wasn't bugged back then too
