### ISSUE TITLE
[BUG] Glyph Panel scroll bar issues

### ISSUE THREAD

**Issue by CharWS** [JamminL/cata-classic-bugs#900]
#### 1.1. Description
Clicking on the scroll bar arrows on the Glyph pane does not properly scroll through the Glyph selections.
  #### 1.2. How to Reproduce
           1. Open Glyph pane
           2. Click the up or down arrows on the scroll bar

#### 2.1. Description
Clicking the arrows on the scroll bar should page through the list of Glyphs

**Comment by CharWS** [comment]
Scroll wheel also does not properly interact with the panel

**Comment by Avizurax7** [comment]
Bump, it's been about 2 months now and this is still bugged, very irritating 😞

**Comment by SimonBpvp** [comment]
Let's go! That's a fix, baby. Keep them coming!
