### ISSUE TITLE
[BUG] "Character Locked" after logging out. 

### ISSUE THREAD

**Issue by Undertoe** [JamminL/cata-classic-bugs#905]
#### 1.1. Description
After leveling, if you log out, the character becomes "locked"
![image](https://github.com/JamminL/cata-classic-bugs/assets/3249986/3bcdf88f-ae13-4dcb-ab0d-be4a19086439)
![image](https://github.com/JamminL/cata-classic-bugs/assets/3249986/742492e8-8600-4faf-a1e0-d56c2e8707d1)
You cannot log back in.

**Comment by JamminL** [comment]
Has something to do with hyjal

**Comment by Undertoe** [comment]
The 2nd toon is logged in deepholme.  I recommend someone try to log at 81+ in old world to see if that causes any issues

**Comment by ssabbyccatt** [comment]
Happened to me in Vashjir

**Comment by JamminL** [comment]
Still happening post-fix

**Comment by Undertoe** [comment]
Appears to be fixed @JamminL ?
