### ISSUE TITLE
Veteran of the Third War not working properly 

### ISSUE THREAD

**Issue by Xallog** [JamminL/cata-classic-bugs#915]
Current Behavior
It gives you expertise the first time you spec into blood, but upon swapping from a different spec back to Blood you lose the Expertise. 
You do not gain stamina whatsoever regardless of presence, swapping specs, relogging, etc. Similar with Outbreak where you gain the CDR when you initially spec into blood, but lose it when you swap from your dual spec back to Blood.
 
 How to Reproduce
        
           1. Spec into Blood and track your health/expertise
           2. Set up a 2nd spec and swap to that
           3. Swap back to blood and you will notice that expertise has changed and you did not gain any stamina.
           4. Process can be repeated for Outbreak CD, initially CDR is gained, lost after using dual spec to do blood > unholy > blood.

Source Material -
  Following is tested while in Blood presence
https://imgur.com/a/1quQWBu

Expected Behavior
You should gain 9% stamina and 6 expertise while in Blood spec and outbreak should be at 30 second cooldown. 
Source Material - 
https://www.wowhead.com/cata/spell=50029/veteran-of-the-third-war

**Comment by lordblackadder** [comment]
in fact VotTW is currently providing 9% strength instead of stamina which might be related to issue https://github.com/JamminL/cata-classic-bugs/issues/917

**Comment by CharWS** [comment]
fixed in build 54339
