### ISSUE TITLE
[BUG]Cloth armor bonus gives incorrect stat bonus.

### ISSUE THREAD

**Issue by TamerLee** [JamminL/cata-classic-bugs#917]
#### 1.1. Description
Mysticism, Wizardry, and Nethermancy passive spells give +5% strength instead of +5% intellect.
  #### 1.2. How to Reproduce
           1. Train Mysticism, Wizardry, or Nethermancy.
           2. Open character sheet.
  #### 1.3  Source Material
![image](https://cdn.discordapp.com/attachments/181571916384043008/1223308165991497798/image.png?ex=66196182&is=6606ec82&hm=d3241e22621f1c5d7a1a510a2677a01038ddde6b13ecac619b5cfbeddbac0419&)
![image](https://cdn.discordapp.com/attachments/181571916384043008/1223309677715132538/image.png?ex=661962eb&is=6606edeb&hm=3f3d3134989fbcb0ca96e9e33709b0729f41981c46564f6cb2941430a99baa55&)
![image](https://cdn.discordapp.com/attachments/181571916384043008/1223310120444756008/image.png?ex=66196354&is=6606ee54&hm=2fe79935ff482a4a3afafa63e9aa3f67bb50471ce5795a1e9d676192320c28f2&)
#### 2.1. Description
Mysticism, Wizardry, and Nethermancy should give +5% intellect rather than +5% strength per tooltips.
  #### 2.2 Source Material
![image](https://github.com/JamminL/cata-classic-bugs/assets/164273628/7c5bcb52-4579-4c98-b9d6-42a1e5e85a8d)
![image](https://github.com/JamminL/cata-classic-bugs/assets/164273628/1e72621e-daaf-498a-8443-741e3a7b3432)
![image](https://github.com/JamminL/cata-classic-bugs/assets/164273628/55dd9d42-2578-45ab-8ca4-192c33480766)

**Comment by Yotsutester** [comment]
Appears that Blood Death Knights are not receiving a bonus of any kind for wearing all plate armor when they should be receiving +5% Stamina as well.

**Comment by CharWS** [comment]
looks to be fixed in build 54339
