### ISSUE TITLE
Combustion and impact talent are not recognizing ignite as a dot

### ISSUE THREAD

**Issue by MEdelsteinE** [JamminL/cata-classic-bugs#918]
#### 1.1. Description
Combustion should use ignite as a dot it adds together. 
  #### 1.2. How to Reproduce
          land a critical strike on a target with a fire spell
          apply ignite to the target
          try to cast combustion on target with ignite
  #### 1.3  Source Material
{Video, Posts, etc..}
#### 2.1. Description
ignite should count as a dot that combustion and impact spreads
  #### 2.2 Source Material
{Video, Posts, etc..}

**Comment by TamerLee** [comment]
Today's build fixed the ability to spread ignite via impact. However, it's still not possible to combust ignite.

**Comment by Remidemmi** [comment]
ignite also shows up as spell damage taken rather than periodic spell damage taken in the combat log.
This also makes fire mages mastery not work with ignite at all
