### ISSUE TITLE
[BUG] Festering Strike sometimes increases duration of Ebon Plague by 9 seconds

### ISSUE THREAD

**Issue by Kilimandaros** [JamminL/cata-classic-bugs#923]
#### 1.1. Description
Festering Strike used on the target that has Ebon Plague + Frost Fever and/or Blood Plague sometimes increase the duration of Ebon Plague by 9 seconds instead of 6 (duration of Frost Fever and Blood Plague is increased by 6 though). When both Frost Fever and Blood Plague are present it happens almost every time.
  #### 1.2. How to Reproduce
           1. Choose Unholy Specialisation and spend 2 talent points in Ebon Plaguebringer.
           2. Cast Icy Touch and/or Plague Strike on the target.
           3. Cast Festering Strike on the target.
           4. Duration of Ebon Plague gets increased by 9 instead of 6 seconds for some casts.
  #### 1.3  Source Material
https://github.com/JamminL/cata-classic-bugs/assets/27138041/05f16149-d99f-489f-b4b5-1b0b972fde16
#### 2.1. Description
Festering Strike is increasing duration of Ebon Plague by constant value every time (I would assume 6 seconds).

**Comment by CharWS** [comment]
fixed in build 54481
