### ISSUE TITLE
[BUG] Deepholm quest "Resonating Blow" doesn't spawn enough boulders to complete

### ISSUE THREAD

**Issue by lordblackadder** [JamminL/cata-classic-bugs#925]
#### 1.1. Description
For the quest **Resonating Blow** you are supposed to strike a resonating crystal and then jump from boulder to boulder until you can pull Aeosera. Currently only one boulder spawns making it impossible to complete this quest
  #### 1.2. How to Reproduce
           1. Get the quest
           2. Strike the resonating crystal at the indicated location
           3. Terrath the Steady will throw you on the first boulder
           4. There is no other boulder to jump onto
  #### 1.3  Source Material
There is currently only 1 boulder
![image](https://github.com/JamminL/cata-classic-bugs/assets/12127284/c8abe8ed-6763-4ad4-82ec-673ac9426f9c)
#### 2.1. Description
There should be a chain of boulders to jump from one to another
  #### 2.2 Source Material
Picture courtesy of Wowhead
![202318-resonating-blow](https://github.com/JamminL/cata-classic-bugs/assets/12127284/4891babc-1937-491a-988e-849e32a9f89a)

**Comment by TamerLee** [comment]
Additional platforms now spawn as of build 54339, and quest can be completed. Bug is fixed.
