### ISSUE TITLE
[BUG] Crashing when attempting to move inside Throne of the Tides. Can easily reproduce.

### ISSUE THREAD

**Issue by Yotsutester** [JamminL/cata-classic-bugs#930]
1. Crash Report list:
BF28937C-3CC2-483D-A5E5-272A14A0A5C9
7D92E6EB-9BA0-4FDF-928B-55303BCC5425
BB0532BB-D2F8-465F-A4FF-218FF00DF39E
2AB6087F-3781-468D-8BED-65BD600EC4C6
204A6A9B-1E46-4F33-AA32-688BCF4F982A
D6147D44-8F6D-44B3-B8FD-FAB686280F83
8B086B0B-D415-486B-8200-67BDB6CF9860

Computer Specs:
- MacBook Pro, 13-inch, M1, 2020
- 16 GB Memory
- macOS Ventura Version 13.2.1

2. Source Link: https://streamable.com/jgfuhe

**Comment by JamminL** [comment]
Haven't heard any more reports regarding this, closing for now
