### ISSUE TITLE
[BUG] Dispels / Purges not Activating without Aura

### ISSUE THREAD

**Issue by ManneN1** [JamminL/cata-classic-bugs#931]
#### 1.1. Description

All dispels and purges are working like they did in WotLK. That is, they don't activate unless the unit actually has an aura that can be dispelled/purged.

  #### 1.2. How to Reproduce

Try to purge/dispel any unit without any auras (any class, any dispel or purge ability). It won't activate.

  #### 1.3  Source Material

![image](https://github.com/JamminL/cata-classic-bugs/assets/16864855/0d1ef6f2-39c2-4ec2-9460-ac471cbf1173)
![image](https://github.com/JamminL/cata-classic-bugs/assets/16864855/bd61282e-0a40-44a9-9aad-20f8acb5cf98)
![image](https://github.com/JamminL/cata-classic-bugs/assets/16864855/74940c85-7870-40a2-996b-05f98d305714)
![image](https://github.com/JamminL/cata-classic-bugs/assets/16864855/1eff7907-2deb-4bc8-bb5d-3327c16ad9be)
![image](https://github.com/JamminL/cata-classic-bugs/assets/16864855/6e1cdd34-b90d-4a96-92e7-9bc07b0b2e33)
![image](https://github.com/JamminL/cata-classic-bugs/assets/16864855/6d441305-dc88-497a-80fa-d7e29280e019)
![image](https://github.com/JamminL/cata-classic-bugs/assets/16864855/bb6a15f8-17d0-4327-8196-7ab519075421)

None of them actually trigger GCD, they just reset like this (with no GCD):

![image](https://github.com/JamminL/cata-classic-bugs/assets/16864855/cb8b43b5-af55-4b89-8204-10304dd46989)

### 2. Expected Behavior

The purge/dispel is supposed to cost mana and go on CD (i.e. regular global cooldown) even if there's nothing to dispel / purge.

  #### 2.2 Source Material
Blizzard explained in a [blue post](https://www.bluetracker.gg/wow/topic/us-en/24038610691-upcoming-cataclysm-dispel-mechanics/)  during the Cata development phase that they were changing this behaviour because they considered the WotLK way to have "minimal input on the part of the player".

Note: This is also common knowledge, everyone who played knows this is how it worked in Cata.

**Comment by JamminL** [comment]
This seems to be working (but is missing animation) for Priest Dispel magic. It doesn't work with the rest.

**Comment by ManneN1** [comment]
I've confirmed it still doesnt work correctly for:
Remove Corruption
Cleanse
Cure Disease
Dispel Magic (it works but doesnt show any animation, also shows the miss text if it misses which idk if that's accurate)
Remove Curse
Spellsteal
Cleanse Spirit
Purge
Tranquilizing Shot
Soothe

**Comment by Kenniflopper** [comment]
So it seems like you can now use Dispel Magic as a priest on targets without buffs to dispel / and dispel urself without any debuffs, but the animation is missing completely.

**Comment by tmpnm099** [comment]
Adding to this:
The ret paladin talent **"Acts of Sacrifice"**:
> "In addition, your Cleanse will remove one movement impairing effect if cast on yourself."

 is currently only working if you have other dispellable debuffs (magic/poison/disease) to trigger Cleanse being useable. If you only have hamstring or any normally undispellable slow/root, Cleanse will say "Nothing to dispel" even with the talent.
 
I suppose this will automatically get resolved if the above issue gets fixed, as it does dispel the slow/root if another dispellable magic/poison/disease debuff is present.

**Comment by gekkuxz** [comment]
ETA ? This is a major issue
