### ISSUE TITLE
[BUG] Visual - Arcanite Fishing Pole using pre-Cataclysm skin.

### ISSUE THREAD

**Issue by TamerLee** [JamminL/cata-classic-bugs#935]
#### 1.1. Description
Arcanite Fishing Pole is using the old pre-Cataclysm model. This was updated in patch 4.0.3a to use a unique model that exists today in retail.
  #### 1.2. How to Reproduce
           1. Equip Arcanite Fishing Pole
  #### 1.3  Source Material
![image](https://github.com/JamminL/cata-classic-bugs/assets/164273628/38540c3d-bf24-4dd5-8ddf-4b88ec8735c7)
#### 2.1. Description
Arcanite Fishing Pole should use updated Cataclysm model:
![image](https://github.com/JamminL/cata-classic-bugs/assets/164273628/88124b81-cc49-429b-b29c-816e8e775c2e)
  #### 2.2 Source Material
![image](https://github.com/JamminL/cata-classic-bugs/assets/164273628/df5fee0f-3331-4562-aa2e-df02b63e573e)
https://wowpedia.fandom.com/wiki/Arcanite_Fishing_Pole

**Comment by LordOfOtakus** [comment]
I dunno when but this has been fixed for a while. Didn’t even know there was a bug report for this.
