### ISSUE TITLE
[BUG] Hyjal quest "Flight in the Firelands" cannot be completed.

### ISSUE THREAD

**Issue by TheHate123** [JamminL/cata-classic-bugs#939]
#### 1.1. Description
The "Flap" ability you need to use with the hippogryph given to you does not thrust you forward as intended, instead it always sends you towards the left wall, no matter what direction you are facing.
  #### 1.2. How to Reproduce
           1. Press Flap
           2. See what direction you jump in
  #### 1.3  Source Material
https://www.youtube.com/watch?v=Z9hmhkDIS-4
#### 2.1. Description
It is supposed to thrust you in the direction you are facing.
  #### 2.2 Source Material
https://www.youtube.com/watch?v=V1ymqySDtAQ

**Comment by raethkcj** [comment]
Fixed in build 54339

**Comment by raethkcj** [comment]
The quest appears to be bugged in a new, unrelated way, I'll open a separate issue
