### ISSUE TITLE
 [BUG] Equipment Manager Bugged 

### ISSUE THREAD

**Issue by DaveyGreen** [JamminL/cata-classic-bugs#947]
Current Behavior

![image](https://github.com/JamminL/cata-classic-bugs/assets/166453076/35903d46-72f7-4eb1-914a-c9e3eff2d8a2)

1.1. Description

The equipment manager currently does not have any arrows, leading to abnormal amounts of clunk and sadness. See picture here:

Expected Behavior

You should be able to click on the arrows to swap out your current items or by even holding in ALT key on your keyboard.

2.1. Description

The equipment manager should have arrows next to each piece of gear for ease of access gear swapping.

1.3 Source Material

![image](https://github.com/JamminL/cata-classic-bugs/assets/166453076/d9f9d8cd-5635-42d3-8253-6242810407ba)

As you can see in this second picture, there are arrows.

**Comment by CharWS** [comment]
should be fixed as of build 54217
