### ISSUE TITLE
Heirloom items do not have stats[BUG]

### ISSUE THREAD

**Issue by Undertoe** [JamminL/cata-classic-bugs#953]
Heirlooms do not have stats currently in beta.  Only the 10% experience.
<img width="335" alt="Screenshot 2024-04-10 at 1 54 43 PM" src="https://github.com/JamminL/cata-classic-bugs/assets/3249986/50fbf527-f82a-44f5-8a5d-bff1cbecd804">

**Comment by Undertoe** [comment]
With a recent build, there are stats on heirlooms, however the stats are currently incorrect: 

![image](https://github.com/JamminL/cata-classic-bugs/assets/3249986/8a09a3b1-7c5d-4fdf-b7ed-1316a8f8b882)

**Comment by raethkcj** [comment]
Looks like this has been fixed 
![image](https://github.com/JamminL/cata-classic-bugs/assets/7716908/51b2ccc0-8588-4616-bab3-ca36ad55c38f)
