### ISSUE TITLE
[BUG][TEST-REQUEST] Nitro boost fail rate is too low

### ISSUE THREAD

**Issue by Lillyton** [JamminL/cata-classic-bugs#961]
#### 1.1. Description
Nitro boost fail rate is currently too low. (around 5%)

I haven't been able to get into the beta to test this myself, but through the grapevine I've heard it's really low. Decided to make this report to at least get some attention in case I don't make it into the beta. It does sound like it can fail in dungeons (hopefully raids too), so that sounds correct. 
#### 2.1. Description
Nitro boost should be able to fail in instances (dungeons, raids, pvp) and have a high fail chance of 50-60%. 

With the release of Cataclysm, the Blizzard team made it so Nitro boost could fail in instances. And they gave it a high chance to do so, to balance it out.

**Comment by eltreum0** [comment]
I should add to this that i've played as an engineer since cataclysm (in retail) and pretty much always had nitro boosts.

They never failed at around 50%, it was always a very low chance, id say the current chance is about correct

**Comment by eltreum0** [comment]
The proc hasnt changed since cata, you can just login into retail and test. You **can** cause the leak multiple times in a row, but over hundreds of times the leak/damage chance will be quite low

**Comment by Lillyton** [comment]
Are you serious? Took me 2 mins to prove you wrong. 
![image](https://github.com/JamminL/cata-classic-bugs/assets/137237050/6c1c7bb6-38d3-481a-a3d5-deabfd6a2614)

**Comment by eltreum0** [comment]
Most of the comments you find will be from people having very bad luck, like i said you'd need to use it over 100 times to get better numbers, its just statistics.

**Comment by Lillyton** [comment]
https://gamefaqs.gamespot.com/boards/534914-world-of-warcraft/57903260
![image](https://github.com/JamminL/cata-classic-bugs/assets/137237050/50804caa-9110-4a50-b0ac-95aee3cc58ab)
They mention it being able to fail in pvp battlegrounds.

**Comment by Lillyton** [comment]
> Most of the comments you find will be from people having very bad luck, like i said you'd need to use it over 100 times to get better numbers, its just statistics.

True, but the chances of multiple failures in a row is still lower than the current chance. And that was happening to a lot of people.

**Comment by Lillyton** [comment]
![image](https://github.com/JamminL/cata-classic-bugs/assets/137237050/70fe88a7-fdba-416d-bbd7-d03164cf41b2)
![image](https://github.com/JamminL/cata-classic-bugs/assets/137237050/f28e14a2-f7be-406c-8926-09c7bed5e2dd)
![image](https://github.com/JamminL/cata-classic-bugs/assets/137237050/b1b50bbb-bac3-4287-a8c4-828cfdfbb397)

**Comment by Lillyton** [comment]
So maybe not 50-60, but more around 40-50? I'll find more stuff tomorrow. Heading to bed soon.

**Comment by eltreum0** [comment]
Thing is that all those people are throwing wild numbers around, they need to supply data. Even myself i am just speaking from experience, i really very rarely get the debuff and i do use it quite often (pretty much all my characters have nitro boosts)

You will need to test this to confirm

**Comment by Yotsutester** [comment]
I spent the first 30 minutes of my morning afk inside Blackrock Caverns using rocket boost on CD. I had one fail.

https://imgur.com/a/xc8BsEg

Here's an imgur link with screenshots of buffs, timestamp, and character pane shown.

**Comment by Lillyton** [comment]
> I spent the first 30 minutes of my morning afk inside Blackrock Caverns using rocket boost on CD. I had one fail.
> 
> https://imgur.com/a/xc8BsEg
> 
> Here's an imgur link with screenshots of buffs, timestamp, and character pane shown.

Thank you for testing. But could you try maybe a couple dozen more times? 10 isn't that high of a test sample, even if it was currently 50%. While you could get 1/9 with a coin flip, it would be more unlikely then if it was 5%.

**Comment by Lillyton** [comment]
Some of the info I've found. Found a bunch of people complaining about it. I've not found anyone who has done a big test so far, but it did seem to be much higher than it might be at the moment. 

https://www.mmo-champion.com/search.php?searchid=71764682
Some example comments being:
![image](https://github.com/JamminL/cata-classic-bugs/assets/137237050/7c20ddf4-0e0e-4217-8d81-45dc741a1232)
![image](https://github.com/JamminL/cata-classic-bugs/assets/137237050/fe7a41f4-443d-4917-982e-75f219b7fefd)
![image](https://github.com/JamminL/cata-classic-bugs/assets/137237050/844bd733-bcc0-45c1-80b2-fe442fb8a2b9)

**Comment by ssabbyccatt** [comment]
Some of the ferals did some data collection on this. It looks like in instances, it's somewhere between 6-10% fail rate.

test 1- https://cdn.discordapp.com/attachments/1170121940778889330/1230970332400189490/image.png?ex=66354175&is=6622cc75&hm=9e11f1df052ecf8f371ee8b2f22ce8d808af8bd608d1fa42620edcd045d05b7a&
test 2 - https://cdn.discordapp.com/attachments/1170121940778889330/1230970518795190372/image.png?ex=663541a2&is=6622cca2&hm=220374205c2f9e3b2fc844bd9a47120de1b47d099738c873e79d54e8404c001e&

**Comment by ForgeGit** [comment]
(Written) sources from OG Cata seem to contradict each other, and are extremely anecdotical for the most part.

Similarly to all those anecdotes of having a "high" fail, there are other comments from back then suggesting the chance of it happening is "very low".

ZaoZao, in a 2011 post casually mentions 1/1000 uses 
![image](https://github.com/JamminL/cata-classic-bugs/assets/75605537/aaacd4a5-c634-4632-88a3-ae101bb58403)

In that same post, Halle mentions the failure rate of getting launched into the air being an "extremely rare" ocurrence. Although it is later clarified that this might be due to mixing in-combat vs out-of-combat chances, and it is specifically about getting launched in the air (not about the leak)

![image](https://github.com/JamminL/cata-classic-bugs/assets/75605537/7c63c418-818f-43e7-abf4-7a3f017c68f4)

Both taken from this thread:
https://web.archive.org/web/20120207222357/http://elitistjerks.com/f72/t125290-blood_dk_endgame_tanking_4_x/p5/#post1990475

**Comment by Lillyton** [comment]
> (Written) sources from OG Cata seem to contradict each other, and are extremely anecdotical for the most part.
> 
> Similarly to all those anecdotes of having a "high" fail, there are other comments from back then suggesting the chance of it happening is "very low".
> 
That's about the shield belt tinker. That one had a very low failure chance.

**Comment by Lillyton** [comment]
@CharWS Reopen this. One comment doesn't disprove the multiple I found.

**Comment by knasen88** [comment]
does it ever occur to you that people only complain when it fails? people arent gonna post when it works as expected. Any comments as source is 

it is pretty easy for blizzard to just check the correct value and apply it, some communication from them would obv help to end any speculation
