### ISSUE TITLE
[BUG] Pulsing spell visuals

### ISSUE THREAD

**Issue by CharWS** [JamminL/cata-classic-bugs#969]
#### 1.1. Description
A number of spell visual effects are pulsing rapidly or repeating when they should be static effects. Spells that have noticed to have the issue include: hungering cold, freezing trap, death and decay, desecration, efflorescence.

EDIT: Looks like it happens from the perspective of a third party, not when you're the ones casting these spells
  #### 1.2. How to Reproduce
           1. Cast any of the listed spells
           2. observe the spell visual

#### 2.1. Description
These spell effects should be static visuals not pulsing or repeating in the way they currently do.

If anyone knows of other spells similarly effected feel free to add on.

**Comment by JamminL** [comment]
Reopened, it's still happening with pet nova

**Comment by JamminL** [comment]
Upon further testing it seems to be enemy casted spells that pulse
