### ISSUE TITLE
Current Cast is interrupted on spell queue

### ISSUE THREAD

**Issue by Vmihai95** [JamminL/cata-classic-bugs#973]
1. Current Behavior
    While casting a steady shot / cobra shot / aimed shot, the cast is interrupted if another spell is queued mid cast
 
1.1. Description
 Aparently when the user is trying to spell queue an explosive shot for example while casting a steady shot / cobra shot, the cast is instantly stopped in order to cast the queued ability. It seems that they are behaving as a channeled ability instead of a cast ability.
 This doesn't happen only for explosive shot., it was just an example. Same behavior for serpent sting/ arcane shot/ kill shot/ multi shot etc.

 1.2. How to Reproduce
    
           1. Go to a dummy / enemy npc
           2.  Start casting steady shot
           3.  Spell queue an arcane shot  while steady shot is still in progress of being cast.

1.3  Source Material
[ Video demonstrating my steady shot cast being interrupted by pressing explosive shot](https://gyazo.com/2207d6fe6ef3a637c922515bf4443874)

2. Expected Behavior
  Current cast is not interrupted, and the spell that is queued will be fired once the cast is finished

2.1. Description
  While casting steady shot, if the user presses explosive shot for example (and has enough focus in order to use that ability), instead of the current cast being interrupted to execute the queued cast, it should wait for the steady shot to be casted first.
 It should work the same for steady shot / cobra shot / aimed shot

**Comment by dbrask** [comment]
spell queue interruption of arcane/cobra shot still seems to happen when under level 85.
