### ISSUE TITLE
[BUG] Master Shapeshifter does not increase spell dmg for moonkin

### ISSUE THREAD

**Issue by ssabbyccatt** [JamminL/cata-classic-bugs#975]
#### 1.1. Description
Master shapeshifter does not increase spell damage for moonkin at all.
  #### 1.2. How to Reproduce
           1. Respec talents
           2. Apply all talents except Master Shapeshifter
           3. Cast Insect Swarm or Moonfire to a target dummy, note damage
           5. Apply Master Shapeshifter
           6. Repeat step 3, and note that the spell did the exact same damage values as it did without Master Shapeshifter.
  #### 1.3  Source Material
https://cdn.discordapp.com/attachments/1171267821112676363/1228734430449766422/World_Of_Warcraft_2024.04.13_-_11.49.41.03.mp4?ex=662d1f1d&is=661aaa1d&hm=7cee5b8c3891265ba4cc5757039def7c28211431718a28c6334560cd097a468e&
#### 2.1. Description
Master Shapeshifter should apply a 4% spell damage bonus for moonkin
  #### 2.2 Source Material
https://www.wowhead.com/cata/spell=48411/master-shapeshifter

**Comment by ssabbyccatt** [comment]
As of 4/18 beta update, Master Shapeshifter is still not providing spell power to boomkin.

**Comment by ssabbyccatt** [comment]
As of 5/19 beta, this is still bugged.... Will see if its working on live servers tomorrow when I hit 81 and report back.

**Comment by ssabbyccatt** [comment]
This is still bugged on live servers. Additionally, it sometimes appears on your buffs, which I don't think is intended. On Wowhead, it has the "is hidden" flag.
https://cdn.discordapp.com/attachments/1171267821112676363/1242811574746349578/IMG_0360.png?ex=664f31f9&is=664de079&hm=67001167936bb9ef887daf62c6fefe9070708c704db3394c4747ac46f4c1e421&

**Comment by AidanZMoon** [comment]
Hey Ssabbyccatt,

Did some looking into on this.
This is NOT Bugged at the moment.

Master Shapeshifter correctly applies to your spell damage done while in Moonkin Form.
There is odd behaviors when you spec into anything that modifiers a stance. You must re-enter that stance after augmenting it with talents. That is how the game works systemically and changing that to make these infinite duration auras check for talents all of the time will add up.

So your steps of:
- Being out of Moonkin
- Casting Insect Swarm
- Noting the Damage
- Talenting into Master Shapeshifter
- Casting Insect Swarm
- Noting the Damage
WILL result in those damages being the same.
You need to add an extra step of shifting out of and back into Moonkin form after talenting into Master Shapeshifter.
So it will look like this if you would like to test it yourself:
- Being out of Moonkin
- Casting Insect Swarm
- Noting the Damage
- Talenting into Master Shapeshifter
- Canceling Moonkin Form
- Casting Moonkin Form
- Take note of your buffs
- Casting Insect Swarm
- Noting the Damage

Also on your last comment, Master Shapeshifter was visible back in Original Cataclysm, it ends up under your consolidated buffs so a lot of videos won't show it but here is one from 12 years ago during OG Cata
![image](https://github.com/JamminL/cata-classic-bugs/assets/137581830/9f52eeb1-67cb-4c6d-b281-4b7225a4dc93)

**Comment by ssabbyccatt** [comment]
> Hey Ssabbyccatt,
> 
> Did some looking into on this. This is NOT Bugged at the moment.
> 
> Master Shapeshifter correctly applies to your spell damage done while in Moonkin Form. That being said, there are some odd behaviors when you spec into anything that modifies a stance. You must re-enter that stance after augmenting it with talents. That is how the game works systemically and changing that to make these infinite duration auras check for talents all of the time will add up.
> 
> So your steps of:
> 
> * Being out of Moonkin
> * Casting Insect Swarm
> * Noting the Damage
> * Talenting into Master Shapeshifter
> * Casting Insect Swarm
> * Noting the Damage
> 
> WILL result in those damages being the same. You need to add an extra step of shifting out of and back into Moonkin form after talenting into Master Shapeshifter. This occurs with anything similar to this, like Blood Death Knight Improved Blood Presence crit reduction, and I believe Leader of the Pack has the same behavior where you have to swap out of and back into form if you talent into it to have it apply. So it will look like this if you would like to test it yourself:
> 
> * Being out of Moonkin
> * Casting Insect Swarm
> * Noting the Damage
> * Talenting into Master Shapeshifter
> * Canceling Moonkin Form
> * Casting Moonkin Form
> * Take note of your buffs
> * Casting Insect Swarm
> * Noting the Damage
> 
> Also on your last comment, Master Shapeshifter was visible back in Original Cataclysm, it ends up under your consolidated buffs so a lot of videos won't show it but here is one from 12 years ago during OG Cata ![image](https://private-user-images.githubusercontent.com/137581830/332997575-9f52eeb1-67cb-4c6d-b281-4b7225a4dc93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MTk0NTQsIm5iZiI6MTcxNjgxOTE1NCwicGF0aCI6Ii8xMzc1ODE4MzAvMzMyOTk3NTc1LTlmNTJlZWIxLTY3Y2ItNGM2ZC1iMjgxLTRiNzIyNWE0ZGM5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QxNDEyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZGMwOWU5ZWRlNDRkNTM2ZTc3MjMyNGJmNWFmMzE1ZmEzNGU1ZjdkYmIwNzhhZGI0ODEyZDFkMGUzYzllNTE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hwGDnH15IesL5KLKwB2TzX8rfu7JnWeHQTv5vFwoeAI)

Wild, that totally explains it; we had no idea we'd need to swap in/out of form after respec, but that did in fact do the trick! Really appreciate you looking into this!
