### ISSUE TITLE
[BUG] Mastercraft Kalu'ak Fishing Pole has level requirement

### ISSUE THREAD

**Issue by sofakingboss** [JamminL/cata-classic-bugs#978]
#### 1.1. Description
Mastercraft Kalu'ak Fishing Pole has a level requirement of 80 on it.
  #### 1.2. How to Reproduce
           1. Obtain Mastercraft Kalu'ak Fishing Pole item or item link
           2. Mouseover Mastercraft Kalu'ak Fishing Pole item or item link
           3. Observe Mastercraft Kalu'ak Fishing Pole's item or item link tooltip
  #### 1.3  Source Material
![cata beta requirement](https://github.com/JamminL/cata-classic-bugs/assets/166942427/8e647758-beb7-46f8-8621-8cb77993be01)
#### 2.1. Description
Mastercraft Kalu'ak Fishing Pole doesn't have a level requirement in retail or original wrath / cataclysm.
  #### 2.2 Source Material
![pole no level req](https://github.com/JamminL/cata-classic-bugs/assets/166942427/855eec55-d6e9-4229-8a5e-c979f93750fd)
![fishing pole retail](https://github.com/JamminL/cata-classic-bugs/assets/166942427/4ae2d181-ad52-40e5-a799-cb88fc3d46f2)
![wowpedia record](https://github.com/JamminL/cata-classic-bugs/assets/166942427/f3974aaa-087d-41ae-ac71-a9e6bb85dcd8)

**Comment by LordOfOtakus** [comment]
Not a bug. A level requirement was added midway through Wrath Classic to prevent low level twinks from using it as a weapon.
