### ISSUE TITLE
[BUG] Racial Resistances are not stacking with Greater Blessing of Kings, Mark of the Wild, or Paladin Resistance Aura

### ISSUE THREAD

**Issue by Yotsutester** [JamminL/cata-classic-bugs#982]
#### 1.1. Description
Whenever the player is buffed by Greater Blessing of Kings or Mark of the Wild, the Racial Bonuses are not stacking.
  #### 1.2. How to Reproduce
           1. Open Character Sheet
           2. Receive a buff that is supposed to increase your resistances
           3. Notice the value does not increase over the give buff's value
  #### 1.3  Source Material
https://imgur.com/a/QjdIgSV

#### 2.1. Description
Expected that the Racial Resistance Passives are additive with various raid buffs
  #### 2.2 Source Material
None so far

**Comment by lordblackadder** [comment]
Many comments from that expansion indicating that cata racial resistance bonuses don't stack with MotW/BoK

https://www.wowhead.com/spell=20551/nature-resistance#comments
https://www.wowhead.com/spell=68976/aberration#comments
https://www.wowhead.com/spell=20579/shadow-resistance#comments
