### ISSUE TITLE
[BUG] Agility is providing Armor when it should not

### ISSUE THREAD

**Issue by NerdEgghead** [JamminL/cata-classic-bugs#983]
#### 1.1. Description
Agility on gear continues to provide 2 Armor per point in the Cataclysm Classic Beta, when it stopped doing so in Patch 4.0.1 of original Catcalysm.
  #### 1.2. How to Reproduce
           1. Note down the Agility and Armor of a naked Druid in caster form.
           2. Equip an item with a known base armor and Agility contribution.
           3. Again note down the final Agility and Armor in caster form, and compare it to the expected increase given the Druid's talents.
  #### 1.3  Source Material
**Example test case:**

Talents screenshot (only Thick Hide should be impacting Armor values)
![image](https://github.com/JamminL/cata-classic-bugs/assets/69437062/4d52f476-44de-4053-95f6-459cbfe89798)

Naked character sheet
![image](https://github.com/JamminL/cata-classic-bugs/assets/69437062/3473b72c-8acf-4d84-ada7-d6f949c4fbd1)

Character sheet with one Agility piece equipped
![image](https://github.com/JamminL/cata-classic-bugs/assets/69437062/9e5f833e-d602-48a1-b7a5-e3b007602952)

Expected final armor should be `180 + 1217*1.1 = 1518`. 
Observed final armor is `180 + 1217*1.1 + (301-90)*2 = 1941`, indicating that the Agility on the equipped helmet is providing 2 Armor per point like it did in WotLK.
#### 2.1. Description
Agility should no longer increase armor as of Patch 4.0.1, the same time when the stat was changed to provide 2 Attack Power per point for Rogues, Shamans, and Druids.
  #### 2.2 Source Material
Wiki page showing the undocumented change in 4.0.1:
https://warcraft.wiki.gg/wiki/Attributes_(pre-6.0)#Patch_changes

Old bear tanking guide from Patch 4.1 confirming the lack of Armor contribution from Agility:
https://www.mmo-champion.com/threads/868401-Bear-Guide-4-1

**Comment by kenthklui** [comment]
The bug appears to be fixed as per 2024-05-26. Tested with a scroll of agility.
