### ISSUE TITLE
[BUG] Blood Tap generating runic power

### ISSUE THREAD

**Issue by CharWS** [JamminL/cata-classic-bugs#988]
#### 1.1. Description
Using Blood Tap generates 10 runic power when used
#### 2.1. Description
Blood tap shouldn't generate any runic power in cataclysm

**Comment by lordblackadder** [comment]
Rune Tap not providing RP is as it was in cata: 
https://youtu.be/zi4j8fXAwCA?t=145
https://youtu.be/Na7GU6UwA08?t=66

Blood Tap providing 10 RP is indeed a bug however. It is the case in WotLK also, but was removed in 4.0.1:
https://warcraft.wiki.gg/wiki/Blood_Tap
https://youtu.be/dLvqKULmwBw?t=455

**Comment by lordblackadder** [comment]
Fixed as of build 54481, maybe even before that
![image](https://github.com/JamminL/cata-classic-bugs/assets/12127284/b97ccaeb-fb10-46b7-b695-9a4bed8f6177)
