### ISSUE TITLE
Cataclysm Trapping Visual Missing

### ISSUE THREAD

**Issue by Kenniflopper** [JamminL/cata-classic-bugs#991]
### 1. Current Behavior
Currently on the beta, if you use a trap while moving its missing the effect added in Cataclysm.

  #### 1.2. How to Reproduce
  
  Move around on a hunter and press any trap while u keep moving, it will not do any sort of animation of you laying the trap.
    
  #### 1.3  Source Material
https://www.youtube.com/watch?v=uXzUFwVYI9E

### 2. Expected Behavior

In Cataclysm an animation was added when you were laying a trap while moving, which would be cancelled upon using any sort of other animation.

  #### 2.2 Source Material
  https://www.youtube.com/clip/UgkxkuyuD5WNkD7OvgmaGGPFpgvio5mty4F1

**Comment by Snipin** [comment]
Trap animation is now fixed, however it lasts too long. (looks like it replays the animation for a second time)

Also, the animation should be cancellable. 
So for example, lay a trap and cast mend pet or an aspect, and the character should switch to the next animation

Example of current animation bug on beta
https://youtu.be/HT2QEbIJMO8

**Comment by Kenniflopper** [comment]
Yeah the animation is too long now and doesnt seem to break upon using other animations abilities
